### PR TITLE
Fix JPEG-XL screenshot contains wrong color attributes, #5212

### LINKED ISSUE #5212: JPEG-XL screenshot contains wrong color attributes
### IINA Version

develop@6cc048e1b56e50c5467b8e8cddb4bba66a5e7d71

### Release Channel

Other

### macOS Version

13.6.9

### Steps to Reproduce

```text
- Start IINA
- Click on  `Settings…` under the `IINA` menu
- The settings panel appears
-  Scroll down to the bottom of the window
-  In the `Screenshots` section change the `Format` setting to `JPEG XL (jxl)`
-  Enable the setting `Show previews after taking screenshots`
-  Start playing the HDR YouTube video [The World in HDR in 4K (ULTRA HD)](https://www.youtube.com/watch?v=tO01J-M3g0U)
-  Under the `Playback` menu click on `Take a Screenshot`
-  After a second or two the screenshot preview will be displayed in the OSD
-  Notice the screenshot displayed in the preview is dark and does not match the video
```

### Expected Behavior

Taking a screenshot of a HDR video in [JPEG XL](https://jpeg.org/jpegxl/) format results in a HDR screenshot.

### Actual Behavior

Taking a screenshot of a HDR video in [JPEG XL](https://jpeg.org/jpegxl/) format results in a screenshot with the wrong color attributes:
screenshot

This was testing and working back on June 19, 2024. Something has broken this feature.

With IINA build from `develop` @ 6cc048e1b56e50c5467b8e8cddb4bba66a5e7d71 the resulting screenshot has these attributes:

```text
low-batt@gag Screenshots$ jxlinfo The\ World\ in\ HDR\ in\ 4K\ \(ULTRA\ HD\)-0188.jxl 
JPEG XL file format container (ISO/IEC 18181-2)
JPEG XL image, 3840x2160, lossy, 16-bit RGB+Alpha
Color space: RGB, D65, sRGB primaries, sRGB transfer function, rendering intent: Relative
low-batt@gag Screenshots$ 
```

A correct screenshot taken by IINA from back on June 19, 2024:
```text
low-batt@gag Screenshots$ jxlinfo The\ World\ in\ HDR\ in\ 4K\ \(ULTRA\ HD\)-0183.jxl 
JPEG XL image, 3840x2160, lossy, 16-bit RGB
intensity_target: 10000.000000 nits
min_nits: 0.000000
relative_to_max_display: 0
linear_below: 0.000000
Color space: RGB, D65, Rec.2100 primaries, PQ transfer function, rendering intent: Relative
low-batt@gag Screenshots$ 
```

Running mpv 0.39.0:
`mpv --log-file=mpv.log --screenshot-format=jxl --vo=gpu-next --target-colorspace-hint ~/Movies/The\ World\ in\ HDR\ in\ 4K\ \(ULTRA\ HD\).mp4`

The screenshot has these attributes:
```text
low-batt@gag ~$ jxlinfo mpv-shot0005.jxl 
JPEG XL file format container (ISO/IEC 18181-2)
JPEG XL image, 3840x2160, lossy, 16-bit RGB+Alpha
intensity_target: 10000.000000 nits
min_nits: 0.000000
relative_to_max_display: 0
linear_below: 0.000000
Color space: RGB, D65, Rec.2100 primaries, PQ transfer function, rendering intent: Relative
low-batt@gag ~$ 
```

The `mpv.log` for mpv shows:
```
[  13.272][v][cplayer] Starting screenshot: 'mpv-shot0005.jxl'
[  13.272][v][screenshot] input: 3840x2160 [0:0] rgba64 rgb/bt.2020/pq/full/display CL=mpeg1/jpeg
[  13.272][v][screenshot] will convert image to rgba64
[  13.272][v][screenshot] using 8 threads for scaling
[  13.274][v][screenshot] Using zimg.
[  13.283][d][screenshot] mapped color params:
[  13.283][d][screenshot]   trc = smpte2084
[  13.283][d][screenshot]   primaries = bt2020
[  13.283][d][screenshot]   range = pc
[  13.283][d][screenshot]   colorspace = gbr
[  13.283][d][screenshot]   chroma_location = center
[  15.096][i][cplayer] Screenshot: 'mpv-shot0005.jxl'
```

Whereas the `mpv.log` for IINA shows:
```text
[  56.626][v][cplayer] Starting screenshot: '/Users/low-batt/Pictures/Screenshots/The World in HDR in 4K (ULTRA HD)-0188.jxl'
[  56.626][v][screenshot] input: 3840x2160 [0:0] rgba64 rgb/bt.709/srgb/full/display CL=mpeg1/jpeg
[  56.626][v][screenshot] will convert image to rgba64
[  56.626][v][screenshot] using 8 threads for scaling
[  56.629][v][screenshot] Using zimg.
[  56.645][d][screenshot] mapped color params:
[  56.645][d][screenshot]   trc = iec61966-2-1
[  56.645][d][screenshot]   primaries = bt709
[  56.645][d][screenshot]   range = pc
[  56.645][d][screenshot]   colorspace = gbr
[  56.645][d][screenshot]   chroma_location = center
[  57.318][i][cplayer] Screenshot: '/Users/low-batt/Pictures/Screenshots/The World in HDR in 4K (ULTRA HD)-0188.jxl'
```

There was a previous problem with screenshot color spaces, mpv issue, https://github.com/mpv-player/mpv/issues/10988, but that should be fixed.

There is also a warning in the IINA log file when generating the screenshot preview that needs to be investigated:
```text
21:31:20.578 [iina][d] Using FFmpeg to decode screenshot: file:///Users/low-batt/Pictures/Screenshots/The%20World%20in%20HDR%20in%204K%20(ULTRA%20HD)-0188.jxl
21:31:20.578 [ffmpeg][d] Creating image with contents of file: /Users/low-batt/Pictures/Screenshots/The World in HDR in 4K (ULTRA HD)-0188.jxl
21:31:20.822 [ffmpeg][d] Decoded libjxl JPEG XL frame
21:31:20.822 [ffmpeg][d] Pixel format: rgba64le (105)
21:31:20.822 [ffmpeg][d] Color range: pc (2)
21:31:20.822 [ffmpeg][d] Color primaries: bt709 (1)
21:31:20.822 [ffmpeg][d] Color transfer: iec61966-2-1 (13)
21:31:20.822 [ffmpeg][d] Color space: gbr (0)
21:31:20.822 [ffmpeg][d] Width: 3840
21:31:20.822 [ffmpeg][d] Height: 2160
21:31:20.822 [ffmpeg][w] Unexpected pixel format: rgba64le (105)
21:31:20.906 [ffmpeg][d] Selected kCGColorSpaceDeviceRGB color space for bitmap image
21:31:20.906 [ffmpeg][d] Creating bitmap image with 8 bits per component and 4 bytes per pixel
```

### Crash Report or Process Sample

_No response_

### Logs

[iina.log](https://github.com/user-attachments/files/17359075/iina.log)

[mpv.log](https://github.com/user-attachments/files/17359076/mpv.log)

### Sample Files

_No response_

### How often can you reproduce the issue

Every time.

### Required Actions

- [X] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [X] I tested with the Nightly build and confirmed the issue is not fixed.
- [X] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Change `MPVController.mpvInit` to configure mpv to use software rendering for screenshots in JPEG XL format
- Change `FFmpegController.createNSImageWithContentsOfURL` to take into account the gamma when choosing the color space
- Change `createNSImageWithContentsOfURL` to use the Accelerate Framework method `vImageConvert_16Uto16F` to convert pixel components to short floating point

Using software rendering for JPEG XL screenshots is a workaround for mpv issue #15107, HDR screenshots are unimplemented (gpu/gpu-next).

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #5212.

---

**Description:**

### CODE REVIEW

File: iina/FFmpegController.m [hunk 1]
```diff
@@ -528,6 +529,7 @@ + (NSImage *)createNSImageWithContentsOfURL:(nonnull NSURL *)url
              pFrame->format);
       case AV_PIX_FMT_ARGB: // WebP with screenshot-webp-lossless mpv option enabled.
       case AV_PIX_FMT_RGB24: // JPEG XL SDR video.
+      case AV_PIX_FMT_RGBA64LE: // JPEG XL SDR video.
```
Comment (saagarjha) [inline iina/FFmpegController.m:532]: Hmm, maybe I am not understanding the scope of these changes. Why is this here?

Comment (low-batt) [reply iina/FFmpegController.m:532]: The Issue #5212 originated from issue #5200 which was about properly handling a video with BT.2020 primaries and a SDR gamma. A JPEG XL screenshot of that kind of video uses this pixel format and before this change was triggering the "Unexpected pixel format" warning.

**Review by uiryuu — APPROVED** [review]

**Review by saagarjha — APPROVED** [review]
Ok, lgtm. Please squash your two commits before this gets merged
