### PR TITLE
Fix OSC next/prev media buttons skip files, #5611

### LINKED ISSUE #5611: Back/Skip (when set to "Next/Previous Media") always skips 1 file
### IINA Version

1.4.0-beta1 Build 152

### Release Channel

Beta

### macOS Version

26.0 Beta (25A5316i)

### Steps to Reproduce

- Open a video file from a folder containing multiple video files
- Make sure in IINA settings > UI, you have set "Use left/right button for:" = Previous / Next Media
- Click the ">>" button in IINA On Screen Controller

### Expected Behavior

Play the next/previous file from the folder the currently playing video is in.

### Actual Behavior

Instead of playing the _next_ video, it plays the video _after_ the next. It always skips one video, same for using "<<" 

### Crash Report or Process Sample

_No response_

### Logs

_No response_

### Sample Files

_No response_

### How often can you reproduce the issue

Every time

### Required Actions

- [x] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [ ] I tested with the Nightly build and confirmed the issue is not fixed.
- [ ] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Rename the `updateArrowButtonImage` method in `MainWindowController` to be `updateArrowButtons`
- Change `updateArrowButtons` to configure the button type to be `momentaryPushIn` or `multiLevelAccelerator` based on what the OSC buttons are set to do
- Change the `leftButtonAction` and `rightButtonAction` methods to handle `momentaryPushIn` buttons

With these changes the OSC left and right arrow buttons only change the position in the playlist by one file. This also corrects the behavior of the buttons when set to seek to only seek once.

This also corrects the behavior where a pressure sensitive device was providing tactile feedback when the buttons were configured to change the position in the playlist, or seek forward. As the buttons only take into account the pressure being applied when the buttons are set to control playback speed it was inappropriate to be providing pressure feedback when the buttons were not controlling the speed.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #5611.

---

**Description:**

### CODE REVIEW

**Comment by low-batt** [comment]
See [this comment](https://github.com/iina/iina/issues/5611#issuecomment-3420031030) for an analysis of what is going wrong.

File: iina/MainWindowController.swift [hunk 1]
```diff
@@ -2897,16 +2923,24 @@ class MainWindowController: PlayerWindowController {
...
+  /// The behavior of the button depends upon the `Use left/right button for` setting found in the
+  /// `On Screen Controller` section on the `UI` tab of IINA's settings. For most settings the button is configured to be a
+  /// [momentaryPushIn](https://developer.apple.com/documentation/appkit/nsbutton/buttontype/momentarypushin)
+  /// button. However if the button is set to control playback speed the button is configured to be a
+  /// [multiLevelAccelerator](https://developer.apple.com/documentation/appkit/nsbutton/buttontype/multilevelaccelerator)
+  /// button. This allows the user to control the speed using pressure when using devices that support pressure sensitivity.
+  /// - Parameter sender: The button invoking this action.
   @IBAction func rightButtonAction(_ sender: NSButton) {
-    if arrowBtnFunction == .speed {
+    log("$$$$$$$$ \(sender)")
```
Comment (uiryuu) [inline iina/MainWindowController.swift]: Maybe remove this before merging?

**Review by uiryuu — CHANGES_REQUESTED** [review]

File: iina/MainWindowController.swift (hunk 1 above)
Comment (low-batt) [reply iina/MainWindowController.swift]: Embarrassing. Good catch! Fixed.

**Comment by Balamiere** [comment]
Can we please release this fix into a general release? It's been very annoying not being able to skip to a next episode properly. Thank you.

**Comment by lhc70000** [comment]
We are planning a release in several days.

**Comment by Balamiere** [comment]
> We are planning a release in several days.

yay! big thank you! can't wait for the release :)

**Comment by Balamiere** [comment]
It's been more than a week. Home many days is "several days"? Do we have a tentative date for planned release?

**Comment by uiryuu** [comment]
We're doing some final tests and some final adjustments. We hope we can release in a day or so. Please be patient and stay tuned.

**Comment by lhc70000** [comment]
We had a build last weekend but found some issues needing urgent fix (see the current develop branch). We are releasing it in hours.

**Comment by Balamiere** [comment]
I can see 1.4.2 is released now! Yay! Thank you, thank you, thank you!
