### PR TITLE
Fix cannot open display link, #4520

### LINKED ISSUE #4520: Cannot open display link.  The application will now close
**System and IINA version:**

- macOS  Ventura 13.4.1 (c)

- IINA  1.3.2 

**Expected behavior:**

App stays open in the background
**Actual behavior:**
Blank window with message "Cannot open display link. The application will now close

  Cannot find any stack trace reports

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**
Happens after the app is running in the background.  Very often.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will change the method `PlayerCore.pause` to not call `MPVControler.setFlag` if the `mpv` core is idle or stopping.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4520.

---

**Description:**

### CODE REVIEW

File: iina/PlayerCore.swift [hunk 1]
```diff
@@ -647,7 +647,18 @@ class PlayerCore: NSObject {
     info.isPaused ? resume() : pause()
   }
 
+  /// Pause playback.
+  ///
+  /// - Important: Setting the `pause` property will cause `mpv` to emit a `MPV_EVENT_PROPERTY_CHANGE` event. The
```
Comment (uiryuu) [inline iina/PlayerCore.swift:652]: Should we also block some of other `setFlag`s (if not all) when the mpv core is idle or stopping?

Comment (low-batt) [reply iina/PlayerCore.swift:652]: I did not do any sort of cleanup or changes for potential bugs with 1.3.4 in mind. Since 1.3.3 added regressions I have been intentionally keeping fixes to the minimum required change. The problem at hand was not reproducible and had to be diagnosed through code reading and experiments. This was another reason to minimize this fix. If the user reports this fixes the problem then that validates the guess as to what is going wrong.

Ok to merge as is?

One of the goals I listed for 1.4.0 was to fix the thread related problems in `MPVController` and refactor that class as well as `PlayerCore`. I thought it was best to wait for a Beta release to due to extensive refactoring. One of the planned changes is to switch to a state enumeration to eliminate these separate flags. But first the thread related problems need to be resolved. My thoughts on that are that `MPVController` should not be doing so much work using its own queue. That queue/thread should be focused on reading the events from `mpv` and then in most cases dispatching the work to the main thread. As it is now you can see cases where it is half done on  `MPVController` thread and then dispatched to main. This is causing data races.
