### PR TITLE
Fix crash in PlaybackInfo.calculateTotalDuration, #5095

### LINKED ISSUE #5095: Crash in PlaybackInfo.calculateTotalDuration
**System and IINA version:**

- macOS 13.6.3
- IINA `develop` @ 108c93c3860be882546ea8c95cfa668aa5b565b4

**Expected behavior:**
IINA does not crash.

**Actual behavior:**
Rarely IINA will crash in `PlaybackInfo.calculateTotalDuration`. This occured during heavy stress testing of the start/quit cycle. This was reproduced with a development build, however it is not a regression and should be reproducible with IINA 1.3.5.

Likely the problem is that not all access to `playlist` property in `PlaybackInfo` is locked.

<details>
<summary><b>Crash report:</b></summary>

```
Thread 164 Crashed::  Dispatch queue: IINAPlaybackInfoLock
0   libswiftCore.dylib            	       0x1b40d5030 closure #1 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 308
1   libswiftCore.dylib            	       0x1b40d4eb4 closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 344
2   libswiftCore.dylib            	       0x1b40d4830 _assertionFailure(_:_:file:line:flags:) + 188
3   libswiftCore.dylib            	       0x1b40b497c Array._checkSubscript(_:wasNativeTypeChecked:) + 160
4   libswiftCore.dylib            	       0x1b40b7ba8 Array.subscript.read + 180
5   libswiftCore.dylib            	       0x1b40b7ac0 protocol witness for Collection.subscript.read in conformance [A] + 68
6   libswiftCore.dylib            	       0x1b40a3f64 IndexingIterator.next() + 512
7   IINA                          	       0x1025d2440 closure #1 in PlaybackInfo.calculateTotalDuration() + 228 (PlaybackInfo.swift:259)
8   IINA                          	       0x1025d4e88 partial apply for closure #1 in PlaybackInfo.calculateTotalDuration() + 20
9   libswiftDispatch.dylib        	       0x1b9609920 partial apply for thunk for @callee_guaranteed () -> (@out A, @error @owned Error) + 28
10  libswiftDispatch.dylib        	       0x1b96099f4 thunk for @callee_guaranteed () -> (@out A, @error @owned Error)partial apply + 16
11  libswiftDispatch.dylib        	       0x1b9607c94 closure #1 in closure #1 in OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 188
12  libswiftDispatch.dylib        	       0x1b9609870 partial apply for thunk for @callee_guaranteed () -> () + 28
13  libswiftDispatch.dylib        	       0x1b96035a4 thunk for @escaping @callee_guaranteed () -> () + 28
14  libdispatch.dylib             	       0x1a51d0400 _dispatch_client_callout + 20
15  libdispatch.dylib             	       0x1a51df97c _dispatch_lane_barrier_sync_invoke_and_complete + 56
16  libswiftDispatch.dylib        	       0x1b96087d0 implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 180
17  libswiftDispatch.dylib        	       0x1b96090b8 partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>(execute:) + 56
18  libswiftDispatch.dylib        	       0x1b9607aa4 OS_dispatch_queue._syncHelper<A>(fn:execute:rescue:) + 396
19  libswiftDispatch.dylib        	       0x1b9608390 OS_dispatch_queue.sync<A>(execute:) + 168
20  IINA                          	       0x1025d2318 PlaybackInfo.calculateTotalDuration() + 108 (PlaybackInfo.swift:257)
21  IINA                          	       0x102935f00 PlaylistViewController.refreshTotalLength() + 464 (PlaylistViewController.swift:191)
22  IINA                          	       0x102941260 closure #2 in PlaylistViewController.tableView(_:viewFor:row:) + 1808 (PlaylistViewController.swift:546)
23  IINA                          	       0x10269b560 thunk for @escaping @callee_guaranteed @Sendable () -> () + 48
24  libdispatch.dylib             	       0x1a51ce874 _dispatch_call_block_and_release + 32
25  libdispatch.dylib             	       0x1a51d0400 _dispatch_client_callout + 20
26  libdispatch.dylib             	       0x1a51d7a88 _dispatch_lane_serial_drain + 668
27  libdispatch.dylib             	       0x1a51d85f8 _dispatch_lane_invoke + 384
28  libdispatch.dylib             	       0x1a51e3244 _dispatch_workloop_worker_thread + 648
29  libsystem_pthread.dylib       	       0x1a537c074 _pthread_wqthread + 288
30  libsystem_pthread.dylib       	       0x1a537ad94 start_wqthread + 8
```
</details>

Full report:
[Crash Report.txt](https://github.com/user-attachments/files/16405210/Crash.Report.txt)

<br>

**Steps to reproduce:**
Run a script that starts and quits IINA over and over again. Make sure the IINA setting `Add files in the same folder automatically` found in the `Playlist` section on the `General` tab is enabled. Keep running the script until the problem reproduces. It is rare and hard to reproduce with a test.

- [x] MPV does not have this problem.

**How often does this happen?**
Rarely.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Add the `Atomic` property wrapper to `PlaybackInfo.playlist`
- Remove `PlaybackInfo.lockQueue` and instead use the playlist lock to single thread access to the playlist itself as well as the playlist cache
- Change all code that was directly accessing the playlist to use the lock

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #5095.

---

**Description:**

### CODE REVIEW

File: iina/PlaylistViewController.swift [hunk 1]
```diff
@@ -644,9 +650,13 @@ class PlaylistViewController: NSViewController, NSTableViewDataSource, NSTableVi
   }
 
   @IBAction func contextMenuPlayInNewWindow(_ sender: NSMenuItem) {
-    let files = selectedRows!.enumerated().map { (_, i) in
-      URL(fileURLWithPath: player.info.playlist[i].filename)
-    }
+
```
Comment (uiryuu) [inline iina/PlaylistViewController.swift]: Extra line?

**Review by uiryuu — APPROVED** [review]
Nice and clean changes to me

File: iina/PlaylistViewController.swift (hunk 1 above)
Comment (low-batt) [reply iina/PlaylistViewController.swift]: Fixed!
