### PR TITLE
Fix app can quit while playback history is being saved, #5107

### LINKED ISSUE #5107: App can quit while playback history is being saved
**System and IINA version:**

- macOS 13.6.3
- IINA `develop` @ ae5d2e3d1cd6d063793efb92812800769a97132e

**Expected behavior:**
Playback history is reliable.

**Actual behavior:**
Under heavy load IINA may terminate while playback history is being saved to the history plist file. Very rarely this can corrupt the file resulting in this error the next time IINA starts:
```text
22:00:16.449 [iina][e] Failed to read playback history file /Users/low-batt/Library/Application Support/com.colliderli.iina/history.plist: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is empty; did you forget to send -finishEncoding to the NSKeyedArchiver?" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is empty; did you forget to send -finishEncoding to the NSKeyedArchiver?}
```

**Steps to reproduce:**
This is very difficult to reproduce. Run a stress test that opens many files at once that use software decoding such that the Mac is overloaded and cause IINA to quit. Repeat for a long time.

- [x] MPV does not have this problem.

This is an IINA feature.

**How often does this happen?**
Very rarely.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Change the call to `write` in the `HistoryController.save` method to use the `atomic` option
- Add a` tasksOutstanding` property to `HistoryController` to keep track of how many tasks are in the background queue
- Change the `HistoryController.history` property to be atomic
- Change the methods in `HistoryController`, `HistoryWindowController` and `JavascriptAPICore` to lock the `history` property when accessing it
- Add a `iinaHistoryTaskFinished` notification to `AppData`
- Change `HistoryController.add` to post this notification when a background task finishes
- Change `AppDelegate.applicationShouldTerminate` to establish an observer for the `iinaHistoryTaskFinished` notification and wait until all outstanding `HistoryController` tasks have finished before proceeding with termination
- Add logging to the `HistoryController`
- Remove unused `removeAll` method from `HistoryController`

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #5107.

---

**Description:**

### CODE REVIEW

File: iina/AppDelegate.swift [hunk 1]
```diff
@@ -573,13 +577,16 @@ class AppDelegate: NSObject, NSApplicationDelegate, SPUUpdaterDelegate {
         // All players have shutdown.
         Logger.log("All players have shutdown")
       }
-      guard !OnlineSubtitle.loggedIn else { return }
-      // All players have shutdown. No longer logged into an online subtitles provider.
+      // If still logged in to subtitle providers or still saving playback history then continue
+      // waiting.
+      guard !OnlineSubtitle.loggedIn, HistoryController.shared.tasksOutstanding == 0 else { return }
```
Comment (lhc70000) [inline iina/AppDelegate.swift]: I suggest using two separate guards.

**Review by lhc70000 — COMMENTED** [review]
Looks good to me.

I was thinking whether an `OperationQueue` will be more suitable for this case, but all other checks in `proceedWithTermination()` use the notification based mechanism. So the current implementation is fine.

File: iina/AppDelegate.swift (hunk 1 above)
Comment (low-batt) [reply iina/AppDelegate.swift]: Fixed. I initially had it as two guards as I thought that was easier to read with separate comments. I decided to combine it into one guard right before posting as a lot of the code uses guards with multiple expressions. In this case with the separate guards it is quicker to read and understand.

**Comment by low-batt** [comment]
I too considered `OperationQueue` as well as [DispatchWorkItem](https://developer.apple.com/documentation/dispatch/dispatchworkitem) but I didn't see an advantage to using them over the current event driven system.
