### PR TITLE
Rectify timeline in Touchbar freezes, #4058

### LINKED ISSUE #4051: [UI]Playback/Timebar freezes at the start while playing any audio file
**System and IINA version:**

- macOS 13
- IINA 1.3.1 Build 133

**Expected behavior:**
Playback/Timebar should display the correct played time for audio files in audio player mode. 

**Actual behavior:**
Playback/Timebar freezes at the start while playing any audio file in audio player mode, but the audio keeps playing as expected.

<br>

**Steps to reproduce:**
Just play any MP3/FLAC file in audio player mode.

- [x] MPV does not have this problem.

**How often does this happen?**
At Random

### LINKED ISSUE #4058: Timeline in Touchbar freezes
**System and IINA version:**

- macOS Ventura 13.0
- IINA 1.3.1 build 133 mpv 0.34.1

**Expected behavior:**
Video progress in Touchbar was dynamic before, timeline was updating every second.

**Actual behavior:**
Timeline in touchbar is dynamic only either when cursor is visible or overlay, but after they hide - timeline in the touchbar freezes and updates again only when I move the cursor.

<details>
<summary><b>mpv log:</b></summary>

```
[   0.004][v][cplayer] mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[   0.004][v][cplayer]  built on Sat May 28 15:57:18 UTC 2022
[   0.004][v][cplayer] FFmpeg library versions:
[   0.004][v][cplayer]    libavutil       56.70.100
[   0.004][v][cplayer]    libavcodec      58.134.100
[   0.004][v][cplayer]    libavformat     58.76.100
[   0.004][v][cplayer]    libswscale      5.9.100
[   0.004][v][cplayer]    libavfilter     7.110.100
[   0.004][v][cplayer]    libswresample   3.9.100
[   0.004][v][cplayer] FFmpeg version: 4.4.2
[   0.004][v][cplayer] 
[   0.004][v][cplayer] Configuration: waf configure --prefix=/opt/homebrew/Cellar/mpv-iina/0.34.1 --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-uchardet --enable-libbluray --disable-swift --disable-debug-build --disable-macos-media-player --confdir=/opt/homebrew/etc/mpv --datadir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/mpv-iina --mandir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/man --docdir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/doc/mpv-iina --lua=luajit
[   0.004][v][cplayer] List of enabled features: asm bsd-fstatfs build-date cocoa coreaudio cplayer cplugins ffmpeg ffmpeg-aviocontext-bytes-read gl gl-cocoa glob glob-posix gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared lua luajit macos-10-11-features macos-10-12-2-features macos-10-14-features macos-touchbar optimize osx-thread-name plain-gl posix posix-or-mingw pthreads rubberband stdatomic uchardet vector videotoolbox-gl videotoolbox-hwaccel zimg zlib
[   0.004][v][cplayer] mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[   0.004][v][cplayer]  built on Sat May 28 15:57:18 UTC 2022
[   0.004][v][cplayer] FFmpeg library versions:
[   0.004][v][cplayer]    libavutil       56.70.100
[   0.004][v][cplayer]    libavcodec      58.134.100
[   0.004][v][cplayer]    libavformat     58.76.100
[   0.004][v][cplayer]    libswscale      5.9.100
[   0.004][v][cplayer]    libavfilter     7.110.100
[   0.004][v][cplayer]    libswresample   3.9.100
[   0.004][v][cplayer] FFmpeg version: 4.4.2
[   0.004][v][cplayer] 
[   0.004][v][cplayer] Configuration: waf configure --prefix=/opt/homebrew/Cellar/mpv-iina/0.34.1 --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-uchardet --enable-libbluray --disable-swift --disable-debug-build --disable-macos-media-player --confdir=/opt/homebrew/etc/mpv --datadir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/mpv-iina --mandir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/man --docdir=/opt/homebrew/Cellar/mpv-iina/0.34.1/share/doc/mpv-iina --lua=luajit
[   0.004][v][cplayer] List of enabled features: asm bsd-fstatfs build-date cocoa coreaudio cplayer cplugins ffmpeg ffmpeg-aviocontext-bytes-read gl gl-cocoa glob glob-posix gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared lua luajit macos-10-11-features macos-10-12-2-features macos-10-14-features macos-touchbar optimize osx-thread-name plain-gl posix posix-or-mingw pthreads rubberband stdatomic uchardet vector videotoolbox-gl videotoolbox-hwaccel zimg zlib
[   0.004][d][global] config path: '' -> '-'
[   0.004][d][global] user path: '~~home/' -> ''
[   0.004][d][global] user path: '~~old_home/' -> ''
[   0.004][d][global] user path: '/Applications/IINA.app/Contents/Resources/config/iina-default-input.conf' -> '/Applications/IINA.app/Contents/Resources/config/iina-default-input.conf'
[   0.005][v][bdmv/bluray] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.005][v][file] Opening /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.005][d][file] resize stream to 131072 bytes, drop 0 bytes
[   0.005][d][file] Stream opened successfully.
[   0.005][v][input] Parsing input config file /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf
[   0.005][v][input] Input config file /Applications/IINA.app/Contents/Resources/config/iina-default-input.conf parsed: 69 binds
[   0.005][d][global] user path: '/Users/danil0110/Library/Logs/com.colliderli.iina/2022-11-09-18-17-09_V7QVIT/mpv.log' -> '/Users/danil0110/Library/Logs/com.colliderli.iina/2022-11-09-18-17-09_V7QVIT/mpv.log'
[   0.005][d][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.005][d][stats] Loading lua script @stats.lua...
[   0.005][d][console] Loading lua script @console.lua...
[   0.005][d][auto_profiles] Loading lua script @auto_profiles.lua...
[   0.005][d][osx] Exiting...
[   0.005][d][stats] loading mp.defaults
[   0.005][d][console] loading mp.defaults
[   0.005][v][cplayer] Set property: vo="libmpv" -> 1
[   0.005][d][ytdl_hook] loading mp.defaults
[   0.005][v][cplayer] Set property: keepaspect="no" -> 1
[   0.005][d][auto_profiles] loading mp.defaults
[   0.005][v][cplayer] Set property: gpu-hwdec-interop="auto" -> 1
[   0.005][d][stats] loading @stats.lua
[   0.005][d][console] loading @console.lua
[   0.005][d][ytdl_hook] loading @ytdl_hook.lua
[   0.005][d][auto_profiles] loading @auto_profiles.lua
[   0.006][d][stats] reading options for stats 
[   0.006][d][stats] script-opts/stats.conf not found. 
[   0.006][d][stats] lua-settings/stats.conf not found. 
[   0.006][d][ytdl_hook] reading options for ytdl_hook 
[   0.006][d][ytdl_hook] script-opts/ytdl_hook.conf not found. 
[   0.006][d][ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[   0.038][v][ao/coreaudio] selected audio output device: MacBook Pro Speakers (69)
[   0.038][d][console] reading options for console 
[   0.038][d][console] script-opts/console.conf not found. 
[   0.038][d][console] lua-settings/console.conf not found. 
[   0.038][d][cplayer] Run command: define-section, flags=64, args=[name="input_console", contents="", flags="default"]
[   0.038][d][cplayer] Run command: enable-section, flags=64, args=[name="input_console", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.038][d][cplayer] Run command: define-section, flags=64, args=[name="input_forced_console", contents="", flags="force"]
[   0.038][d][cplayer] Run command: enable-section, flags=64, args=[name="input_forced_console", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.038][d][auto_profiles] Exiting...
[   0.038][v][cplayer] Waiting for scripts...
[   0.039][d][osd/libass] ASS library version: 0x1502000 (runtime 0x1502000)
[   0.039][v][osd/libass] libass API version: 0x1502000
[   0.039][v][osd/libass] libass source: tarball: 0.15.2
[   0.039][v][osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 4.2.1 (COMPLEX)
[   0.039][v][osd/libass] Setting up fonts...
[   0.040][v][osd/libass] Using font provider coretext
[   0.040][v][osd/libass] Done.
[   0.040][d][cplayer] Run command: define-section, flags=64, args=[name="input_stats", contents="", flags="default"]
[   0.040][d][cplayer] Run command: enable-section, flags=64, args=[name="input_stats", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.040][d][cplayer] Run command: define-section, flags=64, args=[name="input_forced_stats", contents="", flags="force"]
[   0.040][d][cplayer] Run command: enable-section, flags=64, args=[name="input_forced_stats", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.040][v][cplayer] Done loading scripts.
[   0.239][v][libmpv_render] GL_VERSION='4.1 Metal - 83'
[   0.239][v][libmpv_render] Detected desktop OpenGL 4.1.
[   0.239][v][libmpv_render] GL_VENDOR='Apple'
[   0.239][v][libmpv_render] GL_RENDERER='Apple M1'
[   0.239][v][libmpv_render] GL_SHADING_LANGUAGE_VERSION='4.10'
[   0.239][d][libmpv_render] Combined OpenGL extensions string:
[   0.239][d][libmpv_render]  GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_NV_texture_barrier
[   0.239][v][libmpv_render] Loaded extension GL_APPLE_rgb_422.
[   0.239][v][libmpv_render] GL_*_swap_control extension missing.
[   0.240][d][libmpv_render] Texture formats:
[   0.240][d][libmpv_render]   NAME       COMP*TYPE SIZE           DEPTH PER COMP.
[   0.240][d][libmpv_render]   r8         1*unorm   1B    LF CR ST {8}
[   0.240][d][libmpv_render]   rg8        2*unorm   2B    LF CR ST {8 8}
[   0.240][d][libmpv_render]   rgb8       3*unorm   3B    LF CR ST {8 8 8}
[   0.240][d][libmpv_render]   rgba8      4*unorm   4B    LF CR ST {8 8 8 8}
[   0.240][d][libmpv_render]   r16        1*unorm   2B    LF CR ST {16}
[   0.240][d][libmpv_render]   rg16       2*unorm   4B    LF CR ST {16 16}
[   0.240][d][libmpv_render]   rgb16      3*unorm   6B    LF CR ST {16 16 16}
[   0.240][d][libmpv_render]   rgba16     4*unorm   8B    LF CR ST {16 16 16 16}
[   0.240][d][libmpv_render]   r8ui       1*uint    1B       CR ST {8}
[   0.240][d][libmpv_render]   rg8ui      2*uint    2B       CR ST {8 8}
[   0.240][d][libmpv_render]   rgb8ui     3*uint    3B          ST {8 8 8}
[   0.240][d][libmpv_render]   rgba8ui    4*uint    4B       CR ST {8 8 8 8}
[   0.240][d][libmpv_render]   r16ui      1*uint    2B       CR ST {16}
[   0.240][d][libmpv_render]   rg16ui     2*uint    4B       CR ST {16 16}
[   0.240][d][libmpv_render]   rgb16ui    3*uint    6B          ST {16 16 16}
[   0.240][d][libmpv_render]   rgba16ui   4*uint    8B       CR ST {16 16 16 16}
[   0.240][d][libmpv_render]   r16f       1*float   4B    LF CR ST {32/16}
[   0.240][d][libmpv_render]   rg16f      2*float   8B    LF CR ST {32/16 32/16}
[   0.240][d][libmpv_render]   rgb16f     3*float  12B    LF CR ST {32/16 32/16 32/16}
[   0.240][d][libmpv_render]   rgba16f    4*float  16B    LF CR ST {32/16 32/16 32/16 32/16}
[   0.240][d][libmpv_render]   r32f       1*float   4B    LF CR ST {32}
[   0.240][d][libmpv_render]   rg32f      2*float   8B    LF CR ST {32 32}
[   0.240][d][libmpv_render]   rgb32f     3*float  12B    LF CR ST {32 32 32}
[   0.240][d][libmpv_render]   rgba32f    4*float  16B    LF CR ST {32 32 32 32}
[   0.240][d][libmpv_render]   rgb10_a2   4*unorm   4B    LF CR ST {0/10 0/10 0/10 0/2}
[   0.240][d][libmpv_render]   rgba12     4*unorm   8B    LF CR ST {16/12 16/12 16/12 16/12}
[   0.240][d][libmpv_render]   rgb10      3*unorm   6B    LF CR ST {16/10 16/10 16/10}
[   0.240][d][libmpv_render]   rgb565     3*unorm   2B    LF    ST {0/8 0/8 0/8}
[   0.240][d][libmpv_render]   appleyp    0*unorm   2B    LF    ST {}
[   0.240][d][libmpv_render]  LA = LUMINANCE_ALPHA hack format
[   0.240][d][libmpv_render]  LF = linear filterable
[   0.240][d][libmpv_render]  CR = can be used for render targets
[   0.240][d][libmpv_render]  ST = can be used for storable images
[   0.240][d][libmpv_render] Image formats:
[   0.240][d][libmpv_render]   yuv444p => 3 planes 1x1 8/0 [r8/r8/r8] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv420p => 3 planes 2x2 8/0 [r8/r8/r8] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   gray => 1 planes 1x1 8/0 [r8] (r) [unorm]
[   0.240][d][libmpv_render]   gray16 => 1 planes 1x1 16/0 [r16] (r) [unorm]
[   0.240][d][libmpv_render]   uyvy422 => 1 planes 1x1 0/0 [appleyp] (brg) [unknown]
[   0.240][d][libmpv_render]   nv12 => 2 planes 2x2 8/0 [r8/rg8] (r/gb) [unorm]
[   0.240][d][libmpv_render]   p010 => 2 planes 2x2 16/6 [r16/rg16] (r/gb) [unorm]
[   0.240][d][libmpv_render]   argb => 1 planes 1x1 8/0 [rgba8] (argb) [unorm]
[   0.240][d][libmpv_render]   bgra => 1 planes 1x1 8/0 [rgba8] (bgra) [unorm]
[   0.240][d][libmpv_render]   abgr => 1 planes 1x1 8/0 [rgba8] (abgr) [unorm]
[   0.240][d][libmpv_render]   rgba => 1 planes 1x1 8/0 [rgba8] (rgba) [unorm]
[   0.240][d][libmpv_render]   bgr24 => 1 planes 1x1 8/0 [rgb8] (bgr) [unorm]
[   0.240][d][libmpv_render]   rgb24 => 1 planes 1x1 8/0 [rgb8] (rgb) [unorm]
[   0.240][d][libmpv_render]   0rgb => 1 planes 1x1 8/0 [rgba8] (_rgb) [unorm]
[   0.240][d][libmpv_render]   bgr0 => 1 planes 1x1 8/0 [rgba8] (bgr) [unorm]
[   0.240][d][libmpv_render]   0bgr => 1 planes 1x1 8/0 [rgba8] (_bgr) [unorm]
[   0.240][d][libmpv_render]   rgb0 => 1 planes 1x1 8/0 [rgba8] (rgb) [unorm]
[   0.240][d][libmpv_render]   rgba64 => 1 planes 1x1 16/0 [rgba16] (rgba) [unorm]
[   0.240][d][libmpv_render]   rgb565 => 1 planes 1x1 0/0 [rgb565] (rgb) [unknown]
[   0.240][d][libmpv_render]   pal8
[   0.240][d][libmpv_render]   vdpau
[   0.240][d][libmpv_render]   d3d11
[   0.240][d][libmpv_render]   dxva2_vld
[   0.240][d][libmpv_render]   mmal
[   0.240][d][libmpv_render]   mediacodec
[   0.240][d][libmpv_render]   drm_prime
[   0.240][d][libmpv_render]   cuda
[   0.240][d][libmpv_render]   yap8 => 2 planes 1x1 8/0 [r8/r8] (r/a) [unorm]
[   0.240][d][libmpv_render]   yap16 => 2 planes 1x1 16/0 [r16/r16] (r/a) [unorm]
[   0.240][d][libmpv_render]   grayaf32 => 2 planes 1x1 32/0 [r16f/r16f] (r/a) [float]
[   0.240][d][libmpv_render]   yuv444pf => 3 planes 1x1 32/0 [r16f/r16f/r16f] (r/g/b) [float]
[   0.240][d][libmpv_render]   yuva444pf => 4 planes 1x1 32/0 [r16f/r16f/r16f/r16f] (r/g/b/a) [float]
[   0.240][d][libmpv_render]   yuv420pf => 3 planes 2x2 32/0 [r16f/r16f/r16f] (r/g/b) [float]
[   0.240][d][libmpv_render]   yuva420pf => 4 planes 2x2 32/0 [r16f/r16f/r16f/r16f] (r/g/b/a) [float]
[   0.240][d][libmpv_render]   yuv422pf => 3 planes 2x1 32/0 [r16f/r16f/r16f] (r/g/b) [float]
[   0.240][d][libmpv_render]   yuva422pf => 4 planes 2x1 32/0 [r16f/r16f/r16f/r16f] (r/g/b/a) [float]
[   0.240][d][libmpv_render]   yuv440pf => 3 planes 1x2 32/0 [r16f/r16f/r16f] (r/g/b) [float]
[   0.240][d][libmpv_render]   yuva440pf => 4 planes 1x2 32/0 [r16f/r16f/r16f/r16f] (r/g/b/a) [float]
[   0.240][d][libmpv_render]   yuv410pf => 3 planes 4x4 32/0 [r16f/r16f/r16f] (r/g/b) [float]
[   0.240][d][libmpv_render]   yuva410pf => 4 planes 4x4 32/0 [r16f/r16f/r16f/r16f] (r/g/b/a) [float]
[   0.240][d][libmpv_render]   yuv411pf => 3 planes 4x1 32/0 [r16f/r16f/r16f] (r/g/b) [float]
[   0.240][d][libmpv_render]   yuva411pf => 4 planes 4x1 32/0 [r16f/r16f/r16f/r16f] (r/g/b/a) [float]
[   0.240][d][libmpv_render]   rgb30 => 1 planes 1x1 10/0 [rgb10_a2] (bgr) [unknown]
[   0.240][d][libmpv_render]   y1 => 1 planes 1x1 8/-7 [r8] (r) [unorm]
[   0.240][d][libmpv_render]   gbrp1 => 3 planes 1x1 8/-7 [r8/r8/r8] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   gbrp2 => 3 planes 1x1 8/-6 [r8/r8/r8] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   gbrp3 => 3 planes 1x1 8/-5 [r8/r8/r8] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   gbrp4 => 3 planes 1x1 8/-4 [r8/r8/r8] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   gbrp5 => 3 planes 1x1 8/-3 [r8/r8/r8] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   gbrp6 => 3 planes 1x1 8/-2 [r8/r8/r8] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   vdpau_output
[   0.240][d][libmpv_render]   vaapi
[   0.240][d][libmpv_render]   videotoolbox
[   0.240][d][libmpv_render]   yuyv422
[   0.240][d][libmpv_render]   yuv422p => 3 planes 2x1 8/0 [r8/r8/r8] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv410p => 3 planes 4x4 8/0 [r8/r8/r8] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv411p => 3 planes 4x1 8/0 [r8/r8/r8] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   monow
[   0.240][d][libmpv_render]   monob
[   0.240][d][libmpv_render]   yuvj422p => 3 planes 2x1 8/0 [r8/r8/r8] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   uyyvyy411
[   0.240][d][libmpv_render]   bgr8
[   0.240][d][libmpv_render]   bgr4
[   0.240][d][libmpv_render]   bgr4_byte
[   0.240][d][libmpv_render]   rgb8
[   0.240][d][libmpv_render]   rgb4
[   0.240][d][libmpv_render]   rgb4_byte
[   0.240][d][libmpv_render]   nv21 => 2 planes 2x2 8/0 [r8/rg8] (r/bg) [unorm]
[   0.240][d][libmpv_render]   gray16be
[   0.240][d][libmpv_render]   yuv440p => 3 planes 1x2 8/0 [r8/r8/r8] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuvj440p => 3 planes 1x2 8/0 [r8/r8/r8] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuva420p => 4 planes 2x2 8/0 [r8/r8/r8/r8] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   rgb48be
[   0.240][d][libmpv_render]   rgb48 => 1 planes 1x1 16/0 [rgb16] (rgb) [unorm]
[   0.240][d][libmpv_render]   rgb565be
[   0.240][d][libmpv_render]   rgb555be
[   0.240][d][libmpv_render]   rgb555
[   0.240][d][libmpv_render]   bgr565be
[   0.240][d][libmpv_render]   bgr565
[   0.240][d][libmpv_render]   bgr555be
[   0.240][d][libmpv_render]   bgr555
[   0.240][d][libmpv_render]   vaapi_moco
[   0.240][d][libmpv_render]   vaapi_idct
[   0.240][d][libmpv_render]   yuv420p16 => 3 planes 2x2 16/0 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv420p16be
[   0.240][d][libmpv_render]   yuv422p16 => 3 planes 2x1 16/0 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv422p16be
[   0.240][d][libmpv_render]   yuv444p16 => 3 planes 1x1 16/0 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv444p16be
[   0.240][d][libmpv_render]   rgb444
[   0.240][d][libmpv_render]   rgb444be
[   0.240][d][libmpv_render]   bgr444
[   0.240][d][libmpv_render]   bgr444be
[   0.240][d][libmpv_render]   ya8 => 1 planes 1x1 8/0 [rg8] (ra) [unorm]
[   0.240][d][libmpv_render]   bgr48be
[   0.240][d][libmpv_render]   bgr48 => 1 planes 1x1 16/0 [rgb16] (bgr) [unorm]
[   0.240][d][libmpv_render]   yuv420p9be
[   0.240][d][libmpv_render]   yuv420p9 => 3 planes 2x2 16/-7 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv420p10be
[   0.240][d][libmpv_render]   yuv420p10 => 3 planes 2x2 16/-6 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv422p10be
[   0.240][d][libmpv_render]   yuv422p10 => 3 planes 2x1 16/-6 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv444p9be
[   0.240][d][libmpv_render]   yuv444p9 => 3 planes 1x1 16/-7 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv444p10be
[   0.240][d][libmpv_render]   yuv444p10 => 3 planes 1x1 16/-6 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv422p9be
[   0.240][d][libmpv_render]   yuv422p9 => 3 planes 2x1 16/-7 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   gbrp => 3 planes 1x1 8/0 [r8/r8/r8] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   gbrp9be
[   0.240][d][libmpv_render]   gbrp9 => 3 planes 1x1 16/-7 [r16/r16/r16] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   gbrp10be
[   0.240][d][libmpv_render]   gbrp10 => 3 planes 1x1 16/-6 [r16/r16/r16] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   gbrp16be
[   0.240][d][libmpv_render]   gbrp16 => 3 planes 1x1 16/0 [r16/r16/r16] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   yuva422p => 4 planes 2x1 8/0 [r8/r8/r8/r8] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva444p => 4 planes 1x1 8/0 [r8/r8/r8/r8] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva420p9be
[   0.240][d][libmpv_render]   yuva420p9 => 4 planes 2x2 16/-7 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva422p9be
[   0.240][d][libmpv_render]   yuva422p9 => 4 planes 2x1 16/-7 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva444p9be
[   0.240][d][libmpv_render]   yuva444p9 => 4 planes 1x1 16/-7 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva420p10be
[   0.240][d][libmpv_render]   yuva420p10 => 4 planes 2x2 16/-6 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva422p10be
[   0.240][d][libmpv_render]   yuva422p10 => 4 planes 2x1 16/-6 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva444p10be
[   0.240][d][libmpv_render]   yuva444p10 => 4 planes 1x1 16/-6 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva420p16be
[   0.240][d][libmpv_render]   yuva420p16 => 4 planes 2x2 16/0 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva422p16be
[   0.240][d][libmpv_render]   yuva422p16 => 4 planes 2x1 16/0 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva444p16be
[   0.240][d][libmpv_render]   yuva444p16 => 4 planes 1x1 16/0 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   xyz12 => 1 planes 1x1 16/4 [rgb16] (rgb) [unorm]
[   0.240][d][libmpv_render]   xyz12be
[   0.240][d][libmpv_render]   nv16 => 2 planes 2x1 8/0 [r8/rg8] (r/gb) [unorm]
[   0.240][d][libmpv_render]   nv20 => 2 planes 2x1 16/-6 [r16/rg16] (r/gb) [unorm]
[   0.240][d][libmpv_render]   nv20be
[   0.240][d][libmpv_render]   rgba64be
[   0.240][d][libmpv_render]   bgra64be
[   0.240][d][libmpv_render]   bgra64 => 1 planes 1x1 16/0 [rgba16] (bgra) [unorm]
[   0.240][d][libmpv_render]   yvyu422
[   0.240][d][libmpv_render]   ya16be
[   0.240][d][libmpv_render]   ya16 => 1 planes 1x1 16/0 [rg16] (ra) [unorm]
[   0.240][d][libmpv_render]   gbrap => 4 planes 1x1 8/0 [r8/r8/r8/r8] (g/b/r/a) [unorm]
[   0.240][d][libmpv_render]   gbrap16be
[   0.240][d][libmpv_render]   gbrap16 => 4 planes 1x1 16/0 [r16/r16/r16/r16] (g/b/r/a) [unorm]
[   0.240][d][libmpv_render]   qsv
[   0.240][d][libmpv_render]   d3d11va_vld
[   0.240][d][libmpv_render]   yuv420p12be
[   0.240][d][libmpv_render]   yuv420p12 => 3 planes 2x2 16/-4 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv420p14be
[   0.240][d][libmpv_render]   yuv420p14 => 3 planes 2x2 16/-2 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv422p12be
[   0.240][d][libmpv_render]   yuv422p12 => 3 planes 2x1 16/-4 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv422p14be
[   0.240][d][libmpv_render]   yuv422p14 => 3 planes 2x1 16/-2 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv444p12be
[   0.240][d][libmpv_render]   yuv444p12 => 3 planes 1x1 16/-4 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv444p14be
[   0.240][d][libmpv_render]   yuv444p14 => 3 planes 1x1 16/-2 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   gbrp12be
[   0.240][d][libmpv_render]   gbrp12 => 3 planes 1x1 16/-4 [r16/r16/r16] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   gbrp14be
[   0.240][d][libmpv_render]   gbrp14 => 3 planes 1x1 16/-2 [r16/r16/r16] (g/b/r) [unorm]
[   0.240][d][libmpv_render]   yuvj411p => 3 planes 4x1 8/0 [r8/r8/r8] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   bayer_bggr8
[   0.240][d][libmpv_render]   bayer_rggb8
[   0.240][d][libmpv_render]   bayer_gbrg8
[   0.240][d][libmpv_render]   bayer_grbg8
[   0.240][d][libmpv_render]   bayer_bggr16
[   0.240][d][libmpv_render]   bayer_bggr16be
[   0.240][d][libmpv_render]   bayer_rggb16
[   0.240][d][libmpv_render]   bayer_rggb16be
[   0.240][d][libmpv_render]   bayer_gbrg16
[   0.240][d][libmpv_render]   bayer_gbrg16be
[   0.240][d][libmpv_render]   bayer_grbg16
[   0.240][d][libmpv_render]   bayer_grbg16be
[   0.240][d][libmpv_render]   xvmc
[   0.240][d][libmpv_render]   yuv440p10 => 3 planes 1x2 16/-6 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv440p10be
[   0.240][d][libmpv_render]   yuv440p12 => 3 planes 1x2 16/-4 [r16/r16/r16] (r/g/b) [unorm]
[   0.240][d][libmpv_render]   yuv440p12be
[   0.240][d][libmpv_render]   ayuv64 => 1 planes 1x1 16/0 [rgba16] (argb) [unorm]
[   0.240][d][libmpv_render]   ayuv64be
[   0.240][d][libmpv_render]   p010be
[   0.240][d][libmpv_render]   gbrap12be
[   0.240][d][libmpv_render]   gbrap12 => 4 planes 1x1 16/-4 [r16/r16/r16/r16] (g/b/r/a) [unorm]
[   0.240][d][libmpv_render]   gbrap10be
[   0.240][d][libmpv_render]   gbrap10 => 4 planes 1x1 16/-6 [r16/r16/r16/r16] (g/b/r/a) [unorm]
[   0.240][d][libmpv_render]   gray12be
[   0.240][d][libmpv_render]   gray12 => 1 planes 1x1 16/-4 [r16] (r) [unorm]
[   0.240][d][libmpv_render]   gray10be
[   0.240][d][libmpv_render]   gray10 => 1 planes 1x1 16/-6 [r16] (r) [unorm]
[   0.240][d][libmpv_render]   p016 => 2 planes 2x2 16/0 [r16/rg16] (r/gb) [unorm]
[   0.240][d][libmpv_render]   p016be
[   0.240][d][libmpv_render]   gray9be
[   0.240][d][libmpv_render]   gray9 => 1 planes 1x1 16/-7 [r16] (r) [unorm]
[   0.240][d][libmpv_render]   gbrpf32be
[   0.240][d][libmpv_render]   gbrpf32 => 3 planes 1x1 32/0 [r16f/r16f/r16f] (g/b/r) [float]
[   0.240][d][libmpv_render]   gbrapf32be
[   0.240][d][libmpv_render]   gbrapf32 => 4 planes 1x1 32/0 [r16f/r16f/r16f/r16f] (g/b/r/a) [float]
[   0.240][d][libmpv_render]   opencl
[   0.240][d][libmpv_render]   gray14be
[   0.240][d][libmpv_render]   gray14 => 1 planes 1x1 16/-2 [r16] (r) [unorm]
[   0.240][d][libmpv_render]   grayf32be
[   0.240][d][libmpv_render]   grayf32 => 1 planes 1x1 32/0 [r16f] (r) [float]
[   0.240][d][libmpv_render]   yuva422p12be
[   0.240][d][libmpv_render]   yuva422p12 => 4 planes 2x1 16/-4 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   yuva444p12be
[   0.240][d][libmpv_render]   yuva444p12 => 4 planes 1x1 16/-4 [r16/r16/r16/r16] (r/g/b/a) [unorm]
[   0.240][d][libmpv_render]   nv24 => 2 planes 1x1 8/0 [r8/rg8] (r/gb) [unorm]
[   0.240][d][libmpv_render]   nv42 => 2 planes 1x1 8/0 [r8/rg8] (r/bg) [unorm]
[   0.240][d][libmpv_render]   vulkan
[   0.240][d][libmpv_render]   y210be
[   0.240][d][libmpv_render]   y210
[   0.240][d][libmpv_render]   x2rgb10be
[   0.240][v][libmpv_render] Testing FBO format rgba16f
[   0.240][d][libmpv_render] Resizing texture: 16x16
[   0.240][v][libmpv_render] Using FBO format rgba16f.
[   0.240][v][libmpv_render] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).
[   0.240][v][libmpv_render] No advanced processing required. Enabling dumb mode.
[   0.240][v][libmpv_render] Loading hwdec driver 'videotoolbox'
[   0.241][v][cplayer] Set property: override-display-fps=60.002400 -> 1
[   0.326][d][cplayer] Run command: loadfile, flags=64, args=[url="/Users/danil0110/Movies/[FreeCourseSite.com] Udemy - NestJS The Complete Developer's Guide/01 Get Started Here!/001 How to Get Help.mp4", flags="replace", options=""]
[   0.326][d][global] user path: '/Users/danil0110/Library/Application Support/com.colliderli.iina/watch_later' -> '/Users/danil0110/Library/Application Support/com.colliderli.iina/watch_later'
[   0.326][i][cplayer] Resuming playback. This behavior can be disabled with --no-resume-playback.
[   0.326][v][cplayer] Loading config '/Users/danil0110/Library/Application Support/com.colliderli.iina/watch_later/F9D164FB4C446CD41B860D2A114913D4'
[   0.326][v][cplayer] Reading config file /Users/danil0110/Library/Application Support/com.colliderli.iina/watch_later/F9D164FB4C446CD41B860D2A114913D4
[   0.326][v][cplayer] Applying profile 'default'...
[   0.326][v][cplayer] Setting option 'start' = '19.000000' (flags = 36)
[   0.326][v][cplayer] Setting option 'pause' = 'yes' (flags = 36)
[   0.326][v][cplayer] Setting option 'sid' = '1' (flags = 36)
[   0.326][v][cplayer] Running hook: ytdl_hook/on_load
[   0.326][v][ytdl_hook] ytdl:// hook 
[   0.327][v][ytdl_hook] not a ytdl:// url 
[   0.327][v][bdmv/bluray] Opening /Users/danil0110/Movies/[FreeCourseSite.com] Udemy - NestJS The Complete Developer's Guide/01 Get Started Here!/001 How to Get Help.mp4
[   0.327][v][file] Opening /Users/danil0110/Movies/[FreeCourseSite.com] Udemy - NestJS The Complete Developer's Guide/01 Get Started Here!/001 How to Get Help.mp4
[   0.327][d][file] resize stream to 131072 bytes, drop 0 bytes
[   0.327][d][file] Stream opened successfully.
[   0.327][v][demux] Trying demuxers for level=normal.
[   0.327][d][demux] Trying demuxer: disc (force-level: normal)
[   0.327][d][demux] Trying demuxer: edl (force-level: normal)
[   0.327][d][demux] Trying demuxer: cue (force-level: normal)
[   0.327][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.327][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.327][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.327][d][demux] Trying demuxer: libarchive (force-level: normal)
[   0.327][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.328][v][lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[   0.329][v][demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[   0.329][v][cplayer] Opening done: /Users/danil0110/Movies/[FreeCourseSite.com] Udemy - NestJS The Complete Developer's Guide/01 Get Started Here!/001 How to Get Help.mp4
[   0.329][v][find_files] Loading external files in /Users/danil0110/Movies/[FreeCourseSite.com] Udemy - NestJS The Complete Developer's Guide/01 Get Started Here!/
[   0.329][v][cplayer] Running hook: ytdl_hook/on_preloaded
[   0.329][v][lavf] select track 0
[   0.329][v][lavf] select track 1
[   0.329][i][cplayer]  (+) Video --vid=1 (*) (h264 1280x720 30.000fps)
[   0.329][i][cplayer]  (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[   0.329][v][vo/libmpv] Assuming 60.002400 FPS for display sync.
[   0.329][v][vd] Container reported FPS: 30.000000
[   0.329][v][vd] Codec list:
[   0.329][v][vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[   0.329][v][vd] Opening decoder h264
[   0.329][v][vd] Looking at hwdec h264-videotoolbox...
[   0.329][v][vd] Trying hardware decoding via h264-videotoolbox.
[   0.329][v][vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[   0.329][v][vf] User filter list:
[   0.329][v][vf]   (empty)
[   0.329][v][ad] Codec list:
[   0.329][v][ad]     aac - AAC (Advanced Audio Coding)
[   0.329][v][ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[   0.329][v][ad]     aac_at (aac) - aac (AudioToolbox)
[   0.329][v][ad] Opening decoder aac
[   0.329][v][ad] Detected 8 logical cores.
[   0.329][v][ad] Requesting 9 threads for decoding.
[   0.330][v][ad] Selected codec: aac (AAC (Advanced Audio Coding))
[   0.330][v][af] User filter list:
[   0.330][v][af]   (empty)
[   0.330][v][cplayer] Starting playback...
[   0.330][v][lavf] queuing seek to 19.000000
[   0.330][v][lavf] execute seek (to 19.000000 flags 32)
[   0.330][v][lavf] seek done
[   0.330][v][cplayer] hr-seek, skipping to 19.000000
[   0.330][v][file] stream level seek from 131072 to 1169566
[   0.330][d][cplayer] Run command: sub-add, flags=64, args=[url="/Users/danil0110/Movies/[FreeCourseSite.com] Udemy - NestJS The Complete Developer's Guide/01 Get Started Here!/001 How to Get Help.en.srt", flags="select", title="", lang=""]
[   0.330][v][bdmv/bluray] Opening /Users/danil0110/Movies/[FreeCourseSite.com] Udemy - NestJS The Complete Developer's Guide/01 Get Started Here!/001 How to Get Help.en.srt
[   0.330][v][file] Opening /Users/danil0110/Movies/[FreeCourseSite.com] Udemy - NestJS The Complete Developer's Guide/01 Get Started Here!/001 How to Get Help.en.srt
[   0.330][v][vd] Pixel formats supported by decoder: videotoolbox_vld yuv420p
[   0.330][v][vd] Codec profile: Main (0x4d)
[   0.330][v][vd] Requesting pixfmt 'videotoolbox_vld' from decoder.
[   0.330][d][file] resize stream to 131072 bytes, drop 0 bytes
[   0.330][d][file] Stream opened successfully.
[   0.330][v][demux] Trying demuxers for level=normal.
[   0.330][d][demux] Trying demuxer: disc (force-level: normal)
[   0.330][d][demux] Trying demuxer: edl (force-level: normal)
[   0.330][d][demux] Trying demuxer: cue (force-level: normal)
[   0.330][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.330][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.330][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.330][d][demux] Trying demuxer: libarchive (force-level: normal)
[   0.330][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.331][v][lavf] Found 'srt' at score=100 size=1833.
[   0.331][v][lavf] Data looks like UTF-8, ignoring user-provided charset.
[   0.331][v][lavf] avformat_find_stream_info() finished after 1833 bytes.
[   0.331][v][lavf] demuxer read all data; closing stream
[   0.331][v][demux] Detected file format: srt (libavformat)
[   0.380][d][ffmpeg/video] h264: Reinit context to 1280x720, pix_fmt: videotoolbox_vld
[   0.389][i][vd] Using hardware decoding (videotoolbox).
[   0.389][v][vd] Decoder format: 1280x720 [9:10] videotoolbox[nv12] auto/auto/auto/auto/auto CL=mpeg2/4/h264
[   0.389][v][vd] Using container aspect ratio.
[   0.389][v][vf] [in] 1280x720 [9:10] videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[   0.389][v][vf] [userdeint] 1280x720 [9:10] videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[   0.389][v][vf] [userdeint] (disabled)
[   0.389][v][vf] [autorotate] 1280x720 [9:10] videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[   0.389][v][vf] [autorotate] (disabled)
[   0.389][v][vf] [convert] 1280x720 [9:10] videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[   0.389][v][vf] [convert] (disabled)
[   0.389][v][vf] [out] 1280x720 [9:10] videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[   0.390][v][af] [in] 48000Hz stereo 2ch floatp
[   0.390][v][af] [userspeed] 48000Hz stereo 2ch floatp
[   0.390][v][af] [userspeed] (disabled)
[   0.390][v][af] [convert] 48000Hz stereo 2ch floatp
[   0.390][v][lavf] select track 0
[   0.390][d][sub/ass] ASS library version: 0x1502000 (runtime 0x1502000)
[   0.390][v][sub/ass] libass API version: 0x1502000
[   0.390][v][sub/ass] libass source: tarball: 0.15.2
[   0.390][v][sub/ass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 4.2.1 (COMPLEX)
[   0.390][v][sub/ass] Setting up fonts...
[   0.390][v][sub/ass] Using font provider coretext
[   0.390][v][sub/ass] Done.
[   0.390][i][cplayer] Track added:
[   0.390][i][cplayer]  (+) Video --vid=1 (*) (h264 1280x720 30.000fps)
[   0.390][i][cplayer]  (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[   0.390][i][cplayer]  (+) Subs  --sid=1 '001 How to Get Help.en.srt' (subrip) (external)
[   0.390][v][cplayer] Set property: sid=1 -> 1
[   0.390][v][ao] Trying audio driver 'coreaudio'
[   0.390][v][ao/coreaudio] requested format: 48000 Hz, stereo channels, floatp
[   0.391][v][ao/coreaudio] selected audio output device: MacBook Pro Speakers (69)
[   0.391][v][ao/coreaudio] input channel layout:
[   0.391][v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[   0.391][v][ao/coreaudio]  - description 0: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   0.391][v][ao/coreaudio]  - description 1: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   0.391][v][ao/coreaudio] mp chmap: unknown2
[   0.391][v][ao/coreaudio] input channel layout:
[   0.391][v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[   0.391][v][ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   0.391][v][ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   0.391][v][ao/coreaudio] mp chmap: stereo
[   0.391][v][ao/coreaudio] Channel layouts:
[   0.391][v][ao/coreaudio]  - stereo
[   0.391][v][ao/coreaudio]  - mono
[   0.391][v][ao/coreaudio] result: stereo
[   0.400][v][ao/coreaudio] Latency property cntl: 66 frames
[   0.400][v][ao/coreaudio] Latency property zisf: 512 frames
[   0.400][v][ao/coreaudio] Latency property tfas: 113 frames
[   0.400][v][ao/coreaudio] audiounit latency [us]: 0
[   0.400][v][ao/coreaudio] device latency [us]: 14395
[   0.400][v][ao/coreaudio] using soft-buffer of 9600 samples.
[   0.400][i][cplayer] AO: [coreaudio] 48000Hz stereo 2ch floatp
[   0.400][v][cplayer] AO: Description: CoreAudio AudioUnit
[   0.400][v][af] [convert] (disabled)
[   0.400][v][af] [out] 48000Hz stereo 2ch floatp
[   0.402][v][cplayer] Set property: pause=true -> 1
[   0.427][v][cplayer] Set property: pause=false -> 1
[   0.434][i][cplayer] VO: [libmpv] 1280x720 => 1280x800 videotoolbox[nv12]
[   0.434][v][cplayer] VO: Description: render API for libmpv
[   0.434][v][vo/libmpv] reconfig to 1280x720 [9:10] videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[   0.434][v][lavf] queuing seek to 0.000000
[   0.434][v][lavf] execute seek (to 0.000000 flags 0)
[   0.434][v][lavf] seek done
[   0.434][v][lavf] EOF reached.
[   0.434][v][libmpv_render] Window size: 1280x720 (Borders: l=0 t=0 r=0 b=0)
[   0.434][v][libmpv_render] Video source: 1280x720 (9:10)
[   0.434][v][libmpv_render] Video display: (0, 0) 1280x720 -> (0, 0) 1280x720
[   0.434][v][libmpv_render] Video scale: 1.000000/1.000000
[   0.434][v][libmpv_render] OSD borders: l=0 t=0 r=0 b=0
[   0.434][v][libmpv_render] Video borders: l=0 t=0 r=0 b=0
[   0.434][v][libmpv_render] Testing FBO format rgba16f
[   0.434][d][libmpv_render] Resizing texture: 16x16
[   0.435][v][libmpv_render] Using FBO format rgba16f.
[   0.435][v][libmpv_render] No advanced processing required. Enabling dumb mode.
[   0.435][v][cplayer] first video frame after restart shown
[   0.435][d][libmpv_render] vertex shader source:
[   0.435][d][libmpv_render] [  1] #version 410
[   0.435][d][libmpv_render] [  2] #define tex1D texture
[   0.435][d][libmpv_render] [  3] #define tex3D texture
[   0.435][d][libmpv_render] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[   0.435][d][libmpv_render] [  5] in vec2 vertex_position;
[   0.435][d][libmpv_render] [  6] in vec2 vertex_texcoord0;
[   0.435][d][libmpv_render] [  7] out vec2 texcoord0;
[   0.435][d][libmpv_render] [  8] in vec2 vertex_texcoord1;
[   0.435][d][libmpv_render] [  9] out vec2 texcoord1;
[   0.435][d][libmpv_render] [ 10] void main() {
[   0.435][d][libmpv_render] [ 11] gl_Position = vec4(vertex_position, 1.0, 1.0);
[   0.435][d][libmpv_render] [ 12] texcoord0 = vertex_texcoord0;
[   0.435][d][libmpv_render] [ 13] texcoord1 = vertex_texcoord1;
[   0.435][d][libmpv_render] [ 14] }
[   0.436][d][libmpv_render] fragment shader source:
[   0.436][d][libmpv_render] [  1] #version 410
[   0.436][d][libmpv_render] [  2] #define tex1D texture
[   0.436][d][libmpv_render] [  3] #define tex3D texture
[   0.436][d][libmpv_render] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[   0.436][d][libmpv_render] [  5] out vec4 out_color;
[   0.436][d][libmpv_render] [  6] in vec2 texcoord0;
[   0.436][d][libmpv_render] [  7] in vec2 texcoord1;
[   0.436][d][libmpv_render] [  8] uniform mat3 colormatrix;
[   0.436][d][libmpv_render] [  9] uniform vec3 colormatrix_c;
[   0.436][d][libmpv_render] [ 10] uniform vec3 src_luma;
[   0.436][d][libmpv_render] [ 11] uniform vec3 dst_luma;
[   0.436][d][libmpv_render] [ 12] uniform sampler2DRect texture0;
[   0.436][d][libmpv_render] [ 13] uniform vec2 texture_size0;
[   0.436][d][libmpv_render] [ 14] uniform mat2 texture_rot0;
[   0.436][d][libmpv_render] [ 15] uniform vec2 texture_off0;
[   0.436][d][libmpv_render] [ 16] uniform vec2 pixel_size0;
[   0.436][d][libmpv_render] [ 17] uniform sampler2DRect texture1;
[   0.436][d][libmpv_render] [ 18] uniform vec2 texture_size1;
[   0.436][d][libmpv_render] [ 19] uniform mat2 texture_rot1;
[   0.436][d][libmpv_render] [ 20] uniform vec2 texture_off1;
[   0.436][d][libmpv_render] [ 21] uniform vec2 pixel_size1;
[   0.436][d][libmpv_render] [ 22] void main() {
[   0.436][d][libmpv_render] [ 23] vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
[   0.436][d][libmpv_render] [ 24] color.r = 1.000000 * vec4(texture(texture0, texcoord0)).r;
[   0.436][d][libmpv_render] [ 25] color.gb = 1.000000 * vec4(texture(texture1, texcoord1)).rg;
[   0.436][d][libmpv_render] [ 26] color = color.rgbr;
[   0.436][d][libmpv_render] [ 27] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[   0.436][d][libmpv_render] [ 28] color.a = 1.0;
[   0.436][d][libmpv_render] [ 29] // color mapping
[   0.436][d][libmpv_render] [ 30] color.rgb *= vec3(1.000000);
[   0.436][d][libmpv_render] [ 31] color.rgb *= vec3(1.000000);
[   0.436][d][libmpv_render] [ 32] out_color = color;
[   0.436][d][libmpv_render] [ 33] }
[   0.436][v][cplayer] audio ready
[   0.436][d][cplayer] starting video playback
[   0.436][v][cplayer] starting audio playback
[   0.436][d][libmpv_render] shader link log (status=1): 
[   0.491][v][cplayer] playback restart complete @ 19.000000, audio=playing, video=playing
[   0.493][v][libmpv_render] Window size: 1280x772 (Borders: l=0 t=0 r=0 b=0)
[   0.493][v][libmpv_render] Video source: 1280x720 (9:10)
[   0.493][v][libmpv_render] Video display: (0, 0) 1280x720 -> (0, 0) 1280x772
[   0.493][v][libmpv_render] Video scale: 1.000000/1.072222
[   0.493][v][libmpv_render] OSD borders: l=0 t=0 r=0 b=0
[   0.493][v][libmpv_render] Video borders: l=0 t=0 r=0 b=0
[   0.529][v][cplayer] Set property: window-scale=0.500000 -> 1
[   0.529][v][cplayer] Set property: window-scale=0.500000 -> 1
[   0.531][v][libmpv_render] Window size: 1280x800 (Borders: l=0 t=0 r=0 b=0)
[   0.531][v][libmpv_render] Video source: 1280x720 (9:10)
[   0.531][v][libmpv_render] Video display: (0, 0) 1280x720 -> (0, 0) 1280x800
[   0.531][v][libmpv_render] Video scale: 1.000000/1.111111
[   0.531][v][libmpv_render] OSD borders: l=0 t=0 r=0 b=0
[   0.531][v][libmpv_render] Video borders: l=0 t=0 r=0 b=0
[   0.540][v][cplayer] Set property: icc-profile="/Library/ColorSync/Profiles/Displays/Color LCD-37D8832A-2D66-02CA-B9F7-8F30A301B230.icc" -> 1
[   0.540][v][cplayer] Set property: icc-profile="/Library/ColorSync/Profiles/Displays/Color LCD-37D8832A-2D66-02CA-B9F7-8F30A301B230.icc" -> 1
[   0.543][d][global] user path: '/Library/ColorSync/Profiles/Displays/Color LCD-37D8832A-2D66-02CA-B9F7-8F30A301B230.icc' -> '/Library/ColorSync/Profiles/Displays/Color LCD-37D8832A-2D66-02CA-B9F7-8F30A301B230.icc'
[   0.543][v][libmpv_render] Opening ICC profile '/Library/ColorSync/Profiles/Displays/Color LCD-37D8832A-2D66-02CA-B9F7-8F30A301B230.icc'
[   0.543][v][libmpv_render] Testing FBO format rgba16f
[   0.544][d][libmpv_render] Resizing texture: 16x16
[   0.544][v][libmpv_render] Using FBO format rgba16f.
[   0.544][v][libmpv_render] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).
[   0.544][v][libmpv_render] No advanced processing required. Enabling dumb mode.
[   0.544][v][libmpv_render] Detected ICC profile contrast: inf
[   0.565][d][libmpv_render] vertex shader source:
[   0.565][d][libmpv_render] [  1] #version 410
[   0.565][d][libmpv_render] [  2] #define tex1D texture
[   0.565][d][libmpv_render] [  3] #define tex3D texture
[   0.565][d][libmpv_render] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[   0.565][d][libmpv_render] [  5] in vec2 vertex_position;
[   0.565][d][libmpv_render] [  6] in vec2 vertex_texcoord0;
[   0.565][d][libmpv_render] [  7] out vec2 texcoord0;
[   0.565][d][libmpv_render] [  8] in vec2 vertex_texcoord1;
[   0.565][d][libmpv_render] [  9] out vec2 texcoord1;
[   0.565][d][libmpv_render] [ 10] void main() {
[   0.565][d][libmpv_render] [ 11] gl_Position = vec4(vertex_position, 1.0, 1.0);
[   0.565][d][libmpv_render] [ 12] texcoord0 = vertex_texcoord0;
[   0.565][d][libmpv_render] [ 13] texcoord1 = vertex_texcoord1;
[   0.565][d][libmpv_render] [ 14] }
[   0.565][d][libmpv_render] fragment shader source:
[   0.565][d][libmpv_render] [  1] #version 410
[   0.565][d][libmpv_render] [  2] #define tex1D texture
[   0.565][d][libmpv_render] [  3] #define tex3D texture
[   0.565][d][libmpv_render] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[   0.565][d][libmpv_render] [  5] out vec4 out_color;
[   0.565][d][libmpv_render] [  6] in vec2 texcoord0;
[   0.565][d][libmpv_render] [  7] in vec2 texcoord1;
[   0.565][d][libmpv_render] [  8] uniform mat3 colormatrix;
[   0.565][d][libmpv_render] [  9] uniform vec3 colormatrix_c;
[   0.565][d][libmpv_render] [ 10] uniform vec3 src_luma;
[   0.565][d][libmpv_render] [ 11] uniform vec3 dst_luma;
[   0.565][d][libmpv_render] [ 12] uniform sampler3D lut_3d;
[   0.565][d][libmpv_render] [ 13] uniform sampler2DRect texture0;
[   0.565][d][libmpv_render] [ 14] uniform vec2 texture_size0;
[   0.565][d][libmpv_render] [ 15] uniform mat2 texture_rot0;
[   0.565][d][libmpv_render] [ 16] uniform vec2 texture_off0;
[   0.565][d][libmpv_render] [ 17] uniform vec2 pixel_size0;
[   0.565][d][libmpv_render] [ 18] uniform sampler2DRect texture1;
[   0.565][d][libmpv_render] [ 19] uniform vec2 texture_size1;
[   0.565][d][libmpv_render] [ 20] uniform mat2 texture_rot1;
[   0.565][d][libmpv_render] [ 21] uniform vec2 texture_off1;
[   0.565][d][libmpv_render] [ 22] uniform vec2 pixel_size1;
[   0.565][d][libmpv_render] [ 23] void main() {
[   0.565][d][libmpv_render] [ 24] vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
[   0.565][d][libmpv_render] [ 25] color.r = 1.000000 * vec4(texture(texture0, texcoord0)).r;
[   0.565][d][libmpv_render] [ 26] color.gb = 1.000000 * vec4(texture(texture1, texcoord1)).rg;
[   0.565][d][libmpv_render] [ 27] color = color.rgbr;
[   0.565][d][libmpv_render] [ 28] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[   0.565][d][libmpv_render] [ 29] color.a = 1.0;
[   0.565][d][libmpv_render] [ 30] // color mapping
[   0.565][d][libmpv_render] [ 31] color.rgb *= vec3(1.000000);
[   0.565][d][libmpv_render] [ 32] color.rgb *= vec3(1.000000);
[   0.565][d][libmpv_render] [ 33] vec3 cpos;
[   0.565][d][libmpv_render] [ 34] cpos[0] = LUT_POS(color[0], 64.0);
[   0.565][d][libmpv_render] [ 35] cpos[1] = LUT_POS(color[1], 64.0);
[   0.565][d][libmpv_render] [ 36] cpos[2] = LUT_POS(color[2], 64.0);
[   0.565][d][libmpv_render] [ 37] color.rgb = tex3D(lut_3d, cpos).rgb;
[   0.565][d][libmpv_render] [ 38] out_color = color;
[   0.565][d][libmpv_render] [ 39] }
[   0.566][d][libmpv_render] shader link log (status=1): 
[   0.933][v][sub/ass] fontselect: (sans-serif, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
[   0.934][v][libmpv_render] Reallocating OSD texture to 1024x256.
[   0.935][d][libmpv_render] vertex shader source:
[   0.935][d][libmpv_render] [  1] #version 410
[   0.935][d][libmpv_render] [  2] #define tex1D texture
[   0.935][d][libmpv_render] [  3] #define tex3D texture
[   0.935][d][libmpv_render] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[   0.935][d][libmpv_render] [  5] in vec2 vertex_position;
[   0.935][d][libmpv_render] [  6] in vec2 vertex_texcoord;
[   0.935][d][libmpv_render] [  7] out vec2 texcoord;
[   0.935][d][libmpv_render] [  8] in vec4 vertex_ass_color;
[   0.935][d][libmpv_render] [  9] out vec4 ass_color;
[   0.935][d][libmpv_render] [ 10] void main() {
[   0.935][d][libmpv_render] [ 11] gl_Position = vec4(vertex_position, 1.0, 1.0);
[   0.935][d][libmpv_render] [ 12] texcoord = vertex_texcoord;
[   0.935][d][libmpv_render] [ 13] ass_color = vertex_ass_color;
[   0.935][d][libmpv_render] [ 14] }
[   0.935][d][libmpv_render] fragment shader source:
[   0.935][d][libmpv_render] [  1] #version 410
[   0.935][d][libmpv_render] [  2] #define tex1D texture
[   0.935][d][libmpv_render] [  3] #define tex3D texture
[   0.935][d][libmpv_render] [  4] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[   0.935][d][libmpv_render] [  5] out vec4 out_color;
[   0.935][d][libmpv_render] [  6] in vec2 texcoord;
[   0.935][d][libmpv_render] [  7] in vec4 ass_color;
[   0.935][d][libmpv_render] [  8] uniform sampler2D osdtex;
[   0.935][d][libmpv_render] [  9] uniform vec3 src_luma;
[   0.935][d][libmpv_render] [ 10] uniform vec3 dst_luma;
[   0.935][d][libmpv_render] [ 11] uniform sampler3D lut_3d;
[   0.935][d][libmpv_render] [ 12] void main() {
[   0.935][d][libmpv_render] [ 13] vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
[   0.935][d][libmpv_render] [ 14] color = vec4(ass_color.rgb, ass_color.a * texture(osdtex, texcoord).r);
[   0.935][d][libmpv_render] [ 15] // color mapping
[   0.935][d][libmpv_render] [ 16] // linearize
[   0.935][d][libmpv_render] [ 17] color.rgb = clamp(color.rgb, 0.0, 1.0);
[   0.935][d][libmpv_render] [ 18] color.rgb = mix(color.rgb * vec3(1.0/12.92),             
[   0.935][d][libmpv_render] [ 19]                 pow((color.rgb + vec3(0.055))/vec3(1.055), vec3(2.4)), 
[   0.935][d][libmpv_render] [ 20]                 bvec3(lessThan(vec3(0.04045), color.rgb))); 
[   0.935][d][libmpv_render] [ 21] color.rgb *= vec3(1.0/1.000000);
[   0.935][d][libmpv_render] [ 22] color.rgb *= vec3(1.000000);
[   0.935][d][libmpv_render] [ 23] color.rgb *= vec3(1.000000);
[   0.935][d][libmpv_render] [ 24] // delinearize
[   0.935][d][libmpv_render] [ 25] color.rgb = clamp(color.rgb, 0.0, 1.0);
[   0.935][d][libmpv_render] [ 26] color.rgb *= vec3(1.000000);
[   0.935][d][libmpv_render] [ 27] color.rgb = pow(color.rgb, vec3(1.0/2.4));
[   0.935][d][libmpv_render] [ 28] vec3 cpos;
[   0.935][d][libmpv_render] [ 29] cpos[0] = LUT_POS(color[0], 64.0);
[   0.935][d][libmpv_render] [ 30] cpos[1] = LUT_POS(color[1], 64.0);
[   0.935][d][libmpv_render] [ 31] cpos[2] = LUT_POS(color[2], 64.0);
[   0.935][d][libmpv_render] [ 32] color.rgb = tex3D(lut_3d, cpos).rgb;
[   0.935][d][libmpv_render] [ 33] out_color = color;
[   0.935][d][libmpv_render] [ 34] }
[   0.936][d][libmpv_render] shader link log (status=1): 
[   1.778][v][cplayer] Set property: pause=true -> 1
[   1.778][d][cplayer] Run command: seek, flags=64, args=[target="5.340130", flags="absolute-percent+exact", legacy="unused"]
[   1.778][v][lavf] queuing seek to 2.739860
[   1.779][v][lavf] queuing seek to 2.739860
[   1.779][v][lavf] execute seek (to 2.739860 flags 0)
[   1.779][v][lavf] seek done
[   1.779][v][cplayer] hr-seek, skipping to 2.739860
[   1.779][v][lavf] execute seek (to 2.739860 flags 32)
[   1.780][v][lavf] seek done
[   1.780][v][file] stream level seek from 1431710 to 155475
[   1.782][v][vd] Pixel formats supported by decoder: videotoolbox_vld yuv420p
[   1.782][v][vd] Codec profile: Main (0x4d)
[   1.782][v][vd] Requesting pixfmt 'videotoolbox_vld' from decoder.
[   1.786][d][ffmpeg/video] h264: Reinit context to 1280x720, pix_fmt: videotoolbox_vld
[   1.793][v][vd] Decoder format: 1280x720 [9:10] videotoolbox[nv12] auto/auto/auto/auto/auto CL=mpeg2/4/h264
[   1.793][v][vd] Using container aspect ratio.
[   1.800][d][cplayer] Run command: seek, flags=64, args=[target="5.340130", flags="absolute-percent+exact", legacy="unused"]
[   1.809][d][cplayer] Run command: seek, flags=64, args=[target="5.340130", flags="absolute-percent+exact", legacy="unused"]
[   1.816][v][lavf] EOF reached.
[   1.818][v][libmpv_render] Reallocating OSD texture to 1024x512.
[   2.021][v][vo/libmpv] mpv_render_report_swap() not being called.
[   2.022][v][cplayer] first video frame after restart shown
[   2.022][d][cplayer] Run command: seek, flags=64, args=[target="5.340130", flags="absolute-percent+exact", legacy="unused"]
[   2.028][v][cplayer] audio ready
[   2.028][d][cplayer] starting video playback
[   2.028][v][lavf] queuing seek to 2.739860
[   2.028][v][lavf] queuing seek to 2.739860
[   2.028][v][lavf] execute seek (to 2.739860 flags 0)
[   2.028][v][lavf] seek done
[   2.028][v][lavf] execute seek (to 2.739860 flags 32)
[   2.028][v][lavf] seek done
[   2.029][v][cplayer] hr-seek, skipping to 2.739860
[   2.031][v][vd] Pixel formats supported by decoder: videotoolbox_vld yuv420p
[   2.031][v][vd] Codec profile: Main (0x4d)
[   2.031][v][vd] Requesting pixfmt 'videotoolbox_vld' from decoder.
[   2.036][d][ffmpeg/video] h264: Reinit context to 1280x720, pix_fmt: videotoolbox_vld
[   2.045][v][vd] Decoder format: 1280x720 [9:10] videotoolbox[nv12] auto/auto/auto/auto/auto CL=mpeg2/4/h264
[   2.045][v][vd] Using container aspect ratio.
[   2.045][d][cplayer] Run command: seek, flags=64, args=[target="1.152820", flags="absolute-percent+exact", legacy="unused"]
[   2.053][d][cplayer] Run command: seek, flags=64, args=[target="0.908679", flags="absolute-percent+exact", legacy="unused"]
[   2.055][d][cplayer] Run command: seek, flags=64, args=[target="0.908679", flags="absolute-percent+exact", legacy="unused"]
[   2.066][v][lavf] EOF reached.
[   2.271][v][vo/libmpv] mpv_render_report_swap() not being called.
[   2.271][v][cplayer] first video frame after restart shown
[   2.271][d][cplayer] Run command: seek, flags=64, args=[target="0.908679", flags="absolute-percent+exact", legacy="unused"]
[   2.275][v][cplayer] Set property: pause=false -> 1
[   2.275][v][cplayer] audio ready
[   2.275][d][cplayer] starting video playback
[   2.275][v][lavf] queuing seek to 0.466216
[   2.275][v][lavf] queuing seek to 0.466216
[   2.275][v][lavf] execute seek (to 0.466216 flags 0)
[   2.275][v][lavf] execute seek (to 0.466216 flags 32)
[   2.275][v][lavf] seek done
[   2.275][v][lavf] seek done
[   2.275][v][cplayer] hr-seek, skipping to 0.466216
[   2.276][v][file] stream level seek from 352083 to 57807
[   2.278][v][vd] Pixel formats supported by decoder: videotoolbox_vld yuv420p
[   2.278][v][vd] Codec profile: Main (0x4d)
[   2.278][v][vd] Requesting pixfmt 'videotoolbox_vld' from decoder.
[   2.283][d][ffmpeg/video] h264: Reinit context to 1280x720, pix_fmt: videotoolbox_vld
[   2.291][v][vd] Decoder format: 1280x720 [9:10] videotoolbox[nv12] auto/auto/auto/auto/auto CL=mpeg2/4/h264
[   2.291][v][vd] Using container aspect ratio.
[   2.291][d][cplayer] Run command: seek, flags=64, args=[target="0.908679", flags="absolute-percent+exact", legacy="unused"]
[   2.305][v][lavf] EOF reached.
[   2.318][v][cplayer] first video frame after restart shown
[   2.319][v][cplayer] audio ready
[   2.319][d][cplayer] starting video playback
[   2.319][v][lavf] queuing seek to 0.466216
[   2.319][v][lavf] queuing seek to 0.466216
[   2.319][v][lavf] execute seek (to 0.466216 flags 0)
[   2.319][v][lavf] seek done
[   2.319][v][lavf] execute seek (to 0.466216 flags 32)
[   2.319][v][lavf] seek done
[   2.319][v][cplayer] hr-seek, skipping to 0.466216
[   2.320][v][vd] Pixel formats supported by decoder: videotoolbox_vld yuv420p
[   2.320][v][vd] Codec profile: Main (0x4d)
[   2.320][v][vd] Requesting pixfmt 'videotoolbox_vld' from decoder.
[   2.325][d][ffmpeg/video] h264: Reinit context to 1280x720, pix_fmt: videotoolbox_vld
[   2.332][v][vd] Decoder format: 1280x720 [9:10] videotoolbox[nv12] auto/auto/auto/auto/auto CL=mpeg2/4/h264
[   2.332][v][vd] Using container aspect ratio.
[   2.345][v][lavf] EOF reached.
[   2.352][v][cplayer] first video frame after restart shown
[   2.352][v][cplayer] audio ready
[   2.352][d][cplayer] starting video playback
[   2.352][v][cplayer] starting audio playback
[   2.360][v][cplayer] playback restart complete @ 0.466667, audio=playing, video=playing
[  10.879][v][libmpv_render] Reallocating OSD texture to 2048x256.
[  17.648][v][cplayer] Set property: pause=true -> 1
[  18.907][d][cplayer] Run command: write-watch-later-config, flags=64, args=[]
[  18.908][d][global] config path: '/Users/danil0110/Library/Application Support/com.colliderli.iina/watch_later' -> '-'
[  18.908][i][cplayer] Saving state.
[  18.910][d][cplayer] Run command: stop, flags=64, args=[flags=""]
[  18.910][v][cplayer] EOF code: 4  
[  18.910][d][ad] Uninit decoder.
[  18.910][d][vd] Uninit decoder.
[  18.912][d][cplayer] Terminating demuxers...
[  18.912][d][cplayer] Done terminating demuxers.
[  18.912][v][cplayer] finished playback, success (reason 2)
[  18.912][i][cplayer] 
[  18.925][v][cplayer] Set property: icc-profile="/Library/ColorSync/Profiles/Displays/Color LCD-37D8832A-2D66-02CA-B9F7-8F30A301B230.icc" -> 1
[  18.926][v][cplayer] Set property: icc-profile="/Library/ColorSync/Profiles/Displays/Color LCD-37D8832A-2D66-02CA-B9F7-8F30A301B230.icc" -> 1
[  18.929][d][libmpv_render] flushing shader cache
[  18.929][d][cplayer] Run command: quit, flags=64, args=[code="0"]
[  18.929][d][ytdl_hook] Exiting...
[  18.930][d][console] Exiting...
[  18.930][d][stats] Exiting...
[  18.935][d][main] Exiting...
```
</details>

<br>

**Steps to reproduce:**
1. Open any video
2. It starts playing. Timeline in the Touchbar is dynamic. After a few seconds it freezes
3. Move the cursor. Timeline becomes dynamic again. After a few seconds it freezes

**How often does this happen?**
Everytime

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Add a new method makeTouchBar to PlayerCore
- Change MainWindowController and MiniPlayerWindowController extensions in TouchBarSupport to call the new method
- Add a hasTouchBar property to TouchBarSupport
- Change MainWindowController.hideUI to not stop the timer that synchronizes the UI if the Mac has a touch bar

This corrects a regression added by a change to hideUI to stop the timer when the OSC is hidden in order to save energy. That change failed to take into account that the timer also synchronizes controls in the touch bar on MacBooks that have one.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4058.

---

**Description:**

### CODE REVIEW

**Comment by low-batt** [comment]
The regression was due to the change that stops the timer that synchronizes the UI when the OSC is hidden in order to save energy. That change failed to take into account that the timer also synchronizes controls in the touch bar on MacBooks that have one.

In trying to correct the regression and yet not run the timer when it is not needed I looked for APIs that would answer:
- Does the Mac have a touch bar?
- Is the touch bar configured to show app controls?
- Is the touch bar awake?
- Is the MacBook in closed clamshell mode?

Unfortunately Apple thinks there is no need for an application to know if the Mac has a touch bar. From the documentation for [NSTouchBar](https://developer.apple.com/documentation/appkit/nstouchbar):
> There’s no need, and no API, for your app to know whether or not there’s a Touch Bar available. Whether your app is running on a machine that supports the Touch Bar or not, your app’s onscreen user interface (UI) appears and behaves the same way.

I found [isVisible](https://developer.apple.com/documentation/appkit/nstouchbaritem/2544669-isvisible) was `true` even when the touch bar was not displaying the application's UI.

So to determine if the Mac has a touch bar the code is checking whether AppKit has called [makeTouchBar](https://developer.apple.com/documentation/appkit/nsresponder/2544690-maketouchbar). This allows the timer to be stopped on Macs that do not have touch bars. This also avoided running the timer when a MacBook with a touch bar is running in closed clamshell mode.

Reviewers, is there a better way to determine if a touch bar is present?

**Comment by low-batt** [comment]
I've added an additional commit that addresses issue #4051 as it involves the same code.

**Review by uiryuu — APPROVED** [review]

File: iina/PlayerCore.swift [hunk 1]
```diff
@@ -93,6 +93,12 @@ class PlayerCore: NSObject {
   }
   private var _touchBarSupport: Any?
 
+  /// `true` if this Mac is known to have a touch bar.
+  ///
+  /// - Note: This is set based on whether `AppKit` has called `MakeTouchBar`, therefore it can, for example, be `false` for
+  ///         a MacBook that has a touch bar if the touch bar is asleep because the Mac is in closed clamshell mode.
+  var hasTouchBar = false
```
Comment (saagarjha) [inline iina/PlayerCore.swift]:
```suggestion
  var needsTouchBar = false
```

Based on the comment above.

Comment (low-batt) [reply iina/PlayerCore.swift]: Latest commit renames the new property to needsTouchBar as recommended.
