### PR TITLE
Fix chapter list not updating and/or crashing (issue #4696)

### LINKED ISSUE #4696: Keep the chapter menu on and play the next video, the menu is unchanged, and IINA crashes when clicking on the menu for navigation
**System and IINA version:**

- macOS Catalina 10.15.7
- IINA 1.3.3 Build 138

**Expected behavior:**

The chapter menu changes when playing the next video.

**Actual behavior:**

The chapter menu keeps unchanged, and IINA crashes when clicking on the menu for navigation.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

Keep the chapter menu on and play the next video, the menu is unchanged, and IINA crashes when clicking on the menu for navigation

- [ ] MPV does not have this problem.

**How often does this happen?**

Always

### PR DESCRIPTION
**Pull request by svobs**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4696.

---

**Description:**

* Removes bad code from `PlayerCore.getChapters()` which returned early when chapter count == 0. This resulted in chapter list not getting updated in this situation.
* Fix crash by adding checks whether index is valid into chapters array wherever it is referenced.
* Generally fix potential concurrency pitfalls relating to chapters list (see comments in code).
* Chapter list reload triggers table reload. Not the other way around.

### CODE REVIEW

File: iina/PlaySliderCell.swift [hunk 1]
```diff
@@ -206,9 +206,8 @@ class PlaySliderCell: NSSliderCell {
       if let totalSec = info.videoDuration?.second {
         chapterStrokeColor.setStroke()
         var chapters = info.chapters
```
Comment (low-batt) [inline iina/PlaySliderCell.swift]:
```suggestion
        let chapters = info.chapters
```

File: iina/MainMenuActions.swift [hunk 2]
```diff
@@ -154,8 +154,12 @@ extension MainMenuActionHandler {
 
   @objc func menuChapterSwitch(_ sender: NSMenuItem) {
     let index = sender.tag
-    player.playChapter(index)
-    let chapter = player.info.chapters[index]
+    guard let chapter = player.playChapter(index) else {
+      Logger.log("Cannot switch to chapter \(index) because it was not found! Will ignore request and reload chapters instead",
+                 level: .error, subsystem: player.subsystem)
```
Comment (low-batt) [inline iina/MainMenuActions.swift]: I think error is too strong for this situation. The user can trigger this. IINA recovers. There isn't an error that needs to be corrected. I would emit this as a debug level message.

**Review by low-batt — CHANGES_REQUESTED** [review]
Pulled PR, tested, confirmed crash no longer happens.

The variable in `PlaySliderCell` should be changed to be a let constant to correct a new compiler warning.

I would change the log level of that one message although that is not critical.

**Comment by svobs** [comment]
> The variable in PlaySliderCell should be changed to be a let constant to correct a new compiler warning.
> I would change the log level of that one message although that is not critical.

Done. Committed (also rebased). In the XCode 15 release notes, I saw this:
> Fixed an issue where build warnings in Swift files sometimes disappeared after an incremental build.  (105421512)

Doesn't seem to be fixed in all cases, unfortunately.

**Review by low-batt — APPROVED** [review]
All looks good to me.

**Comment by low-batt** [comment]
I have experienced that Xcode behavior where warnings are not shown as well. Very frustrating.

PRs are being merged for a 1.3.4 release. The main focus of this release is the switch to Open Subtitle's REST API as the old API is shutting down at the end of the year. This PR is on the list for that release.

**Comment by uiryuu** [comment]
Thanks!
