### PR TITLE
Fix crash while quitting in mpv_render_context_free, #5031

### LINKED ISSUE #5031: Crash while quitting in mpv_render_context_free
**System and IINA version:**

- macOS 13.6.3
- IINA 1.3.3

**Expected behavior:**
IINA does not crash.

**Actual behavior:**
In issue #4621 @JayBrown reported a side effect of that problem was that IINA would crash during shutdown. I've created this issue for that crash.

The crash happens in `glDeleteTextures` called from `mpv_render_context_free` which is called by `uninit` in `VideoView` as a part of shutting down.

<details>
<summary><b>Crash report:</b></summary>

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               IINA [6643]
Path:                  /Users/USER/*/IINA.app/Contents/MacOS/IINA
Identifier:            com.colliderli.iina
Version:               1.3.3 (138)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-10-10 00:23:12.7316 +0200
OS Version:            macOS 13.6 (22G120)
Report Version:        12
Bridge OS Version:     8.0 (21P365)
Anonymous UUID:        27A319F2-68D4-6212-7623-A3120AF6D7A2


Time Awake Since Boot: 3000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       UNKNOWN_0xD at 0x0000000000000000
Exception Codes:       0x000000000000000d, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [6643]

VM Region Info: 0 is not in any region.  Bytes before following region: 4371877888
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104959000-104c4d000    [ 3024K] r-x/r-x SM=COW  ...ts/MacOS/IINA

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libGL.dylib                   	    0x7ffa35e0e4f7 glDeleteTextures + 29
1   libmpv.2.dylib                	       0x1060da427 ra_tex_free + 23
2   libmpv.2.dylib                	       0x1060e883b gl_video_uninit + 107
3   libmpv.2.dylib                	       0x1060d945c destroy + 28
4   libmpv.2.dylib                	       0x1060f7f22 mpv_render_context_free + 178
5   IINA                          	       0x104ae312c closure #1 in VideoView.uninit() + 380
6   IINA                          	       0x104b4347d partial apply for closure #1 in VideoView.uninit() + 13
7   IINA                          	       0x104b434cd partial apply for specialized closure #1 in Atomic.withLock<A>(_:) + 77
8   IINA                          	       0x104adcdd2 OSUnfairLockImpl.withLock<A>(_:) + 50
9   IINA                          	       0x104adce00 protocol witness for LockImpl.withLock<A>(_:) in conformance OSUnfairLockImpl + 16
10  IINA                          	       0x104b1e920 PlayerCore.uninitVideo() + 400
11  IINA                          	       0x104b1e9e7 PlayerCore.shutdown() + 151
12  IINA                          	       0x104a56c32 closure #2 in AppDelegate.applicationShouldTerminate(_:) + 194
13  IINA                          	       0x104b68143 thunk for @escaping @callee_guaranteed @Sendable (@in_guaranteed Notification) -> () + 99
14  CoreFoundation                	    0x7ff81c3a6687 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 120
15  CoreFoundation                	    0x7ff81c43f40e ___CFXRegistrationPost_block_invoke + 88
16  CoreFoundation                	    0x7ff81c43f363 _CFXRegistrationPost + 536
17  CoreFoundation                	    0x7ff81c379937 _CFXNotificationPost + 729
18  IINA                          	       0x104b31d9c PlayerCore.postNotification(_:) + 188
19  IINA                          	       0x104b5ce7a closure #7 in MPVController.handleEvent(_:) + 154
20  IINA                          	       0x104a28b49 thunk for @escaping @callee_guaranteed () -> () + 25
21  libdispatch.dylib             	    0x7ff81c132d91 _dispatch_call_block_and_release + 12
22  libdispatch.dylib             	    0x7ff81c134033 _dispatch_client_callout + 8
23  libdispatch.dylib             	    0x7ff81c140fcf _dispatch_main_queue_drain + 954
24  libdispatch.dylib             	    0x7ff81c140c07 _dispatch_main_queue_callback_4CF + 31
25  CoreFoundation                	    0x7ff81c3f01a5 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
26  CoreFoundation                	    0x7ff81c3afecf __CFRunLoopRun + 2452
27  CoreFoundation                	    0x7ff81c3aeed1 CFRunLoopRunSpecific + 560
28  HIToolbox                     	    0x7ff825e2ff3d RunCurrentEventLoopInMode + 292
29  HIToolbox                     	    0x7ff825e2fd4e ReceiveNextEventCommon + 657
30  HIToolbox                     	    0x7ff825e2faa8 _BlockUntilNextEventMatchingListInModeWithFilter + 64
31  AppKit                        	    0x7ff81f44b25c _DPSNextEvent + 858
32  AppKit                        	    0x7ff81f44a106 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
33  AppKit                        	    0x7ff81f6cb037 -[NSApplication _shouldTerminate] + 1278
34  AppKit                        	    0x7ff81f819165 -[NSApplication(NSAppleEventHandling) _handleAEQuit] + 323
35  AppKit                        	    0x7ff81f45062d -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 686
36  Foundation                    	    0x7ff81d210aa4 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308
37  Foundation                    	    0x7ff81d210916 _NSAppleEventManagerGenericHandler + 80
38  AE                            	    0x7ff8227ff033 0x7ff8227f0000 + 61491
39  AE                            	    0x7ff8227fe89f 0x7ff8227f0000 + 59551
40  AE                            	    0x7ff8227f7ec4 aeProcessAppleEvent + 419
41  HIToolbox                     	    0x7ff825e3fc48 AEProcessAppleEvent + 54
42  AppKit                        	    0x7ff81f44b5a6 _DPSNextEvent + 1700
43  AppKit                        	    0x7ff81f44a106 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
44  AppKit                        	    0x7ff81f43c788 -[NSApplication run] + 586
45  AppKit                        	    0x7ff81f4109a1 NSApplicationMain + 817
46  IINA                          	       0x10495eeb9 main + 9
47  dyld                          	    0x7ff81bf7b41f start + 1903
```
</details>

<br>

**Steps to reproduce:**
Unknown. I have not been able to reproduce this crash.

- [ ] MPV does not have this problem.

Unknown, but likely this is an IINA problem.

**How often does this happen?**
Unknown, but @JayBrown was able to reproduce this crash and posted mulitple crash reports in issue

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Move the call to `mpv_destroy` in `MPVController` from `handleEvent` to `mpvUninitRendering`
- Move the call to `NSApp.terminate` in `MPVController` from `handleEvent` to `PlayerCore.mpvHasShutdown`
- Add call to `NSApp.terminate` in `PlayerWindowController.handleKeyBinding` for when a key is bound to the mpv `quit` command
- Remove call to `VideoLayer.suspend` from `VideoView.uninit`
- Move call to `stopDisplayLink` from `PlayerCore.uninitVideo` to `VideoView.uninit`
- Change code in `MainWindowController` that checks `isClosing` to instead check the player status
- Remove i`sClosing` property from `MainWindowController`

These changes cause uninitializing the video, which involves calling `mpv_render_context_free`, to be done after the `quit` command finishes instead of before. This also changes the call to `mpv_destroy` to be performed right after the call to `mpv_render_context_free` with the OpenGL context locked. This matches how mpv uses `mpv_destroy`.

This also changes the behavior of keys bound to the mpv `quit` command. Previously the `quit` command would be passed to mpv. With this commit the key press starts the normal app termination sequence.

Testing proved the `isClosing` flag did not cover all cases and the state of the player needed to be checked.

The crash in `mpv_render_context_free` could not be reproduced, so it is not known for certain that these changes fixed issue #5031.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #5031.

---

**Description:**

### CODE REVIEW

File: iina/MainWindowController.swift [hunk 1]
```diff
@@ -244,7 +242,7 @@ class MainWindowController: PlayerWindowController {
   var fsState: FullScreenState = .windowed {
     didSet {
       // Must not access mpv while it is asynchronously processing stop and quit commands.
-      guard !isClosing else { return }
+      guard !player.isStopping, !player.isStopped, !player.isShuttingDown, !player.isShutdown else { return }
```
Comment (lhc70000) [inline iina/MainWindowController.swift:245]: Maybe we can replace this with a computed property to reduce redundancy (we also use this guard in other classes).

Comment (low-batt) [reply iina/MainWindowController.swift:245]: Yes, I have plans to refactor this into a player state variable and use computed properties. I want to do that as a separate PR and not mix fixes with refactoring.
