### PR TITLE
Fix data races, #3829, #3830, #3936, #3937

### LINKED ISSUE #3829: ThreadSanitizer: data race in VideoTime.second.getter
**System and IINA version:**

- macOS 10.15.7
- IINA 1.3.0 debug build

**Expected behavior:**
IINA runs without error when built with the thread sanitizer enabled.

**Actual behavior:**
A debug version of IINA was built under Xcode 13.4 on a M1 MacBookPro18,2 with the thread sanitizer enabled. The resulting application was taken to a 2019 MacBookAir8,2 with an Intel chip running macOS 10.15.7. The thread sanitizer reported multiple data races and when IINA was quit the thread sanitizer triggered a crash. Will report separate issues for the different problems to isolate fixes. This issue is about this warning from the thread sanitizer:
```text
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x10015a2ba) in VideoTime.second.getter+0x3a
```

Multiple threads are accessing this `PlaybackInfo` property:
```swift
var videoDuration: VideoTime?
```

The queue "com.colliderli.iina.controller" processes mpv events and calls `PlayerCore.fileLoaded` which directly gets `videoDuration`:
```swift
    // add to history
    if let url = info.currentURL {
      let duration = info.videoDuration ?? .zero
      HistoryController.shared.add(url, duration: duration.second)
      if Preference.bool(for: .recordRecentFiles) && Preference.bool(for: .trackAllFilesInRecentOpenMenu) {
        NSDocumentController.shared.noteNewRecentDocumentURL(url)
      }
    }

```

And the timer running on the main thread that calls `PlayerCore.syncUITime` which sets `videoDuration`:
```swift
    case .time:
      info.videoPosition?.second = mpv.getDouble(MPVProperty.timePos)
      if info.isNetworkResource {
        info.videoDuration?.second = mpv.getDouble(MPVProperty.duration)
      }
```

<details>
<summary><b>Crash report:</b></summary>

```text
Process:               IINA [29731]
Path:                  /Users/USER/Documents/*/IINA.app/Contents/MacOS/IINA
Identifier:            com.colliderli.iina
Version:               1.3.0 (131)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           IINA [29731]
User ID:               502

Date/Time:             2022-06-13 16:23:53.302 -0400
OS Version:            Mac OS X 10.15.7 (19H1824)
Report Version:        12
Bridge OS Version:     6.4 (19P4242)
Anonymous UUID:        954A8385-28AB-9AF4-B895-3C24A2049280

Sleep/Wake UUID:       A633279D-633B-4221-B425-065C8C33019F

Time Awake Since Boot: 89000 seconds
Time Since Wake:       1600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Write of size 1 at 0x7b10000f22b8 by main thread:
    #0 ViewLayer.needsMPVRender.setter <null>:2 (IINA:x86_64+0x1004bd54a)
    #1 ViewLayer.draw(forced:) <null>:2 (IINA:x86_64+0x1004c20fc)
    #2 MainWindowController.windowWillOpen() <null>:2 (IINA:x86_64+0x10023ab40)
    #3 PlayerCore.openMainWindow(path:url:isNetwork:) <null>:2 (IINA:x86_64+0x1005a4c4b)
    #4 PlayerCore.open(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a1894)
    #5 PlayerCore.openURLs(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2480)
    #6 PlayerCore.openURL(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2d25)
    #7 OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x1004962d7)
    #8 @objc OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x10049654f)
    #9 -[NSApplication(NSResponder) sendAction:to:from:] <null>:2 (AppKit:x86_64+0x283cf6)
    #10 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Previous write of size 1 at 0x7b10000f22b8 by thread T21 (mutexes: write M386038120195514024):
    #0 ViewLayer.needsMPVRender.setter <null>:2 (IINA:x86_64+0x1004bd54a)
    #1 ViewLayer.draw(forced:) <null>:2 (IINA:x86_64+0x1004c2be9)
    #2 closure #1 in mpvUpdateCallback(_:) <null>:2 (IINA:x86_64+0x10065af0d)
    #3 partial apply for closure #1 in mpvUpdateCallback(_:) <null>:2 (IINA:x86_64+0x1006621b9)
    #4 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #5 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #6 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Location is heap block of size 64 at 0x7b10000f2280 allocated by main thread:
    #0 calloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x534a4)
    #1 _objc_rootAllocWithZone <null>:3 (libobjc.A.dylib:x86_64h+0x10804)
    #2 closure #1 in VideoView.videoLayer.getter <null>:2 (IINA:x86_64+0x1004de007)
    #3 VideoView.videoLayer.getter <null>:2 (IINA:x86_64+0x1004ddebf)
    #4 VideoView.init(frame:) <null>:2 (IINA:x86_64+0x1004e1593)
    #5 @objc VideoView.init(frame:) <null>:2 (IINA:x86_64+0x1004e1e05)
    #6 VideoView.__allocating_init(frame:player:) <null>:2 (IINA:x86_64+0x1004e1f53)
    #7 MainWindowController._videoView.getter <null>:2 (IINA:x86_64+0x1001f4251)
    #8 MainWindowController.videoView.getter <null>:2 (IINA:x86_64+0x1001f3e39)
    #9 MainWindowController.addVideoViewToWindow() <null>:2 (IINA:x86_64+0x1002258b1)
    #10 MainWindowController.windowDidLoad() <null>:2 (IINA:x86_64+0x100221307)
    #11 @objc MainWindowController.windowDidLoad() <null>:2 (IINA:x86_64+0x1002245a1)
    #12 -[NSWindowController _windowDidLoad] <null>:2 (AppKit:x86_64+0x23a72d)
    #13 PlayerCore.open(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a1894)
    #14 PlayerCore.openURLs(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2480)
    #15 PlayerCore.openURL(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2d25)
    #16 OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x1004962d7)
    #17 @objc OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x10049654f)
    #18 -[NSApplication(NSResponder) sendAction:to:from:] <null>:2 (AppKit:x86_64+0x283cf6)
    #19 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Mutex M386038120195514024 is already destroyed.
 
  Thread T21 (tid=955443, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x1004bd54a) in ViewLayer.needsMPVRender.setter+0x8a
==================
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Read of size 8 at 0x7b0800013d90 by thread T26:
    #0 VideoTime.second.getter <null>:2 (IINA:x86_64+0x10015a2ba)
    #1 PlayerCore.fileLoaded() <null>:2 (IINA:x86_64+0x1005d29b8)
    #2 MPVController.onFileLoaded() <null>:2 (IINA:x86_64+0x100645d59)
    #3 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x1006432a8)
    #4 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #5 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #6 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #7 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #8 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Previous write of size 8 at 0x7b0800013d90 by main thread:
    #0 VideoTime.second.setter <null>:2 (IINA:x86_64+0x10015a31f)
    #1 PlayerCore.syncUI(_:) <null>:2 (IINA:x86_64+0x1005db14d)
    #2 PlayerCore.syncUITime() <null>:2 (IINA:x86_64+0x1005d8c9c)
    #3 @objc PlayerCore.syncUITime() <null>:2 (IINA:x86_64+0x1005d9641)
    #4 __NSFireTimer <null>:2 (Foundation:x86_64+0xbed69)
    #5 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Location is heap block of size 24 at 0x7b0800013d80 allocated by thread T26:
    #0 malloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x532ec)
    #1 swift_slowAlloc <null>:2 (libswiftCore.dylib:x86_64+0x2f2ca8)
    #2 MPVController.onFileLoaded() <null>:2 (IINA:x86_64+0x100645940)
    #3 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x1006432a8)
    #4 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #5 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #6 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #7 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #8 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Thread T26 (tid=955714, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x10015a2ba) in VideoTime.second.getter+0x3a
==================
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Write of size 8 at 0x7b0800013ab0 by thread T26:
    #0 VideoTime.second.setter <null>:2 (IINA:x86_64+0x10015a31f)
    #1 PlayerCore.syncUI(_:) <null>:2 (IINA:x86_64+0x1005d9f67)
    #2 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x10064358c)
    #3 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #4 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #5 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #6 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #7 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Previous write of size 8 at 0x7b0800013ab0 by main thread:
    #0 VideoTime.second.setter <null>:2 (IINA:x86_64+0x10015a31f)
    #1 PlayerCore.syncUI(_:) <null>:2 (IINA:x86_64+0x1005dae27)
    #2 PlayerCore.syncUITime() <null>:2 (IINA:x86_64+0x1005d8c9c)
    #3 @objc PlayerCore.syncUITime() <null>:2 (IINA:x86_64+0x1005d9641)
    #4 __NSFireTimer <null>:2 (Foundation:x86_64+0xbed69)
    #5 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Location is heap block of size 24 at 0x7b0800013aa0 allocated by thread T26:
    #0 malloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x532ec)
    #1 swift_slowAlloc <null>:2 (libswiftCore.dylib:x86_64+0x2f2ca8)
    #2 MPVController.onFileLoaded() <null>:2 (IINA:x86_64+0x100645c7c)
    #3 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x1006432a8)
    #4 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #5 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #6 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #7 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #8 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Thread T26 (tid=955714, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x10015a31f) in VideoTime.second.setter+0x3f
==================
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Write of size 1 at 0x7b540000c3a8 by thread T22:
    #0 PlaybackInfo.isSeeking.setter <null>:2 (IINA:x86_64+0x10011f5de)
    #1 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x10064427e)
    #2 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #3 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #4 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #5 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #6 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Previous read of size 1 at 0x7b540000c3a8 by main thread:
    #0 PlaybackInfo.isSeeking.getter <null>:2 (IINA:x86_64+0x10011f550)
    #1 MainWindowController.updateNetworkState() <null>:2 (IINA:x86_64+0x10027538e)
    #2 $s4IINA10PlayerCoreC6syncUIyyAC12SyncUIOptionOFyyScMYccfU0_ <null>:2 (IINA:x86_64+0x1005ddbd6)
    #3 $s4IINA10PlayerCoreC6syncUIyyAC12SyncUIOptionOFyyScMYccfU0_TA <null>:2 (IINA:x86_64+0x1005f4ce9)
    #4 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #5 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #6 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
    #7 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Location is heap block of size 616 at 0x7b540000c300 allocated by main thread:
    #0 malloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x532ec)
    #1 swift_slowAlloc <null>:2 (libswiftCore.dylib:x86_64+0x2f2ca8)
    #2 PlayerCore.info.getter <null>:2 (IINA:x86_64+0x10059d049)
    #3 MPVController.mpvInit() <null>:2 (IINA:x86_64+0x1006295a0)
    #4 PlayerCore.startMPV() <null>:2 (IINA:x86_64+0x1005a89cb)
    #5 static PlayerCore.createPlayerCore() <null>:2 (IINA:x86_64+0x1005980cb)
    #6 $s4IINA10PlayerCoreC5first_WZ <null>:2 (IINA:x86_64+0x100597cc3)
    #7 dispatch_once <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x78be3)
    #8 dispatch_once_f <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x78ccb)
    #9 swift_once <null>:2 (libswiftCore.dylib:x86_64+0x31a839)
    #10 static PlayerCore.active.getter <null>:2 (IINA:x86_64+0x1005986fe)
    #11 AppDelegate.applicationDidFinishLaunching(_:) <null>:2 (IINA:x86_64+0x1003149ec)
    #12 @objc AppDelegate.applicationDidFinishLaunching(_:) <null>:2 (IINA:x86_64+0x100318e66)
    #13 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ <null>:3 (CoreFoundation:x86_64h+0x7a14e)
    #14 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Thread T22 (tid=955442, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x10011f5de) in PlaybackInfo.isSeeking.setter+0x5e
==================
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Read of size 1 at 0x7b10000f22b9 by thread T40 (mutexes: write M386038120195514024):
    #0 ViewLayer.forceRender.getter <null>:2 (IINA:x86_64+0x1004bd6d8)
    #1 ViewLayer.canDraw(inCGLContext:pixelFormat:forLayerTime:displayTime:) <null>:2 (IINA:x86_64+0x1004bf7fc)
    #2 @objc ViewLayer.canDraw(inCGLContext:pixelFormat:forLayerTime:displayTime:) <null>:2 (IINA:x86_64+0x1004bfc23)
    #3 CAOpenGLLayerDraw(CAOpenGLLayer*, double, CVTimeStamp const*, unsigned int) <null>:2 (QuartzCore:x86_64+0xc1fce)
    #4 @objc ViewLayer.display() <null>:2 (IINA:x86_64+0x1004c3641)
    #5 ViewLayer.draw(forced:) <null>:2 (IINA:x86_64+0x1004c2147)
    #6 closure #1 in mpvUpdateCallback(_:) <null>:2 (IINA:x86_64+0x10065af0d)
    #7 partial apply for closure #1 in mpvUpdateCallback(_:) <null>:2 (IINA:x86_64+0x1006621b9)
    #8 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #9 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #10 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Previous write of size 1 at 0x7b10000f22b9 by thread T22:
    #0 ViewLayer.forceRender.setter <null>:2 (IINA:x86_64+0x1004bd78a)
    #1 ViewLayer.draw(forced:) <null>:2 (IINA:x86_64+0x1004c211d)
    #2 PlayerCore.playbackRestarted() <null>:2 (IINA:x86_64+0x1005d40aa)
    #3 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x100644594)
    #4 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #5 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #6 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #7 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #8 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Location is heap block of size 64 at 0x7b10000f2280 allocated by main thread:
    #0 calloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x534a4)
    #1 _objc_rootAllocWithZone <null>:3 (libobjc.A.dylib:x86_64h+0x10804)
    #2 closure #1 in VideoView.videoLayer.getter <null>:2 (IINA:x86_64+0x1004de007)
    #3 VideoView.videoLayer.getter <null>:2 (IINA:x86_64+0x1004ddebf)
    #4 VideoView.init(frame:) <null>:2 (IINA:x86_64+0x1004e1593)
    #5 @objc VideoView.init(frame:) <null>:2 (IINA:x86_64+0x1004e1e05)
    #6 VideoView.__allocating_init(frame:player:) <null>:2 (IINA:x86_64+0x1004e1f53)
    #7 MainWindowController._videoView.getter <null>:2 (IINA:x86_64+0x1001f4251)
    #8 MainWindowController.videoView.getter <null>:2 (IINA:x86_64+0x1001f3e39)
    #9 MainWindowController.addVideoViewToWindow() <null>:2 (IINA:x86_64+0x1002258b1)
    #10 MainWindowController.windowDidLoad() <null>:2 (IINA:x86_64+0x100221307)
    #11 @objc MainWindowController.windowDidLoad() <null>:2 (IINA:x86_64+0x1002245a1)
    #12 -[NSWindowController _windowDidLoad] <null>:2 (AppKit:x86_64+0x23a72d)
    #13 PlayerCore.open(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a1894)
    #14 PlayerCore.openURLs(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2480)
    #15 PlayerCore.openURL(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2d25)
    #16 OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x1004962d7)
    #17 @objc OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x10049654f)
    #18 -[NSApplication(NSResponder) sendAction:to:from:] <null>:2 (AppKit:x86_64+0x283cf6)
    #19 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Mutex M386038120195514024 is already destroyed.
 
  Thread T40 (tid=955817, running) is a GCD worker thread
 
  Thread T22 (tid=955442, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x1004bd6d8) in ViewLayer.forceRender.getter+0x68
==================
ThreadSanitizer: reported 5 warnings
 
Performing @selector(terminate:) from sender NSMenuItem 0x7b1c0001a240
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6ea2c32a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6eae8e60 pthread_kill + 430
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b1a33e wrap_pthread_kill + 302
3   libsystem_c.dylib             	0x00007fff6e9b3808 abort + 120
4   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b00806 __sanitizer::Abort() + 70
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111afff34 __sanitizer::Die() + 196
6   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b2f063 __tsan::finalize(void*) + 67
7   libsystem_c.dylib             	0x00007fff6e98e13c __cxa_finalize_ranges + 319
8   libsystem_c.dylib             	0x00007fff6e98e412 exit + 55
9   com.apple.AppKit              	0x00007fff321a3994 -[NSApplication terminate:] + 1749
10  com.apple.AppKit              	0x00007fff32118cf7 -[NSApplication(NSResponder) sendAction:to:from:] + 299
11  com.apple.AppKit              	0x00007fff3222878e -[NSMenuItem _corePerformAction] + 312
12  com.apple.AppKit              	0x00007fff3222850a -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 106
13  com.apple.AppKit              	0x00007fff32279098 -[NSMenu performActionForItemAtIndex:] + 114
14  com.apple.AppKit              	0x00007fff3227901d -[NSMenu _internalPerformActionForItemAtIndex:] + 82
15  com.apple.AppKit              	0x00007fff32278e67 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 101
16  com.apple.AppKit              	0x00007fff32209580 NSSLMMenuEventHandler + 908
17  com.apple.HIToolbox           	0x00007fff338668ef DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1254
18  com.apple.HIToolbox           	0x00007fff33865d7d SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 329
19  com.apple.HIToolbox           	0x00007fff3387b46e SendEventToEventTarget + 39
20  com.apple.HIToolbox           	0x00007fff338db3eb SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) + 368
21  com.apple.HIToolbox           	0x00007fff33902045 SendMenuCommandWithContextAndModifiers + 45
22  com.apple.HIToolbox           	0x00007fff33901fed SendMenuItemSelectedEvent + 346
23  com.apple.HIToolbox           	0x00007fff33901e39 FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) + 96
24  com.apple.HIToolbox           	0x00007fff3390286e MenuSelectCore(MenuData*, Point, double, unsigned int, OpaqueMenuRef**, unsigned short*) + 603
25  com.apple.HIToolbox           	0x00007fff33902578 _HandleMenuSelection2 + 460
26  com.apple.AppKit              	0x00007fff320ad15d _NSHandleCarbonMenuEvent + 215
27  com.apple.AppKit              	0x00007fff320acfca _DPSEventHandledByCarbon + 54
28  com.apple.AppKit              	0x00007fff31ed54ea -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2962
29  com.apple.AppKit              	0x00007fff31ec6bae -[NSApplication run] + 658
30  com.apple.AppKit              	0x00007fff31e98996 NSApplicationMain + 777
31  com.colliderli.iina           	0x000000010f285104 main + 36
32  libdyld.dylib                 	0x00007fff6e8e4cc9 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff6ea28746 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff6e9abeea nanosleep + 196
2   libsystem_c.dylib             	0x00007fff6e9abde4 usleep + 53
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b5258a __tsan::BackgroundThread(void*) + 474
4   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
5   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 2:: mpv/mpv core
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b17635 wrap_pthread_cond_timedwait + 549
4   libmpv.1.dylib                	0x0000000110225b79 mp_dispatch_queue_process + 345
5   libmpv.1.dylib                	0x0000000110261d48 mp_wait_events + 88
6   libmpv.1.dylib                	0x000000011023e311 mp_shutdown_clients + 113
7   libmpv.1.dylib                	0x000000011023e606 core_thread + 70
8   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
9   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
10  libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 3:: mpv/log-file
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b173ad wrap_pthread_cond_wait + 525
4   libmpv.1.dylib                	0x00000001101e732b log_file_thread + 75
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
6   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 4:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff6ea25e26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff684b6b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff684b69b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff684b67c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff684b61e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
6   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff6ea25e26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff684b6b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff684b69b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff684b67c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff684b61e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
6   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6ea25dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6ea26160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff34c63825 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff34c622f2 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff34c6176e CFRunLoopRunSpecific + 462
5   com.apple.AppKit              	0x00007fff32077ea4 _NSEventThread + 132
6   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
7   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 7:: LocalStorage
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b173ad wrap_pthread_cond_wait + 525
4   com.apple.JavaScriptCore      	0x00007fff393f6402 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 3858
5   com.apple.WebKitLegacy        	0x00007fff457c83f5 bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 165
6   com.apple.WebKitLegacy        	0x00007fff457cb5e1 std::__1::unique_ptr<WTF::Function<void ()>, std::__1::default_delete<WTF::Function<void ()> > > WTF::MessageQueue<WTF::Function<void ()> >::waitForMessageFilteredWithTimeout<WTF::MessageQueue<WTF::Function<void ()> >::waitForMessage()::'lambda'(WTF::Function<void ()> const&)>(WTF::MessageQueueWaitResult&, WTF::MessageQueue<WTF::Function<void ()> >::waitForMessage()::'lambda'(WTF::Function<void ()> const&)&&, WTF::Seconds) + 161
7   com.apple.WebKitLegacy        	0x00007fff457cad26 WebCore::StorageThread::threadEntryPoint() + 86
8   com.apple.JavaScriptCore      	0x00007fff39410e3f WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 223
9   com.apple.JavaScriptCore      	0x00007fff384ddbf9 WTF::wtfThreadEntryPoint(void*) + 9
10  libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
11  libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
12  libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6eae4b68 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff6eae4b68 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff6eae4b68 start_wqthread + 0

Thread 11:: Dispatch queue: com.colliderli.iina.controller
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b173ad wrap_pthread_cond_wait + 525
4   com.apple.Foundation          	0x00007fff372f094b -[NSOperation waitUntilFinished] + 697
5   com.apple.Foundation          	0x00007fff372d505b -[__NSObserver _doit:] + 239
6   com.apple.CoreFoundation      	0x00007fff34c5914f __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
7   com.apple.CoreFoundation      	0x00007fff34c590e3 ___CFXRegistrationPost1_block_invoke + 63
8   com.apple.CoreFoundation      	0x00007fff34c59058 _CFXRegistrationPost1 + 372
9   com.apple.CoreFoundation      	0x00007fff34c58cc4 ___CFXNotificationPost_block_invoke + 80
10  com.apple.CoreFoundation      	0x00007fff34c28e2d -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1554
11  com.apple.CoreFoundation      	0x00007fff34c282d9 _CFXNotificationPost + 1351
12  com.colliderli.iina           	0x000000010f546fdc PlayerCore.postNotification(_:) + 428
13  com.colliderli.iina           	0x000000010f5ade08 MPVController.handlePropertyChange(_:_:) + 36024
14  com.colliderli.iina           	0x000000010f5a06f3 MPVController.handleEvent(_:) + 6467
15  com.colliderli.iina           	0x000000010f59ed7c closure #1 in MPVController.readEvents() + 556
16  com.colliderli.iina           	0x000000010f5bf9fa partial apply for closure #1 in MPVController.readEvents() + 26
17  com.colliderli.iina           	0x000000010efa3753 thunk for @escaping @callee_guaranteed () -> () + 83
18  libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b62f0c __tsan::invoke_and_release_block(void*) + 12
19  libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b62c66 __tsan::dispatch_callback_wrap(void*) + 310
20  libdispatch.dylib             	0x00007fff6e88b658 _dispatch_client_callout + 8
21  libdispatch.dylib             	0x00007fff6e890c44 _dispatch_lane_serial_drain + 597
22  libdispatch.dylib             	0x00007fff6e8915d6 _dispatch_lane_invoke + 363
23  libdispatch.dylib             	0x00007fff6e89ac09 _dispatch_workloop_worker_thread + 596
24  libsystem_pthread.dylib       	0x00007fff6eae5a3d _pthread_wqthread + 290
25  libsystem_pthread.dylib       	0x00007fff6eae4b77 start_wqthread + 15

Thread 12:: mpv/worker
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b173ad wrap_pthread_cond_wait + 525
4   libmpv.1.dylib                	0x00000001102276fc worker_thread + 76
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
6   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000011a4f7dc0  rcx: 0x00007ffee0ca0a08  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee0ca0a30  rsp: 0x00007ffee0ca0a08
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x000000011a4f7dc0  r11: 0x0000000000000246
  r12: 0x0000000000000307  r13: 0x0000000000000000  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff6ea2c32a  rfl: 0x0000000000000246  cr2: 0x00001c4000004100
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
...
Truncated to not exceed GitHub limits...
```
</details>

<br>

**Steps to reproduce:**
- In Xcode 13.4 edit the scheme and enable:
  - Thread Sanitizer
  - Undefined Behavior Sanitizer
- Build IINA
- Take the application to a slow Mac running macOS 10.15.7
- Play a video
- Usually the thread sanitizer will detect issues

- [x] MPV does not have this problem.

This is an issue with IINA code.

**How often does this happen?**
Usually.

### LINKED ISSUE #3830: ThreadSanitizer: data race in PlaybackInfo.isSeeking.setter
**System and IINA version:**

- macOS 12.4
- IINA 1.3.0

**Expected behavior:**
IINA runs without error when built with the thread sanitizer enabled.

**Actual behavior:**
A debug version of IINA was built under Xcode 13.4 on a M1 MacBookPro18,2 with the thread sanitizer enabled. The resulting application was taken to a 2019 MacBookAir8,2 with an Intel chip running macOS 10.15.7. The thread sanitzer reported multiple data races and when IINA was quit the thread sanitizer triggered a crash. Will report separate issues for the different problems to isolate fixes. This issue is about this warning from the thread sanitizer:
```text
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x10011f5de) in PlaybackInfo.isSeeking.setter+0x5e
```

Multiple threads are accessing this `PlaybackInfo` property:
```swift
var isSeeking: Bool = false
```

The queue "com.colliderli.iina.controller" processes mpv events and directly sets `isSeeking`:
```swift
    case MPV_EVENT_SEEK:
      player.info.isSeeking = true
```

And from the main thread in `MainWindowController.updateNetworkState` which gets `isSeeking`:
```swift
  func updateNetworkState() {
    let needShowIndicator = player.info.pausedForCache || player.info.isSeeking
```

<details>
<summary><b>Crash report:</b></summary>

```text
Process:               IINA [29731]
Path:                  /Users/USER/Documents/*/IINA.app/Contents/MacOS/IINA
Identifier:            com.colliderli.iina
Version:               1.3.0 (131)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           IINA [29731]
User ID:               502

Date/Time:             2022-06-13 16:23:53.302 -0400
OS Version:            Mac OS X 10.15.7 (19H1824)
Report Version:        12
Bridge OS Version:     6.4 (19P4242)
Anonymous UUID:        954A8385-28AB-9AF4-B895-3C24A2049280

Sleep/Wake UUID:       A633279D-633B-4221-B425-065C8C33019F

Time Awake Since Boot: 89000 seconds
Time Since Wake:       1600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Write of size 1 at 0x7b10000f22b8 by main thread:
    #0 ViewLayer.needsMPVRender.setter <null>:2 (IINA:x86_64+0x1004bd54a)
    #1 ViewLayer.draw(forced:) <null>:2 (IINA:x86_64+0x1004c20fc)
    #2 MainWindowController.windowWillOpen() <null>:2 (IINA:x86_64+0x10023ab40)
    #3 PlayerCore.openMainWindow(path:url:isNetwork:) <null>:2 (IINA:x86_64+0x1005a4c4b)
    #4 PlayerCore.open(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a1894)
    #5 PlayerCore.openURLs(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2480)
    #6 PlayerCore.openURL(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2d25)
    #7 OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x1004962d7)
    #8 @objc OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x10049654f)
    #9 -[NSApplication(NSResponder) sendAction:to:from:] <null>:2 (AppKit:x86_64+0x283cf6)
    #10 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Previous write of size 1 at 0x7b10000f22b8 by thread T21 (mutexes: write M386038120195514024):
    #0 ViewLayer.needsMPVRender.setter <null>:2 (IINA:x86_64+0x1004bd54a)
    #1 ViewLayer.draw(forced:) <null>:2 (IINA:x86_64+0x1004c2be9)
    #2 closure #1 in mpvUpdateCallback(_:) <null>:2 (IINA:x86_64+0x10065af0d)
    #3 partial apply for closure #1 in mpvUpdateCallback(_:) <null>:2 (IINA:x86_64+0x1006621b9)
    #4 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #5 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #6 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Location is heap block of size 64 at 0x7b10000f2280 allocated by main thread:
    #0 calloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x534a4)
    #1 _objc_rootAllocWithZone <null>:3 (libobjc.A.dylib:x86_64h+0x10804)
    #2 closure #1 in VideoView.videoLayer.getter <null>:2 (IINA:x86_64+0x1004de007)
    #3 VideoView.videoLayer.getter <null>:2 (IINA:x86_64+0x1004ddebf)
    #4 VideoView.init(frame:) <null>:2 (IINA:x86_64+0x1004e1593)
    #5 @objc VideoView.init(frame:) <null>:2 (IINA:x86_64+0x1004e1e05)
    #6 VideoView.__allocating_init(frame:player:) <null>:2 (IINA:x86_64+0x1004e1f53)
    #7 MainWindowController._videoView.getter <null>:2 (IINA:x86_64+0x1001f4251)
    #8 MainWindowController.videoView.getter <null>:2 (IINA:x86_64+0x1001f3e39)
    #9 MainWindowController.addVideoViewToWindow() <null>:2 (IINA:x86_64+0x1002258b1)
    #10 MainWindowController.windowDidLoad() <null>:2 (IINA:x86_64+0x100221307)
    #11 @objc MainWindowController.windowDidLoad() <null>:2 (IINA:x86_64+0x1002245a1)
    #12 -[NSWindowController _windowDidLoad] <null>:2 (AppKit:x86_64+0x23a72d)
    #13 PlayerCore.open(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a1894)
    #14 PlayerCore.openURLs(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2480)
    #15 PlayerCore.openURL(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2d25)
    #16 OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x1004962d7)
    #17 @objc OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x10049654f)
    #18 -[NSApplication(NSResponder) sendAction:to:from:] <null>:2 (AppKit:x86_64+0x283cf6)
    #19 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Mutex M386038120195514024 is already destroyed.
 
  Thread T21 (tid=955443, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x1004bd54a) in ViewLayer.needsMPVRender.setter+0x8a
==================
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Read of size 8 at 0x7b0800013d90 by thread T26:
    #0 VideoTime.second.getter <null>:2 (IINA:x86_64+0x10015a2ba)
    #1 PlayerCore.fileLoaded() <null>:2 (IINA:x86_64+0x1005d29b8)
    #2 MPVController.onFileLoaded() <null>:2 (IINA:x86_64+0x100645d59)
    #3 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x1006432a8)
    #4 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #5 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #6 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #7 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #8 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Previous write of size 8 at 0x7b0800013d90 by main thread:
    #0 VideoTime.second.setter <null>:2 (IINA:x86_64+0x10015a31f)
    #1 PlayerCore.syncUI(_:) <null>:2 (IINA:x86_64+0x1005db14d)
    #2 PlayerCore.syncUITime() <null>:2 (IINA:x86_64+0x1005d8c9c)
    #3 @objc PlayerCore.syncUITime() <null>:2 (IINA:x86_64+0x1005d9641)
    #4 __NSFireTimer <null>:2 (Foundation:x86_64+0xbed69)
    #5 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Location is heap block of size 24 at 0x7b0800013d80 allocated by thread T26:
    #0 malloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x532ec)
    #1 swift_slowAlloc <null>:2 (libswiftCore.dylib:x86_64+0x2f2ca8)
    #2 MPVController.onFileLoaded() <null>:2 (IINA:x86_64+0x100645940)
    #3 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x1006432a8)
    #4 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #5 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #6 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #7 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #8 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Thread T26 (tid=955714, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x10015a2ba) in VideoTime.second.getter+0x3a
==================
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Write of size 8 at 0x7b0800013ab0 by thread T26:
    #0 VideoTime.second.setter <null>:2 (IINA:x86_64+0x10015a31f)
    #1 PlayerCore.syncUI(_:) <null>:2 (IINA:x86_64+0x1005d9f67)
    #2 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x10064358c)
    #3 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #4 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #5 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #6 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #7 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Previous write of size 8 at 0x7b0800013ab0 by main thread:
    #0 VideoTime.second.setter <null>:2 (IINA:x86_64+0x10015a31f)
    #1 PlayerCore.syncUI(_:) <null>:2 (IINA:x86_64+0x1005dae27)
    #2 PlayerCore.syncUITime() <null>:2 (IINA:x86_64+0x1005d8c9c)
    #3 @objc PlayerCore.syncUITime() <null>:2 (IINA:x86_64+0x1005d9641)
    #4 __NSFireTimer <null>:2 (Foundation:x86_64+0xbed69)
    #5 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Location is heap block of size 24 at 0x7b0800013aa0 allocated by thread T26:
    #0 malloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x532ec)
    #1 swift_slowAlloc <null>:2 (libswiftCore.dylib:x86_64+0x2f2ca8)
    #2 MPVController.onFileLoaded() <null>:2 (IINA:x86_64+0x100645c7c)
    #3 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x1006432a8)
    #4 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #5 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #6 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #7 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #8 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Thread T26 (tid=955714, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x10015a31f) in VideoTime.second.setter+0x3f
==================
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Write of size 1 at 0x7b540000c3a8 by thread T22:
    #0 PlaybackInfo.isSeeking.setter <null>:2 (IINA:x86_64+0x10011f5de)
    #1 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x10064427e)
    #2 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #3 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #4 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #5 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #6 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Previous read of size 1 at 0x7b540000c3a8 by main thread:
    #0 PlaybackInfo.isSeeking.getter <null>:2 (IINA:x86_64+0x10011f550)
    #1 MainWindowController.updateNetworkState() <null>:2 (IINA:x86_64+0x10027538e)
    #2 $s4IINA10PlayerCoreC6syncUIyyAC12SyncUIOptionOFyyScMYccfU0_ <null>:2 (IINA:x86_64+0x1005ddbd6)
    #3 $s4IINA10PlayerCoreC6syncUIyyAC12SyncUIOptionOFyyScMYccfU0_TA <null>:2 (IINA:x86_64+0x1005f4ce9)
    #4 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #5 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #6 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
    #7 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Location is heap block of size 616 at 0x7b540000c300 allocated by main thread:
    #0 malloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x532ec)
    #1 swift_slowAlloc <null>:2 (libswiftCore.dylib:x86_64+0x2f2ca8)
    #2 PlayerCore.info.getter <null>:2 (IINA:x86_64+0x10059d049)
    #3 MPVController.mpvInit() <null>:2 (IINA:x86_64+0x1006295a0)
    #4 PlayerCore.startMPV() <null>:2 (IINA:x86_64+0x1005a89cb)
    #5 static PlayerCore.createPlayerCore() <null>:2 (IINA:x86_64+0x1005980cb)
    #6 $s4IINA10PlayerCoreC5first_WZ <null>:2 (IINA:x86_64+0x100597cc3)
    #7 dispatch_once <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x78be3)
    #8 dispatch_once_f <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x78ccb)
    #9 swift_once <null>:2 (libswiftCore.dylib:x86_64+0x31a839)
    #10 static PlayerCore.active.getter <null>:2 (IINA:x86_64+0x1005986fe)
    #11 AppDelegate.applicationDidFinishLaunching(_:) <null>:2 (IINA:x86_64+0x1003149ec)
    #12 @objc AppDelegate.applicationDidFinishLaunching(_:) <null>:2 (IINA:x86_64+0x100318e66)
    #13 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ <null>:3 (CoreFoundation:x86_64h+0x7a14e)
    #14 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Thread T22 (tid=955442, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x10011f5de) in PlaybackInfo.isSeeking.setter+0x5e
==================
==================
WARNING: ThreadSanitizer: data race (pid=29731)
  Read of size 1 at 0x7b10000f22b9 by thread T40 (mutexes: write M386038120195514024):
    #0 ViewLayer.forceRender.getter <null>:2 (IINA:x86_64+0x1004bd6d8)
    #1 ViewLayer.canDraw(inCGLContext:pixelFormat:forLayerTime:displayTime:) <null>:2 (IINA:x86_64+0x1004bf7fc)
    #2 @objc ViewLayer.canDraw(inCGLContext:pixelFormat:forLayerTime:displayTime:) <null>:2 (IINA:x86_64+0x1004bfc23)
    #3 CAOpenGLLayerDraw(CAOpenGLLayer*, double, CVTimeStamp const*, unsigned int) <null>:2 (QuartzCore:x86_64+0xc1fce)
    #4 @objc ViewLayer.display() <null>:2 (IINA:x86_64+0x1004c3641)
    #5 ViewLayer.draw(forced:) <null>:2 (IINA:x86_64+0x1004c2147)
    #6 closure #1 in mpvUpdateCallback(_:) <null>:2 (IINA:x86_64+0x10065af0d)
    #7 partial apply for closure #1 in mpvUpdateCallback(_:) <null>:2 (IINA:x86_64+0x1006621b9)
    #8 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #9 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #10 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Previous write of size 1 at 0x7b10000f22b9 by thread T22:
    #0 ViewLayer.forceRender.setter <null>:2 (IINA:x86_64+0x1004bd78a)
    #1 ViewLayer.draw(forced:) <null>:2 (IINA:x86_64+0x1004c211d)
    #2 PlayerCore.playbackRestarted() <null>:2 (IINA:x86_64+0x1005d40aa)
    #3 MPVController.handleEvent(_:) <null>:2 (IINA:x86_64+0x100644594)
    #4 closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x100640d7b)
    #5 partial apply for closure #1 in MPVController.readEvents() <null>:2 (IINA:x86_64+0x1006619f9)
    #6 thunk for @escaping @callee_guaranteed () -> () <null>:2 (IINA:x86_64+0x100045752)
    #7 __tsan::invoke_and_release_block(void*) <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x77f0b)
    #8 _dispatch_client_callout <null>:2 (libdispatch.dylib:x86_64+0x2657)
 
  Location is heap block of size 64 at 0x7b10000f2280 allocated by main thread:
    #0 calloc <null>:3 (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x534a4)
    #1 _objc_rootAllocWithZone <null>:3 (libobjc.A.dylib:x86_64h+0x10804)
    #2 closure #1 in VideoView.videoLayer.getter <null>:2 (IINA:x86_64+0x1004de007)
    #3 VideoView.videoLayer.getter <null>:2 (IINA:x86_64+0x1004ddebf)
    #4 VideoView.init(frame:) <null>:2 (IINA:x86_64+0x1004e1593)
    #5 @objc VideoView.init(frame:) <null>:2 (IINA:x86_64+0x1004e1e05)
    #6 VideoView.__allocating_init(frame:player:) <null>:2 (IINA:x86_64+0x1004e1f53)
    #7 MainWindowController._videoView.getter <null>:2 (IINA:x86_64+0x1001f4251)
    #8 MainWindowController.videoView.getter <null>:2 (IINA:x86_64+0x1001f3e39)
    #9 MainWindowController.addVideoViewToWindow() <null>:2 (IINA:x86_64+0x1002258b1)
    #10 MainWindowController.windowDidLoad() <null>:2 (IINA:x86_64+0x100221307)
    #11 @objc MainWindowController.windowDidLoad() <null>:2 (IINA:x86_64+0x1002245a1)
    #12 -[NSWindowController _windowDidLoad] <null>:2 (AppKit:x86_64+0x23a72d)
    #13 PlayerCore.open(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a1894)
    #14 PlayerCore.openURLs(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2480)
    #15 PlayerCore.openURL(_:shouldAutoLoad:) <null>:2 (IINA:x86_64+0x1005a2d25)
    #16 OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x1004962d7)
    #17 @objc OpenURLWindowController.openBtnAction(_:) <null>:2 (IINA:x86_64+0x10049654f)
    #18 -[NSApplication(NSResponder) sendAction:to:from:] <null>:2 (AppKit:x86_64+0x283cf6)
    #19 start <null>:2 (libdyld.dylib:x86_64+0x1acc8)
 
  Mutex M386038120195514024 is already destroyed.
 
  Thread T40 (tid=955817, running) is a GCD worker thread
 
  Thread T22 (tid=955442, running) is a GCD worker thread
 
SUMMARY: ThreadSanitizer: data race (IINA:x86_64+0x1004bd6d8) in ViewLayer.forceRender.getter+0x68
==================
ThreadSanitizer: reported 5 warnings
 
Performing @selector(terminate:) from sender NSMenuItem 0x7b1c0001a240
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6ea2c32a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6eae8e60 pthread_kill + 430
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b1a33e wrap_pthread_kill + 302
3   libsystem_c.dylib             	0x00007fff6e9b3808 abort + 120
4   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b00806 __sanitizer::Abort() + 70
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111afff34 __sanitizer::Die() + 196
6   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b2f063 __tsan::finalize(void*) + 67
7   libsystem_c.dylib             	0x00007fff6e98e13c __cxa_finalize_ranges + 319
8   libsystem_c.dylib             	0x00007fff6e98e412 exit + 55
9   com.apple.AppKit              	0x00007fff321a3994 -[NSApplication terminate:] + 1749
10  com.apple.AppKit              	0x00007fff32118cf7 -[NSApplication(NSResponder) sendAction:to:from:] + 299
11  com.apple.AppKit              	0x00007fff3222878e -[NSMenuItem _corePerformAction] + 312
12  com.apple.AppKit              	0x00007fff3222850a -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 106
13  com.apple.AppKit              	0x00007fff32279098 -[NSMenu performActionForItemAtIndex:] + 114
14  com.apple.AppKit              	0x00007fff3227901d -[NSMenu _internalPerformActionForItemAtIndex:] + 82
15  com.apple.AppKit              	0x00007fff32278e67 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 101
16  com.apple.AppKit              	0x00007fff32209580 NSSLMMenuEventHandler + 908
17  com.apple.HIToolbox           	0x00007fff338668ef DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1254
18  com.apple.HIToolbox           	0x00007fff33865d7d SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 329
19  com.apple.HIToolbox           	0x00007fff3387b46e SendEventToEventTarget + 39
20  com.apple.HIToolbox           	0x00007fff338db3eb SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) + 368
21  com.apple.HIToolbox           	0x00007fff33902045 SendMenuCommandWithContextAndModifiers + 45
22  com.apple.HIToolbox           	0x00007fff33901fed SendMenuItemSelectedEvent + 346
23  com.apple.HIToolbox           	0x00007fff33901e39 FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) + 96
24  com.apple.HIToolbox           	0x00007fff3390286e MenuSelectCore(MenuData*, Point, double, unsigned int, OpaqueMenuRef**, unsigned short*) + 603
25  com.apple.HIToolbox           	0x00007fff33902578 _HandleMenuSelection2 + 460
26  com.apple.AppKit              	0x00007fff320ad15d _NSHandleCarbonMenuEvent + 215
27  com.apple.AppKit              	0x00007fff320acfca _DPSEventHandledByCarbon + 54
28  com.apple.AppKit              	0x00007fff31ed54ea -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2962
29  com.apple.AppKit              	0x00007fff31ec6bae -[NSApplication run] + 658
30  com.apple.AppKit              	0x00007fff31e98996 NSApplicationMain + 777
31  com.colliderli.iina           	0x000000010f285104 main + 36
32  libdyld.dylib                 	0x00007fff6e8e4cc9 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff6ea28746 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff6e9abeea nanosleep + 196
2   libsystem_c.dylib             	0x00007fff6e9abde4 usleep + 53
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b5258a __tsan::BackgroundThread(void*) + 474
4   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
5   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 2:: mpv/mpv core
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b17635 wrap_pthread_cond_timedwait + 549
4   libmpv.1.dylib                	0x0000000110225b79 mp_dispatch_queue_process + 345
5   libmpv.1.dylib                	0x0000000110261d48 mp_wait_events + 88
6   libmpv.1.dylib                	0x000000011023e311 mp_shutdown_clients + 113
7   libmpv.1.dylib                	0x000000011023e606 core_thread + 70
8   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
9   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
10  libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 3:: mpv/log-file
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b173ad wrap_pthread_cond_wait + 525
4   libmpv.1.dylib                	0x00000001101e732b log_file_thread + 75
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
6   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 4:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff6ea25e26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff684b6b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff684b69b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff684b67c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff684b61e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
6   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff6ea25e26 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff684b6b16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff684b69b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff684b67c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff684b61e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
6   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff6ea25dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff6ea26160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff34c63825 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff34c622f2 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff34c6176e CFRunLoopRunSpecific + 462
5   com.apple.AppKit              	0x00007fff32077ea4 _NSEventThread + 132
6   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
7   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
8   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 7:: LocalStorage
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b173ad wrap_pthread_cond_wait + 525
4   com.apple.JavaScriptCore      	0x00007fff393f6402 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 3858
5   com.apple.WebKitLegacy        	0x00007fff457c83f5 bool WTF::Condition::waitUntil<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 165
6   com.apple.WebKitLegacy        	0x00007fff457cb5e1 std::__1::unique_ptr<WTF::Function<void ()>, std::__1::default_delete<WTF::Function<void ()> > > WTF::MessageQueue<WTF::Function<void ()> >::waitForMessageFilteredWithTimeout<WTF::MessageQueue<WTF::Function<void ()> >::waitForMessage()::'lambda'(WTF::Function<void ()> const&)>(WTF::MessageQueueWaitResult&, WTF::MessageQueue<WTF::Function<void ()> >::waitForMessage()::'lambda'(WTF::Function<void ()> const&)&&, WTF::Seconds) + 161
7   com.apple.WebKitLegacy        	0x00007fff457cad26 WebCore::StorageThread::threadEntryPoint() + 86
8   com.apple.JavaScriptCore      	0x00007fff39410e3f WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 223
9   com.apple.JavaScriptCore      	0x00007fff384ddbf9 WTF::wtfThreadEntryPoint(void*) + 9
10  libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
11  libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
12  libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff6eae4b68 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff6eae4b68 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	0x00007fff6eae4b68 start_wqthread + 0

Thread 11:: Dispatch queue: com.colliderli.iina.controller
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b173ad wrap_pthread_cond_wait + 525
4   com.apple.Foundation          	0x00007fff372f094b -[NSOperation waitUntilFinished] + 697
5   com.apple.Foundation          	0x00007fff372d505b -[__NSObserver _doit:] + 239
6   com.apple.CoreFoundation      	0x00007fff34c5914f __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
7   com.apple.CoreFoundation      	0x00007fff34c590e3 ___CFXRegistrationPost1_block_invoke + 63
8   com.apple.CoreFoundation      	0x00007fff34c59058 _CFXRegistrationPost1 + 372
9   com.apple.CoreFoundation      	0x00007fff34c58cc4 ___CFXNotificationPost_block_invoke + 80
10  com.apple.CoreFoundation      	0x00007fff34c28e2d -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1554
11  com.apple.CoreFoundation      	0x00007fff34c282d9 _CFXNotificationPost + 1351
12  com.colliderli.iina           	0x000000010f546fdc PlayerCore.postNotification(_:) + 428
13  com.colliderli.iina           	0x000000010f5ade08 MPVController.handlePropertyChange(_:_:) + 36024
14  com.colliderli.iina           	0x000000010f5a06f3 MPVController.handleEvent(_:) + 6467
15  com.colliderli.iina           	0x000000010f59ed7c closure #1 in MPVController.readEvents() + 556
16  com.colliderli.iina           	0x000000010f5bf9fa partial apply for closure #1 in MPVController.readEvents() + 26
17  com.colliderli.iina           	0x000000010efa3753 thunk for @escaping @callee_guaranteed () -> () + 83
18  libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b62f0c __tsan::invoke_and_release_block(void*) + 12
19  libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b62c66 __tsan::dispatch_callback_wrap(void*) + 310
20  libdispatch.dylib             	0x00007fff6e88b658 _dispatch_client_callout + 8
21  libdispatch.dylib             	0x00007fff6e890c44 _dispatch_lane_serial_drain + 597
22  libdispatch.dylib             	0x00007fff6e8915d6 _dispatch_lane_invoke + 363
23  libdispatch.dylib             	0x00007fff6e89ac09 _dispatch_workloop_worker_thread + 596
24  libsystem_pthread.dylib       	0x00007fff6eae5a3d _pthread_wqthread + 290
25  libsystem_pthread.dylib       	0x00007fff6eae4b77 start_wqthread + 15

Thread 12:: mpv/worker
0   libsystem_kernel.dylib        	0x00007fff6ea28872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6eae9425 _pthread_cond_wait + 698
2   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b6249e __tsan::call_pthread_cancel_with_cleanup(int (*)(void*), void (*)(void*), void*) + 62
3   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b173ad wrap_pthread_cond_wait + 525
4   libmpv.1.dylib                	0x00000001102276fc worker_thread + 76
5   libclang_rt.tsan_osx_dynamic.dylib	0x0000000111b16b0d __tsan_thread_start_func + 141
6   libsystem_pthread.dylib       	0x00007fff6eae9109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff6eae4b8b thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000011a4f7dc0  rcx: 0x00007ffee0ca0a08  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee0ca0a30  rsp: 0x00007ffee0ca0a08
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x000000011a4f7dc0  r11: 0x0000000000000246
  r12: 0x0000000000000307  r13: 0x0000000000000000  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff6ea2c32a  rfl: 0x0000000000000246  cr2: 0x00001c4000004100
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
...
Truncated to not exceed GitHub limits...
```
</details>

<br>

**Steps to reproduce:**
- In Xcode 13.4 edit the scheme and enable:
  - Thread Sanitizer
  - Undefined Behavior Sanitizer
- Build IINA
- Take the application to a slow Mac running macOS 10.15.7
- Play a video
- Usually the thread sanitizer will detect issues

- [x] MPV does not have this problem.

This is definitely an IINA issue.

**How often does this happen?**
Usually.

### LINKED ISSUE #3936: ThreadSanitizer: data race in PlaybackInfo.disableOSDForFileLoading.setter
**System and IINA version:**

- macOS 12.5.1
- IINA 1.3.0 debug build

**Expected behavior:**
IINA runs without error when built with the thread sanitizer enabled.

**Actual behavior:**
Running on a M1 MacBookPro18,2  under macOS 12.5.1 with a build generated by Xcode 13.4.1 using the thread sanitizer, the thread sanitizer reports a data race:
```text
SUMMARY: ThreadSanitizer: data race <compiler-generated> in PlaybackInfo.disableOSDForFileLoading.setter
```

Multiple threads are accessing this `PlaybackInfo` property:
```swift
var disableOSDForFileLoading: Bool = false
```

<details>
<summary>Xcode Console</summary>

```text
==================
ThreadSanitizer report breakpoint hit. Use 'thread info -s' to get extended information about the report.
17:09:05.075 [player0][d] Track list changed
==================
WARNING: ThreadSanitizer: data race (pid=81983)
  Write of size 1 at 0x00010f112f2f by main thread:
    #0 PlaybackInfo.disableOSDForFileLoading.setter <compiler-generated> (IINA:arm64+0x10010fbc8)
    #1 PlayerCore.reEnableOSDAfterFileLoading() PlayerCore.swift:1340 (IINA:arm64+0x1005778b0)
    #2 @objc PlayerCore.reEnableOSDAfterFileLoading() <compiler-generated> (IINA:arm64+0x100577924)
    #3 __NSFireTimer <null>:96138564 (Foundation:arm64e+0xa691c)
    #4 start <null>:96138564 (dyld:arm64e+0x5088)

  Previous read of size 1 at 0x00010f112f2f by thread T5:
    #0 PlaybackInfo.disableOSDForFileLoading.getter <compiler-generated> (IINA:arm64+0x10010fb2c)
    #1 PlayerCore.sendOSD(_:autoHide:forcedTimeout:accessoryView:context:) PlayerCore.swift:1539 (IINA:arm64+0x10057fce4)
    #2 MPVController.handlePropertyChange(_:_:) MPVController.swift:994 (IINA:arm64+0x1005deb0c)
    #3 MPVController.handleEvent(_:) MPVController.swift:825 (IINA:arm64+0x1005d8bf8)
    #4 closure #1 in MPVController.readEvents() MPVController.swift:765 (IINA:arm64+0x1005d75a8)
    #5 partial apply for closure #1 in MPVController.readEvents() <compiler-generated> (IINA:arm64+0x1005f1bfc)
    #6 thunk for @escaping @callee_guaranteed () -> () <compiler-generated> (IINA:arm64+0x10003e738)
    #7 __tsan::invoke_and_release_block(void*) <null>:96138564 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7c808)
    #8 _dispatch_client_callout <null>:96138564 (libdispatch.dylib:arm64e+0x63a4)

  Location is heap block of size 616 at 0x00010f112e80 allocated by main thread:
    #0 __sanitizer_mz_malloc <null>:96138564 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x59814)
    #1 _malloc_zone_malloc <null>:96138564 (libsystem_malloc.dylib:arm64e+0x1e744)
    #2 PlayerCore.info.getter PlayerCore.swift:121 (IINA:arm64+0x100543a34)
    #3 MPVController.mpvInit() MPVController.swift:244 (IINA:arm64+0x1005c389c)
    #4 PlayerCore.startMPV() PlayerCore.swift:319 (IINA:arm64+0x10054f0c4)
    #5 static PlayerCore.createPlayerCore() PlayerCore.swift:68 (IINA:arm64+0x10053eb00)
    #6 one-time initialization function for first PlayerCore.swift:17 (IINA:arm64+0x10053e780)
    #7 dispatch_once <null>:96138564 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7d708)
    #8 dispatch_once_f <null>:96138564 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7d818)
    #9 PlayerCore.first.unsafeMutableAddressor PlayerCore.swift:17 (IINA:arm64+0x10053ec24)
    #10 static PlayerCore.active.getter PlayerCore.swift:34 (IINA:arm64+0x10053f188)
    #11 AppDelegate.applicationDidFinishLaunching(_:) AppDelegate.swift:183 (IINA:arm64+0x1002d9364)
    #12 @objc AppDelegate.applicationDidFinishLaunching(_:) <compiler-generated> (IINA:arm64+0x1002dc56c)
    #13 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ <null>:96138564 (CoreFoundation:arm64e+0x79518)
    #14 start <null>:96138564 (dyld:arm64e+0x5088)

  Thread T5 (tid=4123361, running) is a GCD worker thread

SUMMARY: ThreadSanitizer: data race <compiler-generated> in PlaybackInfo.disableOSDForFileLoading.setter
==================
```
</details>

<br>

**Steps to reproduce:**
- In Xcode edit the scheme and enable:
  - Thread Sanitizer
  - Undefined Behavior Sanitizer
- Build and run IINA
- Play a video
- Maybe the issue will be detected

- [x] MPV does not have this problem.

This is an issue with IINA code.

**How often does this happen?**
Sometimes.

### LINKED ISSUE #3937: ThreadSanitizer: data race in MainWindowController.rotation.setter
**System and IINA version:**

- macOS 12.5.1
- IINA 1.3.0 debug build

**Expected behavior:**
IINA runs without error when built with the thread sanitizer enabled.

**Actual behavior:**
Running on a M1 MacBookPro18,2  under macOS 12.5.1 with a build generated by Xcode 13.4.1 with the thread sanitizer enabled the thread sanitizer reports a data race:
```text
SUMMARY: ThreadSanitizer: data race MainWindowController.swift in MainWindowController.rotation.setter
```

Multiple threads are accessing this `MainWindowController` property:
```swift
lazy var rotation: Int = {
  return player.mpv.getInt(MPVProperty.videoParamsRotate)
}()
```

<details>
<summary>Xcode Console</summary>

```text
=================
ThreadSanitizer report breakpoint hit. Use 'thread info -s' to get extended information about the report.
==================
WARNING: ThreadSanitizer: data race (pid=98475)
  Write of size 1 at 0x00010f416460 by thread T1:
    #0 MainWindowController.rotation.setter MainWindowController.swift (IINA:arm64+0x1001d9c68)
    #1 MPVController.handlePropertyChange(_:_:) MPVController.swift:965 (IINA:arm64+0x1005e09e4)
    #2 MPVController.handleEvent(_:) MPVController.swift:830 (IINA:arm64+0x1005dc578)
    #3 closure #1 in MPVController.readEvents() MPVController.swift:765 (IINA:arm64+0x1005daeb8)
    #4 partial apply for closure #1 in MPVController.readEvents() <compiler-generated> (IINA:arm64+0x1005f5584)
    #5 thunk for @escaping @callee_guaranteed () -> () <compiler-generated> (IINA:arm64+0x100040c84)
    #6 __tsan::invoke_and_release_block(void*) <null>:97269060 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7c808)
    #7 _dispatch_client_callout <null>:97269060 (libdispatch.dylib:arm64e+0x63a4)

  Previous read of size 1 at 0x00010f416460 by main thread:
    #0 MainWindowController.rotation.getter MainWindowController.swift (IINA:arm64+0x1001d984c)
    #1 MainWindowController.updateTimeLabel(_:originalPos:) MainWindowController.swift:2079 (IINA:arm64+0x10023f5ec)
    #2 MainWindowController.mouseExited(with:) MainWindowController.swift:949 (IINA:arm64+0x100213d8c)
    #3 @objc MainWindowController.mouseExited(with:) <compiler-generated> (IINA:arm64+0x100213fe0)
    #4 -[NSTrackingArea _dispatchMouseExited:] <null>:97269060 (AppKit:arm64e+0x239a04)
    #5 start <null>:97269060 (dyld:arm64e+0x5088)

  Location is heap block of size 1104 at 0x00010f416300 allocated by main thread:
    #0 calloc <null>:97269060 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x59514)
    #1 _objc_rootAllocWithZone <null>:97269060 (libobjc.A.dylib:arm64e+0xc8b4)
    #2 PlayerCore.init() PlayerCore.swift:158 (IINA:arm64+0x10054bbd8)
    #3 @objc PlayerCore.init() <compiler-generated> (IINA:arm64+0x10054c024)
    #4 PlayerCore.__allocating_init() PlayerCore.swift (IINA:arm64+0x100543a7c)
    #5 static PlayerCore.createPlayerCore() PlayerCore.swift:65 (IINA:arm64+0x100542154)
    #6 one-time initialization function for first PlayerCore.swift:17 (IINA:arm64+0x100542090)
    #7 dispatch_once <null>:97269060 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7d708)
    #8 dispatch_once_f <null>:97269060 (libclang_rt.tsan_osx_dynamic.dylib:arm64e+0x7d818)
    #9 PlayerCore.first.unsafeMutableAddressor PlayerCore.swift:17 (IINA:arm64+0x100542534)
    #10 static PlayerCore.active.getter PlayerCore.swift:34 (IINA:arm64+0x100542a98)
    #11 AppDelegate.applicationDidFinishLaunching(_:) AppDelegate.swift:183 (IINA:arm64+0x1002db8b0)
    #12 @objc AppDelegate.applicationDidFinishLaunching(_:) <compiler-generated> (IINA:arm64+0x1002deab8)
    #13 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ <null>:97269060 (CoreFoundation:arm64e+0x79518)
    #14 start <null>:97269060 (dyld:arm64e+0x5088)

  Thread T1 (tid=4314678, running) is a GCD worker thread

SUMMARY: ThreadSanitizer: data race MainWindowController.swift in MainWindowController.rotation.setter
==================
```
</details>

<br>

**Steps to reproduce:**
- In Xcode edit the scheme and enable:
  - Thread Sanitizer
  - Undefined Behavior Sanitizer
- Build and run IINA
- Play a video
- Maybe the issue will be detected

- [x] MPV does not have this problem.

This is an issue with IINA code.

**How often does this happen?**
Rarely.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Change `MPVController` to perform most event processing using the main thread
- Remove dispatching to main queue from `PlayerCore` methods now being called by `MPVController` using the main thread
- Add the `Atomic` property wrapper to the `playlistTotalLength` and `playlistTotalLengthIsReady` `PlaylistViewController` properties
- Add the `Atomic` property wrapper to the following `PlayerInfo` properties:
  - aid
  - secondSid
  - sid
   - subTracks
  - thumbnails
  - thumbnailsProgress
  - thumbnailsReady
  - vid
- Change references to `subTracks` to lock the array
- Change references to `thumbnails` to lock the array
- Add the `Atomic` property wrapper to the `hooks` `MPVController` property
- Change references to `hooks` to lock the array
- Change `PlayerCore.playbackRestarted` to re-enable the OSD by dispatching to the main thread using `async` with a delay instead of using a timer
- Add the method `logPropertyValueError` to `MPVController` to report when property values can not be converted to the expected type
- Replace `MPVController` method `reEnableOSDAfterFileLoading` with inline code

These changes will correct data races between the  main thread and the thread for the `MPVController` `com.colliderli.iina.controller` queue by changing `MPVController` to dispatch work to the main queue. This will simplify the code as in some cases work was being done on both the `controller` queue and the main queue as some processing required calling AppKit methods that must be run on the main thread.

These changes will correct the data races between the main thread and PlayerCore backgroundQueue used for loading subtitles by adding the `Atomic` property wrapper to properties shared between these threads and using the `withLock` method. Similar changes correct the data races between the main thread and PlayerCore thumbnailQueue.

These changes will also fix data races with the `playlistTotalLengthIsReady` and `playlistTotalLength` properties.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #3829, #3830, #3936, #3937.

---

**Description:**

### CODE REVIEW

**Comment by low-batt** [comment]
Been waiting for a release that includes beta testing to make these significant changes. Lots here for reviewers to criticize.

Before the changes in this PR `MPVController` performed many operations using its `com.colliderli.iina.controller` queue. Some operations were partially performed on that queue and then dispatched using `DispatchQueue.main.sync` due to needing to call AppKit methods that can only be called using the main thread. In the documentation for [DispatchQueue](https://developer.apple.com/documentation/dispatch/dispatchqueue) Apple says:
> **Important**
> Attempting to synchronously execute a work item on the main queue results in deadlock.

So we should be careful about using `DispatchQueue.main.sync` . I'm assuming [sync](https://developer.apple.com/documentation/dispatch/dispatchqueue/2016083-sync) was chosen in an attempt to keep the data modified while running in the `controller` queue consistent with the data modified while running on the main thread?

Rather than add locks around lots of properties this PR changes `MPVController` to dispatch most work using  `DispatchQueue.main.async` so that only one thread is accessing the data and locks are not needed. For other situations where we really do need processing to occur in the background locks are used.

Does anyone know why the re-enabling of the OSD which is disabled until after file loading is not re-enabled in the `fileLoaded` method and instead is done in `playbackRestarted` and involves a `0.2` second delay?

As `mpv` is forcing us to raise the minimum supported macOS version to 10.15, another possibility would be to put data shared between threads into [Actors](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/#Actors). As we already have too much work to do for 1.4.0, I thought it would be better solve the data races using our current techniques and consider making use of [Swift Concurrency](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/) in a future release.

**Comment by svobs** [comment]
> So we should be careful about using DispatchQueue.main.sync . I'm assuming sync was chosen in an attempt to keep the data modified while running in the controller queue consistent with the data modified while running on the main thread?

I'm a lot more doubtful about the need for `DispatchQueue.main.sync`. On my fork I did a bunch of refactoring to ensure that `com.colliderli.iina.controller` was used for all libmpv API calls, and just replaced a few of the syncs with async. No major hiccups to report.

Are you familiar with `dispatchPrecondition(condition: .onQueue(DispatchQueue.main))` for indicating / enforcing which execution queue a given method is running from? Would highly recommend for reducing bugs / increasing sanity.

> Does anyone know why the re-enabling of the OSD which is disabled until after file loading is not re-enabled in the fileLoaded method and instead is done in playbackRestarted and involves a 0.2 second delay?

The `playbackRestarted` event (despite being called more often in general) is fired later in the file loading sequence. There is a bunch of stuff that happens after `fileLoaded` like playlist refresh and (if I recall correctly) tracklist and current track may not be finished loading yet. A lot of these things generate events which trigger display of OSD messages.

But `MPV_EVENT_PLAYBACK_RESTART` is almost always accompanied by an `MPV_EVENT_SEEK` message, and often a `pause` property change, and IINA normally generates an OSD message for each whenever it receives one. It's hard to distinguish them from user behavior. Also, the order in which they are received is not deterministic. So the 0.2 sec delay seems to be enough to block these redundant messages.

**Comment by low-batt** [comment]
Good to hear that switching from `sync` to `async` did not exhibit problems. Of course the trouble with thread related changes is that it may behave differently on other Macs. I fixed some other thread related problems that I never could reproduce on my Macs, but the timing was right on some user's Macs such that they would experience the problem. That is why I held off on these changes for a release that uses beta releases.

Using [dispatchPrecondition](https://developer.apple.com/documentation/dispatch/1780605-dispatchprecondition) is a good tip. I will think about where that could be used.

I was expecting the odd 0.2 second delay and the code not being in the `fileLoaded` method had something to do with suppressing OSD messages for events after the `MPV_EVENT_FILE_LOADED`. What disturbs me is that there aren't any comments in the code about this. The name of the flag (`disableOSDForFileLoading`) makes you expect the OSD would be re-enabled upon receiving the `MPV_EVENT_FILE_LOADED` event.  Code that relies upon delays like this should have comments discussing why a nondeterministic solution is required. Anyway, this PR preserves the current behavior. It just replaces a timer with `asyncAfter`.

**Comment by low-batt** [comment]
Rebased with `develop` and fixed merge conflicts.

**Comment by low-batt** [comment]
Rebased with `develop` again and fixed merge conflicts.

File: iina/MPVController.swift [hunk 1]
```diff
@@ -982,10 +991,10 @@ not applying FFmpeg 9599 workaround
       let userData = event.pointee.reply_userdata
       let hookEvent = event.pointee.data.bindMemory(to: mpv_event_hook.self, capacity: 1).pointee
       let hookID = hookEvent.id
-      if let hook = hooks[userData] {
-        hook.call {
-          mpv_hook_continue(self.mpv, hookID)
-        }
+      let hook = $hooks.withLock { $0[userData] }
+      guard let hook = hook else { break }
```
Comment (lhc70000) [inline iina/MPVController.swift]: We can write
```swift
guard let hook = $hooks.withLock({ $0[userData] }) else { break }
```

File: iina/MPVController.swift [hunk 2]
```diff
@@ -1130,118 +1136,148 @@ not applying FFmpeg 9599 workaround
...
+      DispatchQueue.main.async { self.player.mainWindow.rotation = rotation }
 
     case MPVProperty.videoParamsPrimaries:
       fallthrough;
 
     case MPVProperty.videoParamsGamma:
-      player.refreshEdrMode()
+      if #available(macOS 10.15, *) {
+        DispatchQueue.main.async { self.player.refreshEdrMode() }
+      }
```
Comment (lhc70000) [inline iina/MPVController.swift]: We are now targeting 10.15. Maybe you added it back accidentally during rebase?

File: iina/MPVController.swift [hunk 3]
```diff
@@ -1130,118 +1136,148 @@ not applying FFmpeg 9599 workaround
...
       }
-      player.syncUI(.playButton)
 
     case MPVProperty.chapter:
-      player.info.chapter = Int(getInt(MPVProperty.chapter))
-      player.syncUI(.time)
-      player.syncUI(.chapterList)
-      player.postNotification(.iinaMediaTitleChanged)
+      DispatchQueue.main.async { [self] in
+        player.info.chapter = Int(getInt(MPVProperty.chapter))
```
Comment (lhc70000) [inline iina/MPVController.swift]: This `getInt()` needs to be moved outside

File: iina/MPVController.swift [hunk 4]
```diff
@@ -1259,111 +1295,152 @@ not applying FFmpeg 9599 workaround
...
+      DispatchQueue.main.async { self.player.afChanged() }
 
     case MPVOption.Window.fullscreen:
-      guard player.mainWindow.loaded else { break }
-      let fs = getFlag(MPVOption.Window.fullscreen)
-      if fs != player.mainWindow.fsState.isFullscreen {
-        DispatchQueue.main.async(execute: self.player.mainWindow.toggleWindowFullScreen)
+      DispatchQueue.main.async { [self] in
+        guard player.mainWindow.loaded else { return }
+        let fs = getFlag(MPVOption.Window.fullscreen)
```
Comment (lhc70000) [inline iina/MPVController.swift]: `getFlag` should be moved out

File: iina/MPVController.swift [hunk 5]
```diff
@@ -1259,111 +1295,152 @@ not applying FFmpeg 9599 workaround
...
 
     case MPVOption.Window.ontop:
-      guard player.mainWindow.loaded else { break }
-      let ontop = getFlag(MPVOption.Window.ontop)
-      if ontop != player.mainWindow.isOntop {
-        DispatchQueue.main.async {
-          self.player.mainWindow.setWindowFloatingOnTop(ontop)
+      DispatchQueue.main.async { [self] in
+        guard player.mainWindow.loaded else { return }
+        let ontop = getFlag(MPVOption.Window.ontop)
```
Comment (lhc70000) [inline iina/MPVController.swift]: same as above

File: iina/MPVController.swift [hunk 6]
```diff
@@ -1259,111 +1295,152 @@ not applying FFmpeg 9599 workaround
...
 
     case MPVOption.Window.windowScale:
-      guard player.mainWindow.loaded else { break }
-      let windowScale = getDouble(MPVOption.Window.windowScale)
-      if fabs(windowScale - player.info.cachedWindowScale) > 10e-10 {
-        DispatchQueue.main.async {
-          self.player.mainWindow.setWindowScale(windowScale)
+      DispatchQueue.main.async { [self] in
+        guard player.mainWindow.loaded else { return }
+        let windowScale = getDouble(MPVOption.Window.windowScale)
```
Comment (lhc70000) [inline iina/MPVController.swift]: same as above

**Review by lhc70000 — CHANGES_REQUESTED** [review]
Good job! Generally looks good to me.

Another concern is that now lots of functions in `PlayerCore` are meant to be called on the main thread. We should at least add some comments to alert future developers.

File: iina/MPVController.swift (hunk 2 above)
Comment (low-batt) [reply iina/MPVController.swift]: Yes, I probably missed that during the rebase. Will fix.

File: iina/MPVController.swift (hunk 3 above)
Comment (low-batt) [reply iina/MPVController.swift]: I'm confused. Why can't `getInt` be called on the main thread?

Comment (lhc70000) [reply iina/MPVController.swift]: Because it's `mpv_get_property()`, and we want it to be on the `com.colliderli.iina.controller` thread. If it's on the main thread, then for example, `mpv_destroy()` is on the `com.colliderli.iina.controller` thread, and it will cause another potential crash due to race condition when closing the window.

https://github.com/iina/iina/blob/1ebe0f459627c8e10639bd65276e29bd57629fdd/iina/MPVController.swift#L970-L975

Comment (low-batt) [reply iina/MPVController.swift]: Will fix, but we do call methods like `getInt` outside of `MPVController` from code I'm sure is running on the main thread. I will think on how to better coordinate this. I have seen `mpv` emit some events during shutdown that it really shouldn't be emitting. I've been worried that we let `q` through to `mpv` causing `mpv` to shutdown "behind" IINA's back although I've not been able to trigger a crash in testing that. The `gets` are a problem because they do not return optional values. If they did it would be easy to detect shutdown and return `nil`.

Comment (lhc70000) [reply iina/MPVController.swift]: Yes, but these ones are perhaps much easier to trigger because it's in `handleEvent`. We can't say exactly that "mpv is emitting events during shutdown", because this block is queued on the main thread and executed later than the event, after some unknown delay. If mpv shuts down right after emitting the event, there will be a crash.

> The gets are a problem because they do not return optional values. If they did it would be easy to detect shutdown and return nil.

If we are going to add the check, I think we can just return 0. If mpv is already terminated then the value makes little sense.

Comment (low-batt) [reply iina/MPVController.swift]: Brain wasn't remembering this PR last night, it has been a while since I coded it. I remember thinking having the get methods return some random value seemed a bit wrong. So I decided it would be better to coordinate shutdown at a higher level. I have been slowly refactoring MPVController to call "listener" methods in PlayerCore. Those methods have the ability to check if shutdown is in progress and if so, drop the event. I need to refactor the code you pointed out into additional "listener" methods in PlayerCore that check the state and avoid calling `getInt`.

I'm used to a layered design where the bottom layer classes know very little about the higher level code. I was expecting we'd have a class that was focused solely on providing a Swift interface for the mpv client. Since we did not have such a class I did not consider implementing the interesting suggestion from @CarterLi in PR #4367 of using mpv to display previews of JPEG XL screenshots. In macOS Sonoma AppKit renders the preview of JPEG XL screenshots, so going forward mpv is not needed for that. However we still at some point need support for HDR screenshots. One way to do that would be to move away from our proprietary thumbnail file format and store the thumbnails as a MP4 and use mpv to display them. A discussion for another day. Anyway, just an example of how a more isolated mpv client could have been used.

Comment (low-batt) [reply iina/MPVController.swift]: I think I have addressed the comments. I added a comment about the main thread requirement. I moved the code that was calling back into mpv to PlayerCore with checks for shutting down.

**Review by lhc70000 — APPROVED** [review]
