### PR TITLE
Fix top osc not responds to scroll wheel

### LINKED ISSUE #3863: Enable scroll wheel scrubbing with Controller UI in Top position
**System and IINA version:**

- macOS  10.14.6
- IINA  1.30

**Expected behavior:**

The scroll wheel should scrub the video when the pointer is hovering over the controller, for all controller layout options.

**Actual behavior:**

When the Top layout is chosen as the controller UI option, scrubbing does not occur as it does when the Bottom or Floating layout is chosen.

**Steps to reproduce:**

Set UI position to Top, open video file, hover pointer over controller, and attempt to scrub using the scroll wheel.

**How often does this happen?**

Always.  This issue was present in previous versions as well, and 1.30 exhibits the same behavior.

### PR DESCRIPTION
**Pull request by uiryuu**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #3863.

---

**Description:**
Found a simple fix to this issue, just don't return when one of the override is true. @svobs @low-batt take a look

### CODE REVIEW

File: iina/MainWindowController.swift [hunk 1]
```diff
@@ -1051,6 +1050,10 @@ class MainWindowController: PlayerWindowController {
       guard !isMouseEvent(event, inAnyOf: [currentControlBar]) else { return }
     }
 
+    if isMouseEvent(event, inAnyOf: [sideBarView, titleBarView, subPopoverView]) && !(seekOverride || volumeOverride) {
+      return
+    }
+
```
Comment (low-batt) [inline iina/MainWindowController.swift:1055]: Why switch to a complex `if` over a `guard`? Can't this just be?:
```swift
    guard !isMouseEvent(event, inAnyOf: [sideBarView, titleBarView, subPopoverView])
            || seekOverride || volumeOverride else { return }
```

Comment (uiryuu) [reply iina/MainWindowController.swift:1055]: You are absolutely correct. Somehow I incorrectly thought converting to `if` would make it simpler.

**Review by low-batt — APPROVED** [review]
I confirmed this fixes the problem. Good to get this one fixed!
