### PR TITLE
Fix #4156 (OSD stealing mouse clicks from OSC even while hidden), #4612: (OSC responds to mouse hover when behind OSD)

### LINKED ISSUE #4156: With seek bar/controller moved to top left, parts of seek bar doesn't respond.
**System and IINA version:**

- macOS 13.1 (on macbook air m1)
- IINA 1.3.1 (via homebrew)

**Expected behavior:**

Clicking and dragging to seek in the video seeks to expected part of video.

**Actual behavior:**

Clicking on seek bar doesn't work if seek bar/controller is moved to top left of screen. The seek bar doesn't work in the exact area as the "notification" telling which timecode of the video you were seeking to. The notification itself overlays the seek bar.

**Steps to reproduce:**

1. Move video controller to the top left (the controller with the seek bar, play, pause etc) while iina is minimized.
2. Try to use the seek bar to seek to an area close to the beginning of the video. 
3. Iina will not seek, because clicking in this region apparently the clicks are sent to the "seek-to-notification" view in the top left, instead of to the seek bar.

Screenshot of IINA (02-01-2023, 14-31-00)

**How often does this happen?**

Consistently, reproducible over many versions of iina.

### LINKED ISSUE #4612: OSC responds to mouse when behind the OSD
**System and IINA version:**

- macOS 13.5
- IINA 1.3.3

**Expected behavior:**
OSC does not respond to mouse when behind the OSD.

**Actual behavior:**
As can be seen here even though the OSC was behind the OSD it responded to the mouse position and displayed a thumbnail, blocking a portion of the OSD:
osc-thumbnail

- [x ] MPV does not have this problem.

**How often does this happen?**
Every time.

### PR DESCRIPTION
**Pull request by svobs**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issues:
  - #4156 
  - #4612.

---

**Description:**

Could not have been a more straightforward fix. When the OSD was hidden, its alpha was set to 0, but `isHidden` was never set to `true` (looks deleted or forgot to include).

Update: added a fix for #4612, since it needed the original fix as a prerequisite.

### CODE REVIEW

**Comment by svobs** [comment]
Added another commit which fixes #4612.

It also adds an `else` which takes care to hide the thumbnail when it is determined it should not be shown. This may help with #4559.

File: iina/MainWindowController.swift [hunk 1]
```diff
@@ -2265,6 +2262,16 @@ class MainWindowController: PlayerWindowController {
     }
   }
 
+  private func refreshSeekTimeAndThumnail(from event: NSEvent) {
+    let isCoveredByOSD = !osdVisualEffectView.isHidden && isMouseEvent(event, inAnyOf: [osdVisualEffectView])
```
Comment (uiryuu) [inline iina/MainWindowController.swift:2266]: I also found that if the sidebar covers the thumbnail, it will also trigger the thumbnail, and I've confirmed that something like this
`let isCoveredBySidebar = !sideBarView.isHidden && isMouseEvent(event, inAnyOf: [sideBarView])`
and checking both `isCoveredByOSD` and `isCoveredBySidebar` is able to fix this problem

**Review by uiryuu — CHANGES_REQUESTED** [review]
Sidebar can also cover the thumbnail, please also fix this issue. Otherwise this pr is good to merge.

File: iina/MainWindowController.swift [hunk 2]
```diff
@@ -2265,6 +2262,16 @@ class MainWindowController: PlayerWindowController {
     }
   }
 
+  private func refreshSeekTimeAndThumnail(from event: NSEvent) {
```
Comment (Coeur) [inline iina/MainWindowController.swift]: Would you mind renaming it without a typo?
```suggestion
  private func refreshSeekTimeAndThumbnail(from event: NSEvent) {
```

Comment (svobs) [reply iina/MainWindowController.swift]: Pushed another commit which should address feedback, thanks.

**Comment by uiryuu** [comment]
Thanks!
