### PR TITLE
Update highlight of sidebar tab buttons so they all match (fixes issue #4332)

### LINKED ISSUE #4332: Sidebar active tab button colors for do not match
**System and IINA version:**

- macOS 13.1
- IINA `develop` f6f0eb727678ab6679280f73695bd64b38701734

**Expected behavior:**

The highlight color of the "active" tab in the [Quick] Settings tab group should be the same as the Playlist/Chapters tab group (preferably solid black?)

**Actual behavior:**

Settings tabs are #000000, but Playlist/Chapters tabs are #61554B.

SCR-20230409-bqzg

SCR-20230409-bqvt

**Steps to reproduce:**

I highly recommend the amazing app [Shottr](https://shottr.cc/) which is an excellent tool for taking screenshots, analyzing them and annotating them. The shots above are screenshots of it viewing screenshots from IINA, showing the output of its color analyzer.

**How often does this happen?**

Always

### PR DESCRIPTION
**Pull request by svobs**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4332.

---

**Description:**

Analysis: For newer versions of MacOS (10.14+), the 3 Quick Settings tab buttons are displayed all in bold, and the active tab's button text tint is set to pure black. However, the Playlist & Chapters tabs were following (what looks like) an older scheme: the active tab was bold, and the other tab was not bold; neither had a special tint. (The Quick Settings tabs fall back to this behavior for older versions of MacOS).

This update changes Playlist & Chapters so that they match the behavior of the other three

### CODE REVIEW

**Comment by svobs** [comment]
Update: found a case which I missed, where the Playlist was displayed in Music Mode right after starting IINA. Fixed in the latest commit.

**Comment by low-batt** [comment]
For me the Playlist and Chapters tabs do not match. Looks like the Playlist font is bold and Chapters isn't?

**Comment by svobs** [comment]
> For me the Playlist and Chapters tabs do not match. Looks like the Playlist font is bold and Chapters isn't?

Good catch. Made another commit to address this.

**Review by low-batt — APPROVED** [review]
Pulled PR, built, tested, looks good to me.

File: iina/ExtendedColors.swift [hunk 1]
```diff
@@ -36,3 +36,9 @@ extension NSColor.Name {
   static let sidebarTabTint = NSColor.Name("SidebarTabTint")
   static let sidebarTabTintActive = NSColor.Name("SidebarTabTintActive")
 }
+
+@available(OSX 10.14, *)
```
Comment (uiryuu) [inline iina/ExtendedColors.swift]:
```suggestion
@available(macOS 10.14, *)
```

**Review by uiryuu — CHANGES_REQUESTED** [review]

File: iina/ExtendedColors.swift (hunk 1 above)
Comment (svobs) [reply iina/ExtendedColors.swift]: Updated in latest commit

**Comment by uiryuu** [comment]
Thanks!
