### PR TITLE
Fix unintended fast-forward when dismissing notification banner

### LINKED ISSUE #5540: Unintended fast-forward when dismissing notification banner in fullscreen mode
### IINA Version

1.3.5 Build 141

### Release Channel

Release

### macOS Version

15.5 (24F74)

### Steps to Reproduce

- Enter fullscreen mode
- Trigger a notification banner (e.g. using Alfred for testing)
- Move the cursor over the banner
- Quickly swipe with a Trackpad or Magic Mouse to dismiss it

### Expected Behavior

Player stays at current frame or slightly fast forward

### Actual Behavior

Fast forward quickly to the end(usually the case for a tv show episode) 

### Crash Report or Process Sample

_No response_

### Logs

_No response_

### Sample Files

https://github.com/user-attachments/assets/757a6e53-f930-4df5-afc1-eff77ab02138

### How often can you reproduce the issue

95%

### Required Actions

- [x] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [x] I tested with the Nightly build and confirmed the issue is not fixed.
- [ ] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

### PR DESCRIPTION
**Pull request by bo2themax**
- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #5540.

---

**Description:**

Added a check to ensure scroll momentum phase matches expected gesture sequence.

### CODE REVIEW

File: iina/MainWindowController.swift [hunk 1]
```diff
@@ -161,6 +161,8 @@ class MainWindowController: PlayerWindowController {
   // might use another obj to handle slider?
   var isMouseInWindow: Bool = false
   var isMouseInSlider: Bool = false
+  /** flag to ignor abrupt momentum scrolls */
```
Comment (low-batt) [inline iina/MainWindowController.swift]: typo: `ignor`

This is why the spelling check failed.

**Review by bo2themax — COMMENTED** [review]
Done

**Comment by uiryuu** [comment]
Thanks!
