### PR TITLE
Fix screenshot crash with long video title, #3334

### LINKED ISSUE #3334: Crash when screenshotting with long video title (No error display)
This is a bug in mpv in crashing with long video titles since it saves files by default containing the full filename. macOS filename limit is 255 characters. But, streams can often have far more than 255 character filenames. Iina will then crash with no error display. This should be handled better, likely with an error display that it can't save a file. You could attempt to truncate this to 255 characters as well but that approach doesn't seem ideal. 

- macOS 10.15.7
- IINA 1.1.2 Build 128

```
[   5.892][d][global] user path: '/Users/drewbitt/Pictures/Screenshots' -> '/Users/drewbitt/Pictures/Screenshots'
[   5.892][v][cplayer] Starting screenshot: '/Users/drewbitt/Pictures/Screenshots/CpMEKnGjK_3okdJGWD1cW5pqCjYWfoVenzgwG239NfKKzVU-5KTYVh2-FKS1whmCRiG0HKco5_Qeoc5KDcrvzd1Pkb5QLoJ954fnjeIcp3_O5HbADC-BSvW2zGpkVkYA0tQ-KntJpWEeCEAPSG_D2LeNUIA-S8T1BR1y2gR4aOAd-0ROzkPn_0a9VsSLYp3KZffPdI6u6j1BfZDPnRvU2n4sVLEQUSa_7Cp4yvOrKCfLOxgcpVbeHRHDp2dLiDHW366aI4c6l0f-wFgj6WgPbyHHz5wuZjC95mso0CGyjmj0l-kT_6H8J2qQ7MDdAVKGwKrF7pAYTGROATeB7ldUgr8VR9N7Zac1YtPKikqlVF_OXMuLirgu5mP0ZOPPgirRiwXXt_Ax4nVb15mIagu_JWviYMl0AT3hPvIhBKEMqIGYrST0xb7QIcIWs5Iz3VpEB1slBvTLzhfRM0n_iJ0-JOaqyP9y0PXmzDyUj3aflUBxDyIPzNGSSNaJ7Vvs3OWHqgp4cXjGXg6M99dYUXS8CA5D8WkAZ5u2mig5lDBGAmQj3OdSu0jqr1q33F7mRqz7_5vCqagak0SF8VvbOIqDm0ACdlcDjwtmR7W6x7qfwwaCvSnSeaAgHJJzrG7ggN4QRzETpAnWY99zRcQtevgp2RQkMqLE2qtUr87b-xHjVCfuz3U-Ek1OxD6uRGq8-4emTwxFUBRUEhBsdiA3xgCW5CwhhduDVp_mGgwR5yRZrZfgfRH3YI0-0001.png'
[   5.892][d][ffmpeg] SwScaler: reducing / aligning filtersize 1 -> 4
[   5.893][d][ffmpeg] SwScaler: reducing / aligning filtersize 7 -> 8
[   5.893][d][ffmpeg] SwScaler: reducing / aligning filtersize 1 -> 1
[   5.893][d][ffmpeg] SwScaler: reducing / aligning filtersize 7 -> 6
[   5.893][v][ffmpeg] swscaler: Lanczos scaler, from nv12 to rgb24 using MMXEXT
[   5.893][d][ffmpeg] swscaler: 1920x1080 -> 1920x1080
[   5.920][e][cplayer] Error opening '/Users/drewbitt/Pictures/Screenshots/CpMEKnGjK_3okdJGWD1cW5pqCjYWfoVenzgwG239NfKKzVU-5KTYVh2-FKS1whmCRiG0HKco5_Qeoc5KDcrvzd1Pkb5QLoJ954fnjeIcp3_O5HbADC-BSvW2zGpkVkYA0tQ-KntJpWEeCEAPSG_D2LeNUIA-S8T1BR1y2gR4aOAd-0ROzkPn_0a9VsSLYp3KZffPdI6u6j1BfZDPnRvU2n4sVLEQUSa_7Cp4yvOrKCfLOxgcpVbeHRHDp2dLiDHW366aI4c6l0f-wFgj6WgPbyHHz5wuZjC95mso0CGyjmj0l-kT_6H8J2qQ7MDdAVKGwKrF7pAYTGROATeB7ldUgr8VR9N7Zac1YtPKikqlVF_OXMuLirgu5mP0ZOPPgirRiwXXt_Ax4nVb15mIagu_JWviYMl0AT3hPvIhBKEMqIGYrST0xb7QIcIWs5Iz3VpEB1slBvTLzhfRM0n_iJ0-JOaqyP9y0PXmzDyUj3aflUBxDyIPzNGSSNaJ7Vvs3OWHqgp4cXjGXg6M99dYUXS8CA5D8WkAZ5u2mig5lDBGAmQj3OdSu0jqr1q33F7mRqz7_5vCqagak0SF8VvbOIqDm0ACdlcDjwtmR7W6x7qfwwaCvSnSeaAgHJJzrG7ggN4QRzETpAnWY99zRcQtevgp2RQkMqLE2qtUr87b-xHjVCfuz3U-Ek1OxD6uRGq8-4emTwxFUBRUEhBsdiA3xgCW5CwhhduDVp_mGgwR5yRZrZfgfRH3YI0-0001.png' for writing!
[   5.920][e][cplayer] Error writing screenshot!
```
and a crash

Expected Behavior: Tells you if it can't screenshot and doesn't simply crash with no error

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:

- Change the method  MPVController.handleEvent to raise an alert if
    screenshot generation failed
- Change the method  Utility.getLatestScreenshot to guard against an empty
    screenshot directory

This commit adds new text for the alert that will require localization.

- [ ] This change has been discussed with the author.
- [ x] It implements / fixes issue #3334.

---

**Description:**

NOTE the need for localization of the added alert message text.

### CODE REVIEW

File: iina/MPVController.swift [hunk 1]
```diff
@@ -664,6 +664,18 @@ class MPVController: NSObject {
     case MPV_EVENT_COMMAND_REPLY:
       let reply = event.pointee.reply_userdata
       if reply == MPVController.UserData.screenshot {
+        let code = event.pointee.error
+        guard 0 <= code else {
```
Comment (saagarjha) [inline iina/MPVController.swift:668]: I think I would prefer the condition to be flipped

```suggestion
        guard code >= 0 else {
```

File: iina/MPVController.swift [hunk 2]
```diff
@@ -664,6 +664,18 @@ class MPVController: NSObject {
...
+          let error = String.init(cString: mpv_error_string(code))
```
Comment (saagarjha) [inline iina/MPVController.swift:669]:
```suggestion
          let error = String(cString: mpv_error_string(code))
```

File: iina/Utility.swift [hunk 3]
```diff
@@ -461,7 +461,7 @@ class Utility {
     guard let contents = try? FileManager.default.contentsOfDirectory(
       at: folder,
       includingPropertiesForKeys: [.creationDateKey],
-      options: .skipsSubdirectoryDescendants) else { return nil }
+      options: .skipsSubdirectoryDescendants), !contents.isEmpty else { return nil }
```
Comment (saagarjha) [inline iina/Utility.swift:464]:
```suggestion
      options: .skipsSubdirectoryDescendants),
      let latestFile = contents.first else { return nil }
```

File: iina/MPVController.swift (hunk 1 above)
Comment (low-batt) [reply iina/MPVController.swift]: Fixed

File: iina/MPVController.swift (hunk 2 above)
Comment (low-batt) [reply iina/MPVController.swift]: I see my inexperience with Swift is showing. Fixed.

File: iina/Utility.swift (hunk 3 above)
Comment (low-batt) [reply iina/Utility.swift]: Fixed. I did have to use var instead of let as the code below this updates latestFile.

Comment (saagarjha) [reply iina/Utility.swift]: Ah, I see. I would probably replace the code below to use `min(by:)` with a custom comparator, to be honest, but it's up to you if you want to change that here.

Comment (low-batt) [reply iina/Utility.swift]: That was existing code that I thought could be simplified, but I chose to make the minimum change to fix the issue. I have just pushed a commit that simplifies this method. See if that is what you were expecting.

File: iina/Utility.swift [hunk 4]
```diff
@@ -461,18 +461,9 @@ class Utility {
...
-    for file in contents {
-      if let date = try? file.resourceValues(forKeys: [.creationDateKey]).creationDate, date > latestDate {
-        latestDate = date
-        latestFile = file
-      }
-    }
-    return latestFile
+      options: .skipsSubdirectoryDescendants),
+          !contents.isEmpty else { return nil }
+    return contents.max { a, b in a.creationDate! < b.creationDate! }
```
Comment (uiryuu) [inline iina/Utility.swift:466]:
```suggestion
    return contents.filter { $0.creationDate != nil }.max { $0.creationDate! < $1.creationDate! }
```
Or if you are sure that `creationDate` would never be `nil`, you can remove the `filter` clause.

**Review by uiryuu — CHANGES_REQUESTED** [review]

File: iina/Utility.swift (hunk 4 above)
Comment (low-batt) [reply iina/Utility.swift]: Fixed. Rebased with develop. Tested again. I kept the filter. Made me worry that someone could put the screen shot directory on some network device that doesn't provide it.

**Review by uiryuu — APPROVED** [review]
