### PR TITLE
Fix  crash during quit in windowDidExitFullScreen, #4020

### LINKED ISSUE #4020: Crash during quit in windowDidExitFullScreen
**System and IINA version:**

- macOS 13.0
- IINA develop 15d0451

**Expected behavior:**
IINA does not crash when quitting.

**Actual behavior:**
During termination MainWindowController.windowDidExitFullScreen was called. MainWindowController called PlayerCore which called MPVController.getDouble. That method called mpv_get_property triggering a crash as IINA had already sent a quit command to mpv.

This is with the develop branch that contains changes to try and correct shutdown problems.

<details>
<summary><b>Xcode Console:</b></summary>

```
14:10:23.356 [iina][d] IINA 1.3.0 Build 131
14:10:23.358 [iina][d] Copyright © 2017-2022
14:10:23.358 [iina][d] Collider LI, et al.
14:10:23.358 [iina][d] Released under GPLv3.
14:10:23.358 [iina][d] FFmpeg 4.4.2
14:10:23.358 [iina][d]   libavcodec 58.134.100
14:10:23.358 [iina][d]   libavformat 58.76.100
14:10:23.358 [iina][d]   libavutil 56.70.100
14:10:23.358 [iina][d]   libswscale 5.9.100
14:10:23.358 [iina][d] App will launch
14:10:23.358 [iina][d] Got arguments ["-NSDocumentRevisionsDebugMode", "YES"]
14:10:23.358 [iina][d] IINA arguments: []
14:10:23.358 [iina][d] Filenames from arguments: []
IINA 1.3.0 Build 131
This binary is not intended for being used as a command line tool. Please use the bundled iina-cli.
Please ignore this message if you are running in a debug environment.
14:10:23.379 [iina][d] App launched
14:10:23.380 [iina][d] Loading key bindings
14:10:23.382 [iina][d] Set key bindings
2022-10-29 14:10:23.385423-0400 IINA[9185:878426] [logging] open flag(s) 0x01000000 are reserved for VFS use and do not affect behaviour when passed to sqlite3_open_v2
2022-10-29 14:10:23.385491-0400 IINA[9185:878426] [logging-persist] cannot open file at line 46922 of [6bf7a27121]
2022-10-29 14:10:23.385507-0400 IINA[9185:878426] [logging-persist] os_unix.c:46922: (0) open(/private/var/db/DetachedSignatures) - Undefined error: 0
2022-10-29 14:10:23.486631-0400 IINA[9185:877912] Metal API Validation Enabled
14:10:23.512 [player0][d] Set path to /Users/low-batt/Library/Developer/Xcode/DerivedData/iina-caydzgleiqupoxbtitkkfadxksfs/Build/Products/Debug/IINA.app/Contents/MacOS:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
2022-10-29 14:10:23.530162-0400 IINA[9185:877912] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000003c45e0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
14:10:23.547 [iina][d] Using mpv 0.34.1
14:10:23.547 [iina][d] Setting up MediaPlayer integration
14:10:23.549 [player0][d] Track list changed
14:10:25.589 [player0][d] Open URL: file:///Users/low-batt/Movies/The%20World%20in%20HDR%20in%204K%20(ULTRA%20HD).mp4
14:10:25.589 [player0][d] Opening /Users/low-batt/Movies/The World in HDR in 4K (ULTRA HD).mp4 in main window
14:10:25.697 [iina][d] Created OpenGL pixel format with [__C._CGLPixelFormatAttribute(rawValue: 5), __C._CGLPixelFormatAttribute(rawValue: 96), __C._CGLPixelFormatAttribute(rawValue: 99), __C._CGLPixelFormatAttribute(rawValue: 12800), __C._CGLPixelFormatAttribute(rawValue: 73), __C._CGLPixelFormatAttribute(rawValue: 0)]
14:10:25.706 [iina][d] Falling back to nominal display refresh rate: 120.0 from 0.0
14:10:25.709 [iina][d] window!.screen: Built-in Retina Display visible frame (0.0, 44.0, 1728.0, 1035.0)
14:10:25.709 [iina][d] NSScreen.main: Built-in Retina Display visible frame (0.0, 44.0, 1728.0, 1035.0)
14:10:25.709 [iina][d] NSScreen.screens[0]: Built-in Retina Display visible frame (0.0, 44.0, 1728.0, 1035.0)
14:10:25.709 [iina][d] MainWindowLastPosition (0.0, 76.0) matched: Built-in Retina Display visible frame (0.0, 44.0, 1728.0, 1035.0)
14:10:25.711 [player0][d] File started
14:10:25.711 [player0][d] Track list changed
14:10:25.712 [player0][d] Started auto load
14:10:25.713 [fmatcher][d] **Start matching
14:10:25.713 [fmatcher][d] Getting all media files...
14:10:25.716 [player0][d] Track list changed
14:10:25.720 [player0][d] File loaded
14:10:25.726 [fmatcher][d] Got all media files, video=22, audio=0
14:10:25.727 [fmatcher][d] Getting all sub files...
14:10:25.728 [fmatcher][d] Searching subtitles from 5 directories...
14:10:25.733 [fmatcher][d] Got 9 subtitles
14:10:25.734 [fmatcher][d] Grouping video files...
14:10:25.734 [fgroup][d] Start grouping 22 files
14:10:25.735 [fmatcher][d] Finished with 1 groups
14:10:25.735 [fmatcher][d] Grouping sub files...
14:10:25.735 [fgroup][d] Start grouping 9 files
14:10:25.735 [fmatcher][d] Finished with 1 groups
14:10:25.735 [fmatcher][d] Matching video and sub series...
14:10:25.735 [fmatcher][d] Calculated editing distance
14:10:25.736 [fmatcher][d] Finished matching.
14:10:25.737 [fmatcher][d] Matching subs with matched series, prefixes=0...
14:10:25.737 [fmatcher][d] **Finished matching
14:10:25.755 [player0][d] Track list changed
14:10:25.827 [player0][d] Getting thumbnails
14:10:25.828 [player0][d] Found thumbnail cache
14:10:25.828 [thumbcache][d] Reading thumbnail cache...
14:10:25.828 [thumbcache][d] Reading from /Users/low-batt/Library/Caches/com.colliderli.iina/thumb_cache/5136587baff284aba811c3f47b084be6
14:10:25.829 [player0][d] Track list changed
14:10:25.830 [hdr][d] Will activate HDR color space instead of using ICC profile
14:10:25.839 [hdr][d] HDR mode has been enabled, skipping
14:10:25.859 [thumbcache][d] Finished reading thumbnail cache, 53 in total
14:10:27.613 [player0][d] Playback restarted
14:10:37.369 [iina][e] Return value -4 when executing key command {encode} quit 4
14:10:37.369 [iina][w] mpv log: [input] error: Command '{encode}' not found.
14:10:37.369 [iina][w] mpv log: [input] error: Command was defined at main.
14:10:42.980 [iina][d] App should terminate
14:10:42.980 [iina][d] Disabling all menus
14:10:42.981 [iina][d] Disabling remote commands
14:10:42.981 [iina][d] Closing all windows
14:10:42.983 [player0][d] Write watch later config
14:10:42.985 [player0][d] Stopping playback
14:10:43.017 [iina][d] Waiting for players to stop and shutdown
14:10:43.221 [hdr][d] HDR primaries and gamma not available
14:10:43.222 [hdr][d] HDR primaries and gamma not available
14:10:43.226 [player0][d] Playback has stopped
14:10:43.226 [player0][d] Shutting down
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x48)
    frame #0: 0x0000000103f1d418 libmpv.1.dylib`mpv_get_property + 16
  * frame #1: 0x0000000102813b08 IINA`MPVController.getDouble(name="time-pos", self=0x00006000031ad170) at MPVController.swift:578:5
    frame #2: 0x00000001027d1d70 IINA`PlayerCore.syncUI(option=time, self=0x0000600003cac3c0) at PlayerCore.swift:1576:40
    frame #3: 0x00000001027d1474 IINA`PlayerCore.syncUITime(self=0x0000600003cac3c0) at PlayerCore.swift:1559:7
    frame #4: 0x0000000102540a88 IINA`MainWindowController.showUI(self=0x000000012a863800) at MainWindowController.swift:1677:12
    frame #5: 0x0000000102538120 IINA`MainWindowController.windowDidExitFullScreen(notification=Foundation.Notification @ 0x000000016da2bb60, self=0x000000012a863800) at MainWindowController.swift:1281:5
    frame #6: 0x000000010253894c IINA`@objc MainWindowController.windowDidExitFullScreen(_:) at <compiler-generated>:0
    frame #7: 0x000000019fae258c CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
    frame #8: 0x000000019fb80074 CoreFoundation`___CFXRegistrationPost_block_invoke + 88
    frame #9: 0x000000019fb7ffbc CoreFoundation`_CFXRegistrationPost + 440
    frame #10: 0x000000019fab3bac CoreFoundation`_CFXNotificationPost + 708
    frame #11: 0x00000001a09a072c Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 88
    frame #12: 0x00000001a37af398 AppKit`-[NSWindow(NSFullScreen) _didExitFullScreen] + 336
    frame #13: 0x00000001a35b70a8 AppKit`-[_NSExitFullScreenTransitionController _doAfterExitFullScreen] + 304
    frame #14: 0x00000001a35b7904 AppKit`-[_NSExitFullScreenTransitionController _doSucceededToExitFullScreen] + 712
    frame #15: 0x00000001a35b813c AppKit`__63-[_NSExitFullScreenTransitionController _performExitFullScreen]_block_invoke + 236
    frame #16: 0x000000019f77d670 libxpc.dylib`_xpc_connection_reply_callout + 124
    frame #17: 0x000000019f77d560 libxpc.dylib`_xpc_connection_call_reply_async + 88
    frame #18: 0x000000010361ea54 libdispatch.dylib`_dispatch_client_callout3 + 20
    frame #19: 0x0000000103644d04 libdispatch.dylib`_dispatch_mach_msg_async_reply_invoke + 400
    frame #20: 0x0000000103631cd8 libdispatch.dylib`_dispatch_main_queue_drain + 780
    frame #21: 0x00000001036319bc libdispatch.dylib`_dispatch_main_queue_callback_4CF + 44
    frame #22: 0x000000019fb2ed6c CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
    frame #23: 0x000000019faec7ec CoreFoundation`__CFRunLoopRun + 2036
    frame #24: 0x000000019faeb8a4 CoreFoundation`CFRunLoopRunSpecific + 612
    frame #25: 0x00000001a915f3bc HIToolbox`RunCurrentEventLoopInMode + 292
    frame #26: 0x00000001a915f04c HIToolbox`ReceiveNextEventCommon + 236
    frame #27: 0x00000001a915ef48 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 72
    frame #28: 0x00000001a2d44630 AppKit`_DPSNextEvent + 632
    frame #29: 0x00000001a2d437c0 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
    frame #30: 0x00000001a2f663b0 AppKit`-[NSApplication _shouldTerminate] + 700
    frame #31: 0x00000001a2f58fb0 AppKit`-[NSApplication terminate:] + 612
    frame #32: 0x00000001a2eed2f0 AppKit`-[NSApplication(NSResponder) sendAction:to:from:] + 440
    frame #33: 0x00000001a2fb9998 AppKit`-[NSMenuItem _corePerformAction] + 336
    frame #34: 0x00000001a2fb9714 AppKit`-[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 104
    frame #35: 0x00000001a2ff5710 AppKit`-[NSMenu performActionForItemAtIndex:] + 200
    frame #36: 0x00000001a2ff5630 AppKit`-[NSMenu _internalPerformActionForItemAtIndex:] + 76
    frame #37: 0x00000001a2ff5484 AppKit`-[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 108
    frame #38: 0x00000001a2fa1cdc AppKit`NSSLMMenuEventHandler + 640
    frame #39: 0x00000001a9137944 HIToolbox`DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1092
    frame #40: 0x00000001a9136dc4 HIToolbox`SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 356
    frame #41: 0x00000001a914cfd4 HIToolbox`SendEventToEventTarget + 40
    frame #42: 0x00000001a91ac6bc HIToolbox`SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) + 416
    frame #43: 0x00000001a91d0ee4 HIToolbox`SendMenuCommandWithContextAndModifiers + 56
    frame #44: 0x00000001a91d0e74 HIToolbox`SendMenuItemSelectedEvent + 352
    frame #45: 0x00000001a91d0ca0 HIToolbox`FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) + 100
    frame #46: 0x00000001a91d1660 HIToolbox`MenuSelectCore(MenuData*, Point, double, unsigned int, OpaqueMenuRef**, unsigned short*) + 560
    frame #47: 0x00000001a91d1380 HIToolbox`_HandleMenuSelection2 + 416
    frame #48: 0x00000001a2e970f4 AppKit`_NSHandleCarbonMenuEvent + 256
    frame #49: 0x00000001a2e96f18 AppKit`_DPSEventHandledByCarbon + 60
    frame #50: 0x00000001a2d43db8 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2256
    frame #51: 0x00000001a2d37bf0 AppKit`-[NSApplication run] + 464
    frame #52: 0x00000001a2d0f058 AppKit`NSApplicationMain + 880
    frame #53: 0x00000001025e4e18 IINA`main at AppDelegate.swift:24:7
    frame #54: 0x000000019f6e3e50 dyld`start + 2544
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x48)
    frame #0: 0x0000000103f1d418 libmpv.1.dylib`mpv_get_property + 16
  * frame #1: 0x0000000102813b08 IINA`MPVController.getDouble(name="time-pos", self=0x00006000031ad170) at MPVController.swift:578:5
    frame #2: 0x00000001027d1d70 IINA`PlayerCore.syncUI(option=time, self=0x0000600003cac3c0) at PlayerCore.swift:1576:40
    frame #3: 0x00000001027d1474 IINA`PlayerCore.syncUITime(self=0x0000600003cac3c0) at PlayerCore.swift:1559:7
    frame #4: 0x0000000102540a88 IINA`MainWindowController.showUI(self=0x000000012a863800) at MainWindowController.swift:1677:12
    frame #5: 0x0000000102538120 IINA`MainWindowController.windowDidExitFullScreen(notification=Foundation.Notification @ 0x000000016da2bb60, self=0x000000012a863800) at MainWindowController.swift:1281:5
    frame #6: 0x000000010253894c IINA`@objc MainWindowController.windowDidExitFullScreen(_:) at <compiler-generated>:0
    frame #7: 0x000000019fae258c CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
    frame #8: 0x000000019fb80074 CoreFoundation`___CFXRegistrationPost_block_invoke + 88
    frame #9: 0x000000019fb7ffbc CoreFoundation`_CFXRegistrationPost + 440
    frame #10: 0x000000019fab3bac CoreFoundation`_CFXNotificationPost + 708
    frame #11: 0x00000001a09a072c Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 88
    frame #12: 0x00000001a37af398 AppKit`-[NSWindow(NSFullScreen) _didExitFullScreen] + 336
    frame #13: 0x00000001a35b70a8 AppKit`-[_NSExitFullScreenTransitionController _doAfterExitFullScreen] + 304
    frame #14: 0x00000001a35b7904 AppKit`-[_NSExitFullScreenTransitionController _doSucceededToExitFullScreen] + 712
    frame #15: 0x00000001a35b813c AppKit`__63-[_NSExitFullScreenTransitionController _performExitFullScreen]_block_invoke + 236
    frame #16: 0x000000019f77d670 libxpc.dylib`_xpc_connection_reply_callout + 124
    frame #17: 0x000000019f77d560 libxpc.dylib`_xpc_connection_call_reply_async + 88
    frame #18: 0x000000010361ea54 libdispatch.dylib`_dispatch_client_callout3 + 20
    frame #19: 0x0000000103644d04 libdispatch.dylib`_dispatch_mach_msg_async_reply_invoke + 400
    frame #20: 0x0000000103631cd8 libdispatch.dylib`_dispatch_main_queue_drain + 780
    frame #21: 0x00000001036319bc libdispatch.dylib`_dispatch_main_queue_callback_4CF + 44
    frame #22: 0x000000019fb2ed6c CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
    frame #23: 0x000000019faec7ec CoreFoundation`__CFRunLoopRun + 2036
    frame #24: 0x000000019faeb8a4 CoreFoundation`CFRunLoopRunSpecific + 612
    frame #25: 0x00000001a915f3bc HIToolbox`RunCurrentEventLoopInMode + 292
    frame #26: 0x00000001a915f04c HIToolbox`ReceiveNextEventCommon + 236
    frame #27: 0x00000001a915ef48 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 72
    frame #28: 0x00000001a2d44630 AppKit`_DPSNextEvent + 632
    frame #29: 0x00000001a2d437c0 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
    frame #30: 0x00000001a2f663b0 AppKit`-[NSApplication _shouldTerminate] + 700
    frame #31: 0x00000001a2f58fb0 AppKit`-[NSApplication terminate:] + 612
    frame #32: 0x00000001a2eed2f0 AppKit`-[NSApplication(NSResponder) sendAction:to:from:] + 440
    frame #33: 0x00000001a2fb9998 AppKit`-[NSMenuItem _corePerformAction] + 336
    frame #34: 0x00000001a2fb9714 AppKit`-[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 104
    frame #35: 0x00000001a2ff5710 AppKit`-[NSMenu performActionForItemAtIndex:] + 200
    frame #36: 0x00000001a2ff5630 AppKit`-[NSMenu _internalPerformActionForItemAtIndex:] + 76
    frame #37: 0x00000001a2ff5484 AppKit`-[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 108
    frame #38: 0x00000001a2fa1cdc AppKit`NSSLMMenuEventHandler + 640
    frame #39: 0x00000001a9137944 HIToolbox`DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1092
    frame #40: 0x00000001a9136dc4 HIToolbox`SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 356
    frame #41: 0x00000001a914cfd4 HIToolbox`SendEventToEventTarget + 40
    frame #42: 0x00000001a91ac6bc HIToolbox`SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) + 416
    frame #43: 0x00000001a91d0ee4 HIToolbox`SendMenuCommandWithContextAndModifiers + 56
    frame #44: 0x00000001a91d0e74 HIToolbox`SendMenuItemSelectedEvent + 352
    frame #45: 0x00000001a91d0ca0 HIToolbox`FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) + 100
    frame #46: 0x00000001a91d1660 HIToolbox`MenuSelectCore(MenuData*, Point, double, unsigned int, OpaqueMenuRef**, unsigned short*) + 560
    frame #47: 0x00000001a91d1380 HIToolbox`_HandleMenuSelection2 + 416
    frame #48: 0x00000001a2e970f4 AppKit`_NSHandleCarbonMenuEvent + 256
    frame #49: 0x00000001a2e96f18 AppKit`_DPSEventHandledByCarbon + 60
    frame #50: 0x00000001a2d43db8 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2256
    frame #51: 0x00000001a2d37bf0 AppKit`-[NSApplication run] + 464
    frame #52: 0x00000001a2d0f058 AppKit`NSApplicationMain + 880
    frame #53: 0x00000001025e4e18 IINA`main at AppDelegate.swift:24:7
    frame #54: 0x000000019f6e3e50 dyld`start + 2544
(lldb) 
```
</details>

<br>

**Steps to reproduce:**
Quit while playing a video in full screen. Use a script to do this over and over until the problem reproduces.

- [x] MPV does not have this problem.

**How often does this happen?**
Somewhat rare.

### LINKED ISSUE #4045: IINA 1.3.1 crashed when quit app
**System and IINA version:**
- macOS 
- Ventura 13.0 (22A380)
- IINA 
- 1.3.1 (133)

**Expected behavior:**
App quit.

**Actual behavior:**
App crashed.

<details>
<summary><b>Crash report:</b></summary>

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               IINA [28685]
Path:                  /Applications/IINA.app/Contents/MacOS/IINA
Identifier:            com.colliderli.iina
Version:               1.3.1 (133)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2022-11-07 15:10:18.3596 +0800
OS Version:            macOS 13.0 (22A380)
Report Version:        12
Anonymous UUID:        4737203F-1A31-0454-A594-14C4216DE27E

Sleep/Wake UUID:       AE116B8B-B932-4F58-8A72-C879AA892FEC

Time Awake Since Boot: 32000 seconds
Time Since Wake:       1873 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000048
Exception Codes:       0x0000000000000001, 0x0000000000000048

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [28685]

VM Region Info: 0x48 is not in any region.  Bytes before following region: 105553518919608
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libmpv.1.dylib                	       0x1037d1418 mpv_get_property + 16
1   IINA                          	       0x1028777b0 PlayerCore.syncUI(_:) + 560
2   IINA                          	       0x1028777b0 PlayerCore.syncUI(_:) + 560
3   IINA                          	       0x10287747c PlayerCore.syncUITime() + 56
4   IINA                          	       0x10278466c MainWindowController.showUI() + 372
5   IINA                          	       0x102780470 MainWindowController.windowDidExitFullScreen(_:) + 504
6   IINA                          	       0x102783f1c @objc MainWindowController.windowWillClose(_:) + 120
7   CoreFoundation                	       0x1b433258c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
8   CoreFoundation                	       0x1b43d0074 ___CFXRegistrationPost_block_invoke + 88
9   CoreFoundation                	       0x1b43cffbc _CFXRegistrationPost + 440
10  CoreFoundation                	       0x1b4303bac _CFXNotificationPost + 708
11  Foundation                    	       0x1b51f072c -[NSNotificationCenter postNotificationName:object:userInfo:] + 88
12  AppKit                        	       0x1b7fff398 -[NSWindow(NSFullScreen) _didExitFullScreen] + 336
13  AppKit                        	       0x1b7e070a8 -[_NSExitFullScreenTransitionController _doAfterExitFullScreen] + 304
14  AppKit                        	       0x1b7e07904 -[_NSExitFullScreenTransitionController _doSucceededToExitFullScreen] + 712
15  AppKit                        	       0x1b7e0813c __63-[_NSExitFullScreenTransitionController _performExitFullScreen]_block_invoke + 236
16  libxpc.dylib                  	       0x1b3fcd670 _xpc_connection_reply_callout + 124
17  libxpc.dylib                  	       0x1b3fcd560 _xpc_connection_call_reply_async + 88
18  libdispatch.dylib             	       0x1b40d7584 _dispatch_client_callout3 + 20
19  libdispatch.dylib             	       0x1b40f5710 _dispatch_mach_msg_async_reply_invoke + 344
20  libdispatch.dylib             	       0x1b40e5c70 _dispatch_main_queue_drain + 756
21  libdispatch.dylib             	       0x1b40e596c _dispatch_main_queue_callback_4CF + 44
22  CoreFoundation                	       0x1b437ed6c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
23  CoreFoundation                	       0x1b433c7ec __CFRunLoopRun + 2036
24  CoreFoundation                	       0x1b433b8a4 CFRunLoopRunSpecific + 612
25  HIToolbox                     	       0x1bd9af3bc RunCurrentEventLoopInMode + 292
26  HIToolbox                     	       0x1bd9af200 ReceiveNextEventCommon + 672
27  HIToolbox                     	       0x1bd9aef48 _BlockUntilNextEventMatchingListInModeWithFilter + 72
28  AppKit                        	       0x1b7594630 _DPSNextEvent + 632
29  AppKit                        	       0x1b75937c0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
30  AppKit                        	       0x1b77b63b0 -[NSApplication _shouldTerminate] + 700
31  AppKit                        	       0x1b77a8fb0 -[NSApplication terminate:] + 612
32  AppKit                        	       0x1b773d2f0 -[NSApplication(NSResponder) sendAction:to:from:] + 440
33  AppKit                        	       0x1b7809998 -[NSMenuItem _corePerformAction] + 336
34  AppKit                        	       0x1b7809714 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 104
35  AppKit                        	       0x1b7afab7c -[NSMenu _performActionForItem:atIndex:fromEvent:] + 212
36  AppKit                        	       0x1b7808c24 -[NSMenu performKeyEquivalent:] + 356
37  AppKit                        	       0x1b7c38090 routeKeyEquivalent + 428
38  AppKit                        	       0x1b76bfba0 -[NSApplication(NSEvent) sendEvent:] + 652
39  AppKit                        	       0x1b7912144 -[NSApplication _handleEvent:] + 60
40  AppKit                        	       0x1b7587c14 -[NSApplication run] + 500
41  AppKit                        	       0x1b755f058 NSApplicationMain + 880
42  IINA                          	       0x1026f2428 main + 12
43  dyld                          	       0x1b3f33e50 start + 2544

Thread 1:
0   libsystem_pthread.dylib       	       0x1b4258e18 start_wqthread + 0

Thread 2:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	       0x1b421ed6c semaphore_wait_trap + 8
1   caulk                         	       0x1bd6d6cfc caulk::mach::semaphore::wait_or_error() + 28
2   caulk                         	       0x1bd6b9634 caulk::concurrent::details::worker_thread::run() + 56
3   caulk                         	       0x1bd6b9278 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib       	       0x1b425e06c _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1b4258e2c thread_start + 8

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1b421edf0 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1b42308d8 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1b4227638 mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x1b421f16c mach_msg + 24
4   CoreFoundation                	       0x1b433dbdc __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1b433c4c8 __CFRunLoopRun + 1232
6   CoreFoundation                	       0x1b433b8a4 CFRunLoopRunSpecific + 612
7   AppKit                        	       0x1b76be248 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x1b425e06c _pthread_start + 148
9   libsystem_pthread.dylib       	       0x1b4258e2c thread_start + 8

Thread 4:: com.apple.coremedia.rootQueue.47
0   libsystem_kernel.dylib        	       0x1b421ed84 semaphore_timedwait_trap + 8
1   libdispatch.dylib             	       0x1b40d7b1c _dispatch_sema4_timedwait + 64
2   libdispatch.dylib             	       0x1b40d811c _dispatch_semaphore_wait_slow + 76
3   libdispatch.dylib             	       0x1b40e8d68 _dispatch_worker_thread + 324
4   libsystem_pthread.dylib       	       0x1b425e06c _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1b4258e2c thread_start + 8

Thread 5:
0   libsystem_pthread.dylib       	       0x1b4258e18 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x1b4258e18 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x1b4258e18 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x000000010296fc61   x2: 0x0000000000000005   x3: 0x000000016d710980
    x4: 0xe700000000000000   x5: 0x0000000000000001   x6: 0x00000002109a4ef8   x7: 0x0000000000000000
    x8: 0x0000000000000008   x9: 0x0000000200000003  x10: 0xfffffffe00000000  x11: 0x0000000200000003
   x12: 0x0000000000000003  x13: 0x00000000000007fd  x14: 0x00000000f8c3d068  x15: 0x00000000f8a3c835
   x16: 0x00000001037d1408  x17: 0x03000001029de631  x18: 0x0000000000000000  x19: 0x000000021204bdf0
   x20: 0x00006000008583e0  x21: 0x0000000000000000  x22: 0x000000016d710910  x23: 0x0000000000000008
   x24: 0x000000016d710900  x25: 0x00006000037c83c0  x26: 0x0000600003aca2e0  x27: 0x00000001029f7d10
   x28: 0x00000002109b36d8   fp: 0x000000016d7108f0   lr: 0x00000001028777b0
    sp: 0x000000016d7108a0   pc: 0x00000001037d1418 cpsr: 0x60001000
   far: 0x0000000000000048  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x103760000 -        0x103a3bfff libmpv.1.dylib (*) <e8089b8a-8ba0-3583-a8f2-e724a48fa25f> /Applications/IINA.app/Contents/Frameworks/libmpv.1.dylib
       0x1026ec000 -        0x10299bfff com.colliderli.iina (1.3.1) <da58f4cc-7901-3bca-a111-34e5236b0261> /Applications/IINA.app/Contents/MacOS/IINA
       0x1b42bc000 -        0x1b4793fff com.apple.CoreFoundation (6.9) <f4ff83fc-e62c-30b4-b3a9-876c8a1fd595> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1b51e7000 -        0x1b5c1ffff com.apple.Foundation (6.9) <52b2f83f-586d-32a2-8b66-ce651400ac8c> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x1b755b000 -        0x1b8462fff com.apple.AppKit (6.9) <af9f6891-70ad-3c26-af08-b747344892d2> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1b3fbe000 -        0x1b4000fff libxpc.dylib (*) <44992a1e-d222-3d40-841d-e2cf9e26f67e> /usr/lib/system/libxpc.dylib
       0x1b40d3000 -        0x1b411afff libdispatch.dylib (*) <40c9c98c-00d6-3e8e-9ad3-2ed6cf0d0cfe> /usr/lib/system/libdispatch.dylib
       0x1bd97d000 -        0x1bdcb0fff com.apple.HIToolbox (2.1.1) <02b9797f-c47d-30b7-b7b0-802d0d26f31c> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1b3f2e000 -        0x1b3fb84af dyld (*) <1f56ab4e-f398-3a9c-bfba-fbbd17808963> /usr/lib/dyld
       0x1b4257000 -        0x1b4263ffb libsystem_pthread.dylib (*) <886caca0-5762-3640-8db2-3fa3b911c062> /usr/lib/system/libsystem_pthread.dylib
       0x1b421e000 -        0x1b4256ffb libsystem_kernel.dylib (*) <6d6644d3-3db3-34c4-b1e3-c675ec5360f0> /usr/lib/system/libsystem_kernel.dylib
       0x1bd6b7000 -        0x1bd6e0fff com.apple.audio.caulk (1.0) <445d1341-52c5-3468-ba85-f01410317744> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 141
    thread_create: 113
    thread_set_state: 608

VM Region Summary:
ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
Writable regions: Total=1.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 4544K        4 
CG image                          1104K       27 
ColorSync                          672K       30 
CoreAnimation                     5216K      206 
CoreGraphics                        32K        2 
CoreImage                           16K        1 
CoreUI image data                 5632K       46 
Foundation                          48K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           462.3M       72 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         888.0M        8         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        384K        5 
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                       1504K       29 
__AUTH                            1870K      352 
__AUTH_CONST                      24.5M      576 
__CTF                               756        1 
__DATA                            21.9M      639 
__DATA_CONST                      30.1M      648 
__DATA_DIRTY                      1977K      222 
__FONT_DATA                        2352        1 
__GLSLBUILTINS                    5174K        1 
__LINKEDIT                       773.4M       71 
__OBJC_CONST                      4645K      316 
__OBJC_RO                         65.1M        1 
__OBJC_RW                         1981K        1 
__TEXT                           622.5M      671 
dyld private memory                256K        1 
mapped file                      311.1M       50 
shared memory                      928K       20 
===========                     =======  ======= 
TOTAL                              3.6G     4035 
TOTAL, minus reserved VM space     2.4G     4035 



-----------
Full Report
-----------

{"app_name":"IINA","timestamp":"2022-11-07 15:10:18.00 +0800","app_version":"1.3.1","slice_uuid":"da58f4cc-7901-3bca-a111-34e5236b0261","build_version":"133","platform":1,"bundleID":"com.colliderli.iina","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0 (22A380)","roots_installed":0,"name":"IINA","incident_id":"05E2BD89-8401-46BA-B5D0-C9ECAFC8D3EB"}
{
  "uptime" : 32000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "coalitionID" : 34620,
  "osVersion" : {
    "train" : "macOS 13.0",
    "build" : "22A380",
    "releaseType" : "User"
  },
  "captureTime" : "2022-11-07 15:10:18.3596 +0800",
  "incident" : "05E2BD89-8401-46BA-B5D0-C9ECAFC8D3EB",
  "pid" : 28685,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-11-07 15:08:33.8215 +0800",
  "procStartAbsTime" : 778769777110,
  "procExitAbsTime" : 781278237466,
  "procName" : "IINA",
  "procPath" : "\/Applications\/IINA.app\/Contents\/MacOS\/IINA",
  "bundleInfo" : {"CFBundleShortVersionString":"1.3.1","CFBundleVersion":"133","CFBundleIdentifier":"com.colliderli.iina"},
  "storeInfo" : {"deviceIdentifierForVendor":"8D166178-2F58-5A81-B4FD-7BD6F59DA4FC","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.colliderli.iina",
  "crashReporterKey" : "4737203F-1A31-0454-A594-14C4216DE27E",
  "wakeTime" : 1873,
  "sleepWakeUUID" : "AE116B8B-B932-4F58-8A72-C879AA892FEC",
  "sip" : "enabled",
  "vmRegionInfo" : "0x48 is not in any region.  Bytes before following region: 105553518919608\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-\/rwx SM=NUL  ...(unallocated)",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000048","rawCodes":[1,72],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000048"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":28685},
  "vmregioninfo" : "0x48 is not in any region.  Bytes before following region: 105553518919608\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-\/rwx SM=NUL  ...(unallocated)",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":113,"thread_set_state":608,"task_for_pid":141},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":561123,"threadState":{"x":[{"value":0},{"value":4338416737},{"value":5},{"value":6131091840},{"value":16645304222761353216},{"value":1},{"value":8868482808,"symbolLocation":0,"symbol":"protocol witness table for DefaultStringInterpolation"},{"value":0},{"value":8},{"value":8589934595},{"value":18446744065119617024},{"value":8589934595},{"value":3},{"value":2045},{"value":4173582440},{"value":4171483189},{"value":4353496072,"symbolLocation":0,"symbol":"mpv_get_property"},{"value":216172786452653617,"symbolLocation":216172782113783809,"symbol":"OBJC_CLASS_$__TtC4IINA13MPVController"},{"value":0},{"value":8892235248,"symbolLocation":0,"symbol":"type metadata for DispatchWorkItemFlags"},{"value":105553125016544},{"value":0},{"value":6131091728},{"value":8},{"value":6131091712},{"value":105553174758336},{"value":105553177912032},{"value":4338973968,"symbolLocation":0,"symbol":"direct field offset for PlaybackInfo.videoPosition"},{"value":8868542168,"symbolLocation":0,"symbol":"value witness table for Builtin.Int64"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4337399728},"cpsr":{"value":1610616832},"fp":{"value":6131091696},"sp":{"value":6131091616},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4353496088,"matchesCrashFrame":1},"far":{"value":72}},"queue":"com.apple.main-thread","frames":[{"imageOffset":463896,"symbol":"mpv_get_property","symbolLocation":16,"imageIndex":0},{"imageOffset":1619888,"symbol":"PlayerCore.syncUI(_:)","symbolLocation":560,"imageIndex":1},{"imageOffset":1619888,"symbol":"PlayerCore.syncUI(_:)","symbolLocation":560,"imageIndex":1},{"imageOffset":1619068,"symbol":"PlayerCore.syncUITime()","symbolLocation":56,"imageIndex":1},{"imageOffset":624236,"symbol":"MainWindowController.showUI()","symbolLocation":372,"imageIndex":1},{"imageOffset":607344,"symbol":"MainWindowController.windowDidExitFullScreen(_:)","symbolLocation":504,"imageIndex":1},{"imageOffset":622364,"symbol":"@objc MainWindowController.windowWillClose(_:)","symbolLocation":120,"imageIndex":1},{"imageOffset":484748,"symbol":"__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__","symbolLocation":148,"imageIndex":2},{"imageOffset":1130612,"symbol":"___CFXRegistrationPost_block_invoke","symbolLocation":88,"imageIndex":2},{"imageOffset":1130428,"symbol":"_CFXRegistrationPost","symbolLocation":440,"imageIndex":2},{"imageOffset":293804,"symbol":"_CFXNotificationPost","symbolLocation":708,"imageIndex":2},{"imageOffset":38700,"symbol":"-[NSNotificationCenter postNotificationName:object:userInfo:]","symbolLocation":88,"imageIndex":3},{"imageOffset":11158424,"symbol":"-[NSWindow(NSFullScreen) _didExitFullScreen]","symbolLocation":336,"imageIndex":4},{"imageOffset":9093288,"symbol":"-[_NSExitFullScreenTransitionController _doAfterExitFullScreen]","symbolLocation":304,"imageIndex":4},{"imageOffset":9095428,"symbol":"-[_NSExitFullScreenTransitionController _doSucceededToExitFullScreen]","symbolLocation":712,"imageIndex":4},{"imageOffset":9097532,"symbol":"__63-[_NSExitFullScreenTransitionController _performExitFullScreen]_block_invoke","symbolLocation":236,"imageIndex":4},{"imageOffset":63088,"symbol":"_xpc_connection_reply_callout","symbolLocation":124,"imageIndex":5},{"imageOffset":62816,"symbol":"_xpc_connection_call_reply_async","symbolLocation":88,"imageIndex":5},{"imageOffset":17796,"symbol":"_dispatch_client_callout3","symbolLocation":20,"imageIndex":6},{"imageOffset":141072,"symbol":"_dispatch_mach_msg_async_reply_invoke","symbolLocation":344,"imageIndex":6},{"imageOffset":76912,"symbol":"_dispatch_main_queue_drain","symbolLocation":756,"imageIndex":6},{"imageOffset":76140,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":44,"imageIndex":6},{"imageOffset":798060,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":16,"imageIndex":2},{"imageOffset":526316,"symbol":"__CFRunLoopRun","symbolLocation":2036,"imageIndex":2},{"imageOffset":522404,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":2},{"imageOffset":205756,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":7},{"imageOffset":205312,"symbol":"ReceiveNextEventCommon","symbolLocation":672,"imageIndex":7},{"imageOffset":204616,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":7},{"imageOffset":235056,"symbol":"_DPSNextEvent","symbolLocation":632,"imageIndex":4},{"imageOffset":231360,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":728,"imageIndex":4},{"imageOffset":2470832,"symbol":"-[NSApplication _shouldTerminate]","symbolLocation":700,"imageIndex":4},{"imageOffset":2416560,"symbol":"-[NSApplication terminate:]","symbolLocation":612,"imageIndex":4},{"imageOffset":1975024,"symbol":"-[NSApplication(NSResponder) sendAction:to:from:]","symbolLocation":440,"imageIndex":4},{"imageOffset":2812312,"symbol":"-[NSMenuItem _corePerformAction]","symbolLocation":336,"imageIndex":4},{"imageOffset":2811668,"symbol":"-[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:]","symbolLocation":104,"imageIndex":4},{"imageOffset":5897084,"symbol":"-[NSMenu _performActionForItem:atIndex:fromEvent:]","symbolLocation":212,"imageIndex":4},{"imageOffset":2808868,"symbol":"-[NSMenu performKeyEquivalent:]","symbolLocation":356,"imageIndex":4},{"imageOffset":7196816,"symbol":"routeKeyEquivalent","symbolLocation":428,"imageIndex":4},{"imageOffset":1461152,"symbol":"-[NSApplication(NSEvent) sendEvent:]","symbolLocation":652,"imageIndex":4},{"imageOffset":3895620,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":60,"imageIndex":4},{"imageOffset":183316,"symbol":"-[NSApplication run]","symbolLocation":500,"imageIndex":4},{"imageOffset":16472,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":4},{"imageOffset":25640,"symbol":"main","symbolLocation":12,"imageIndex":1},{"imageOffset":24144,"symbol":"start","symbolLocation":2544,"imageIndex":8}]},{"id":561168,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":561178,"name":"caulk.messenger.shared:17","frames":[{"imageOffset":3436,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":10},{"imageOffset":130300,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":11},{"imageOffset":9780,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":11},{"imageOffset":8824,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":11},{"imageOffset":28780,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":9},{"imageOffset":7724,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]},{"id":561216,"name":"com.apple.NSEventThread","frames":[{"imageOffset":3568,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":10},{"imageOffset":75992,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":10},{"imageOffset":38456,"symbol":"mach_msg_overwrite","symbolLocation":540,"imageIndex":10},{"imageOffset":4460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":10},{"imageOffset":531420,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":2},{"imageOffset":525512,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":2},{"imageOffset":522404,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":2},{"imageOffset":1454664,"symbol":"_NSEventThread","symbolLocation":172,"imageIndex":4},{"imageOffset":28780,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":9},{"imageOffset":7724,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]},{"id":561246,"name":"com.apple.coremedia.rootQueue.47","frames":[{"imageOffset":3460,"symbol":"semaphore_timedwait_trap","symbolLocation":8,"imageIndex":10},{"imageOffset":19228,"symbol":"_dispatch_sema4_timedwait","symbolLocation":64,"imageIndex":6},{"imageOffset":20764,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":76,"imageIndex":6},{"imageOffset":89448,"symbol":"_dispatch_worker_thread","symbolLocation":324,"imageIndex":6},{"imageOffset":28780,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":9},{"imageOffset":7724,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]},{"id":561670,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":562374,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]},{"id":562543,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4353032192,
    "size" : 2998272,
    "uuid" : "e8089b8a-8ba0-3583-a8f2-e724a48fa25f",
    "path" : "\/Applications\/IINA.app\/Contents\/Frameworks\/libmpv.1.dylib",
    "name" : "libmpv.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4335779840,
    "CFBundleShortVersionString" : "1.3.1",
    "CFBundleIdentifier" : "com.colliderli.iina",
    "size" : 2818048,
    "uuid" : "da58f4cc-7901-3bca-a111-34e5236b0261",
    "path" : "\/Applications\/IINA.app\/Contents\/MacOS\/IINA",
    "name" : "IINA",
    "CFBundleVersion" : "133"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7317733376,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5079040,
    "uuid" : "f4ff83fc-e62c-30b4-b3a9-876c8a1fd595",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1953.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7333638144,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 10719232,
    "uuid" : "52b2f83f-586d-32a2-8b66-ce651400ac8c",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1953.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7370813440,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15761408,
    "uuid" : "af9f6891-70ad-3c26-af08-b747344892d2",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7314595840,
    "size" : 274432,
    "uuid" : "44992a1e-d222-3d40-841d-e2cf9e26f67e",
    "path" : "\/usr\/lib\/system\/libxpc.dylib",
    "name" : "libxpc.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7315730432,
    "size" : 294912,
    "uuid" : "40c9c98c-00d6-3e8e-9ad3-2ed6cf0d0cfe",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7475810304,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "02b9797f-c47d-30b7-b7b0-802d0d26f31c",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7314006016,
    "size" : 566448,
    "uuid" : "1f56ab4e-f398-3a9c-bfba-fbbd17808963",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7317319680,
    "size" : 53244,
    "uuid" : "886caca0-5762-3640-8db2-3fa3b911c062",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7317086208,
    "size" : 233468,
    "uuid" : "6d6644d3-3db3-34c4-b1e3-c675ec5360f0",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7472902144,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 172032,
    "uuid" : "445d1341-52c5-3468-ba85-f01410317744",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 7313358848,
  "size" : 3403612160,
  "uuid" : "5667eb2d-1398-3b38-afff-a929572d4b88"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)\nWritable regions: Total=1.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 4544K        4 \nCG image                          1104K       27 \nColorSync                          672K       30 \nCoreAnimation                     5216K      206 \nCoreGraphics                        32K        2 \nCoreImage                           16K        1 \nCoreUI image data                 5632K       46 \nFoundation                          48K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           462.3M       72 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         888.0M        8         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        384K        5 \nSTACK GUARD                       56.1M        8 \nStack                             11.7M        8 \nVM_ALLOCATE                       1504K       29 \n__AUTH                            1870K      352 \n__AUTH_CONST                      24.5M      576 \n__CTF                               756        1 \n__DATA                            21.9M      639 \n__DATA_CONST                      30.1M      648 \n__DATA_DIRTY                      1977K      222 \n__FONT_DATA                        2352        1 \n__GLSLBUILTINS                    5174K        1 \n__LINKEDIT                       773.4M       71 \n__OBJC_CONST                      4645K      316 \n__OBJC_RO                         65.1M        1 \n__OBJC_RW                         1981K        1 \n__TEXT                           622.5M      671 \ndyld private memory                256K        1 \nmapped file                      311.1M       50 \nshared memory                      928K       20 \n===========                     =======  ======= \nTOTAL                              3.6G     4035 \nTOTAL, minus reserved VM space     2.4G     4035 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62fe74515312cd4599bd3c80",
      "factorPackIds" : {
        "MYRIAD_BOOSTS" : "62fe74805312cd4599bd3c81"
      },
      "deploymentId" : 240000006
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000026
    }
  ],
  "experiments" : [

  ]
}
}

Model: Macmini9,1, BootROM 8419.41.10, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: 32C1U, 6016 x 3384, Main, MirrorOff, Online
Memory Module: LPDDR4, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Sep  3 2022 03:37:22 version 18.20.379.4.7.8.143 FWID 01-e3c71b50
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB30Bus
USB Device: CSS25U36G
USB Device: USB3.0 Hub
USB Device: Expansion
USB Device: USB2.0 Hub
USB Device: Razer BlackWidow Tournament Edition Chroma
USB Device: USB Receiver
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: MD202
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
1. open an HDR video
2. quit IINA by cmd+q

- [ ] MPV does not have this problem.

**How often does this happen?**
Very often, if not every time.

### PR DESCRIPTION
**Pull request by low-batt**
This commit will:
- Add a new isClosing property to MainWindowController
- Change windowWillClose to set isClosing to true
- Change windowWillExitFullScreen and windowDidExitFullScreen to not access mpv if window is closing
- Change fsState didSet to not access mpv if window is closing
- Change windowWillOpen to set isClosing to false

These changes prevent IINA from calling mpv while mpv is asynchronously unloading the file or shutting down.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4020.

---

**Description:**

### CODE REVIEW

File: iina/MainWindowController.swift [hunk 1]
```diff
@@ -242,7 +244,9 @@ class MainWindowController: PlayerWindowController {
       switch fsState {
       case .fullscreen: player.mpv.setFlag(MPVOption.Window.fullscreen, true)
       case .animating:  break
-      case .windowed:   player.mpv.setFlag(MPVOption.Window.fullscreen, false)
+      case .windowed:
+        guard !isClosing else { return }
```
Comment (uiryuu) [inline iina/MainWindowController.swift]: I suggest put this `guard` before the `switch` statement.

**Review by uiryuu — CHANGES_REQUESTED** [review]

**Comment by icpz** [comment]
Hi, any updates on this PR?

**Comment by doersino** [comment]
Bumping the "any updates?" question - the crash after quitting is not a huge issue, but it sure is annoying.

**Comment by edphan** [comment]
@low-batt seems like uiryuu requested to have the `guard` statement before `switch`. IINA getting a crash report every time CMD + Q is quite annoying :(

**Comment by low-batt** [comment]
Sorry, was away from IINA during the holidays. Special thanks to @danshao who in my absence addressed the review comment in another PR.

I've updated this PR because with further testing I found an additional check was needed.

Hopefully we can finish the review and get this fix merged soon.

**Comment by svobs** [comment]
@low-batt I took at look at the changes and I have a couple suggestions:
- If you haven't already, try doing a text search for all Swift files in the workspace for the string `mpv.` (no spaces). It should give you all the places where the `MPVController` is referenced, though with a few false positives. My search found 21 files, but eliminating the ones for `mpv.mpvVersion`, matches in comments, and plugin stuff (`Javascript*`), I counted 15 files containing potential problem points. Not terrible. But ideally there would be checks before all of these calls. Fortunately, probably over 2/3 of them require an explicit user action or request, which would be highly unlikely between the start of `close` to the finish of `close`.
- Consider moving `isClosing` from `MainWindowController` to its parent, `PlayerWindowController`. Even if you don't need to reference it right now, it will probably be needed there in the future because this issue can theoretically happen with all types of player windows.

If you haven't noticed already, you need to cover these cases too:
1. At the start of `PlayerCore`'s `syncUI()`. This gets called several times a second, even when video is paused (hopefully that can be nailed down someday...) and looks like a prime failure point. There is already a `guard mainWindow.loaded else { return }` at its beginning which looks like a good place to add another check.
2. At the start of `MainWindowController's` `showUI()`. This is called by `mouseEntered()` which looks most dangerous, but it's called from other places too, and since a simple boolean check costs basically nothing in terms of clock cycles, adding a redundant check to prevent even a 0.001% chance of a crash is still definitely worth it.

OK after I wrote all of this, I noticed something else. Try looking through the code for checks for `mainWindow.loaded`. It looks like almost all its `guard` checks will also apply to `isClosing`! For example, I'm a little bit concerned about `VideoView`'s `refreshEdrMode()` which is called asynchronously from all sorts of places, and saw that it is also making sure `loaded` is `true`. Again, when in doubt it's a better strategy to just add more checks than necessary, given that they're trivial.

**Comment by low-batt** [comment]
The fully deterministic way to enforce the mpv requirement to not use the mpv context once mpv has been told to shutdown would be to enforce it in `MPVController`. This would require using thread locks similar to the protection that was added in `Logger`. To reduce the amount of locking it might be better to enforce it at the `PlayerCore` level and force most code to go through that class. Even if we did this `MPVController` methods that return values are a problem. If coded from scratch we might have made such methods optionally return values. Lots of code changes to retrofit that. Another choice would be to throw some sort of "shutting down" exception that is then handled specially. I'm trying to avoid such extensive changes.

The idea behind the current termination sequence is to at a high level shutdown the code that would call into mpv. For example mouse events should not be a problem because the window is closed. Issue #4020 has to do with events occurring as the window is being closed when in full screen mode, especially when legacy full scree mode is not being used.

What I am concerned about is that IINA allows mpv to initiate termination. This is what this code from `MPVController` is detecting:
```swift
    case MPV_EVENT_SHUTDOWN:
      let quitByMPV = !player.isShuttingDown
```

Seems like this would allow a window where IINA could be operating on mpv while it is shutting down. But so far I've not been able to trigger a problem.

I've been testing using various scripts that start IINA and quit IINA over and over again. This is one example:
```bash
#!/bin/bash

while true; do

    echo Starting IINA
    open -a /Users/low-batt/Library/Developer/Xcode/DerivedData/iina-gwhhvjgxybcchtdcwvmukizbfeip/Build/Products/Debug/IINA.app ~/Movies/earth.mp4

    sleep 2

    echo Instructing  IINA to Quit
    osascript -e 'activate application "IINA"' \
	      -e 'tell application "System Events" to keystroke "q" using command down'

    sleep 2

done
```

With the changes in the PR I've not been able to generate a crash.

**Comment by ghost** [comment]
> The fully deterministic way to enforce the mpv requirement to not use the mpv context once mpv has been told to shutdown would be to enforce it in `MPVController`. This would require using thread locks similar to the protection that was added in `Logger`. To reduce the amount of locking it might be better to enforce it at the `PlayerCore` level and force most code to go through that class. Even if we did this `MPVController` methods that return values are a problem. If coded from scratch we might have made such methods optionally return values. Lots of code changes to retrofit that. Another choice would be to throw some sort of "shutting down" exception that is then handled specially. I'm trying to avoid such extensive changes.
> 
> The idea behind the current termination sequence is to at a high level shutdown the code that would call into mpv. For example mouse events should not be a problem because the window is closed. Issue #4020 has to do with events occurring as the window is being closed when in full screen mode, especially when legacy full scree mode is not being used.
> 
> What I am concerned about is that IINA allows mpv to initiate termination. This is what this code from `MPVController` is detecting:
> 
> ```swift
>     case MPV_EVENT_SHUTDOWN:
>       let quitByMPV = !player.isShuttingDown
> ```
> 
> Seems like this would allow a window where IINA could be operating on mpv while it is shutting down. But so far I've not been able to trigger a problem.
> 
> I've been testing using various scripts that start IINA and quit IINA over and over again. This is one example:
> 
> ```shell
> #!/bin/bash
> 
> while true; do
> 
>     echo Starting IINA
>     open -a /Users/low-batt/Library/Developer/Xcode/DerivedData/iina-gwhhvjgxybcchtdcwvmukizbfeip/Build/Products/Debug/IINA.app ~/Movies/earth.mp4
> 
>     sleep 2
> 
>     echo Instructing  IINA to Quit
>     osascript -e 'activate application "IINA"' \
> 	      -e 'tell application "System Events" to keystroke "q" using command down'
> 
>     sleep 2
> 
> done
> ```
> 
> With the changes in the PR I've not been able to generate a crash.

Hi. Are the changes made on 1.3.1 code the sole cause of this issue? IINA v1.3.0 is fine when quitting full screen. No matter macOS version or CPU architecture.

**Comment by low-batt** [comment]
Hi GitHubIINA,
As it turns out this:
> IINA v1.3.0 is fine when quitting full screen. No matter macOS version or CPU architecture.

Is not true. In 1.3.0 and earlier versions there is a thread race condition that sometimes results in various crashes. It also causes the `Resume last playback position` feature to be unreliable. The code sends a command to mpv to shutdown using a synchronous interface. Turns out mpv treats this as a special case and starts processing the shutdown asynchronously in a background thread while the IINA code thinking that has been completed continues with application termination on the main thread. Depending upon timing of these two threads bad things happen. The code is broken.

For 1.3.1 IINA was changed to properly wait for mpv to shutdown. That change had a side effect of increasing the window of vulnerability for thread coordination problems to appear. Multiple problems that were rarely experienced with 1.3.0 and earlier releases became frequent. Issue #4020 is one of those. It was on the list to fix for 1.3.1, but that release was cut early in a rush due to Apple releasing macOS Ventura which broke HDR.

**Comment by ghost** [comment]
> Hi GitHubIINA, As it turns out this:
> 
> > IINA v1.3.0 is fine when quitting full screen. No matter macOS version or CPU architecture.
> 
> Is not true. In 1.3.0 and earlier versions there is a thread race condition that sometimes results in various crashes. It also causes the `Resume last playback position` feature to be unreliable. The code sends a command to mpv to shutdown using a synchronous interface. Turns out mpv treats this as a special case and starts processing the shutdown asynchronously in a background thread while the IINA code thinking that has been completed continues with application termination on the main thread. Depending upon timing of these two threads bad things happen. The code is broken.
> 
> For 1.3.1 IINA was changed to properly wait for mpv to shutdown. That change had a side effect of increasing the window of vulnerability for thread coordination problems to appear. Multiple problems that were rarely experienced with 1.3.0 and earlier releases became frequent. Issue #4020 is one of those. It was on the list to fix for 1.3.1, but that release was cut early in a rush due to Apple releasing macOS Ventura which broke HDR.

Hi.  Thank you for the response. Waiting for the next version of IINA.

**Comment by svobs** [comment]
Felt compelled to attempt a (loose) analogy of the current problem.

Imagine there is a freeway for carrying traffic between IINA and mpv, which goes through an underwater tunnel, because the two are on separate islands. There are many semi-independent sections of IINA and they all have access to the freeway. If one needs something from mpv, or needs to send it a message, it sends a car onto the freeway and through the tunnel toward mpv. But when mpv gets the signal to shut down, it immediately blows up the tunnel. This destroys any cars which are in it at the time, and any cars IINA sends to it afterwards, because once on the freeway they can't stop. But if IINA ever loses a single car, the operating system detects it and crashes IINA. But most of the components in IINA are not even aware that mpv has been sent the shutdown signal, and there is a small amount of time before they are told that IINA itself is shutting down, and until then they carry on like usual. Because there is a degree of randomness in traffic getting to the onramps, they may or may not get on before IINA quits and thus may only cause a crash infrequently.

So, using the analogy, the agreed-upon fix is to add traffic signals to the on-ramps of that freeway, so that a given on-ramp's signal goes red as soon as IINA sends the shutdown signal, preventing tragedy.

But it's a lot of work to add red lights to 200+ on-ramps, sure... My only objection is that this fix doesn't go far enough - this fix adds a red light only at the places which have been reported as crashing; whereas my analysis of the code points a few more potential danger points. They may not fail now but they could sometime in the future due either to updates in IINA, updates to MacOS's scheduling system, or hardware changes. These would be nice to avoid, given IINA's relatively long time between even bugfix releases... But I don't oppose this fix. It should go in ASAP.

**Review by Coeur — APPROVED** [review]
The change is good, and addresses the problem that was being consistently observed.

This change should preferably be merged before next release.
If further code refactoring are desired, those can be done in the future but shouldn't block this fix from being merged now.

**Comment by low-batt** [comment]
I've marked issue #4020 as high priority. The plan is to fix this in the next IINA release, either with this PR or with a different fix depending upon feedback from other reviewers.

**Review by uiryuu — APPROVED** [review]
Approve for 1.3.2 release; further refactor can be done later if needed
