### PR TITLE
Fix: cursor lost when dragging clip view edges

### LINKED ISSUE #4299: Custom crop view resize issues
**System and IINA version:**

- macOS Ventura 13.3
- IINA 1.3.1

Start IINA and play a video, open "Quick Settings" panel and select Crop - "Custom...". Drag the right edge over the left boundary and release.

**Expected behavior:**

Drag the left edge of the box, should be able to resize the box again.

**Actual behavior:**

Unable to resize by drag the left edge, and its hit-box stays on the right side.

screenshot

</details>

<br>

</details>

<br>

**Steps to reproduce:**

https://user-images.githubusercontent.com/34335406/227890268-c57467a0-158d-4b8f-b46c-81bb3dd3020f.mov

- [x] MPV does not have this problem.

**How often does this happen?**

Every time.

### PR DESCRIPTION
**Pull request by yuxiqian**
Start IINA and play a video, open "Quick Settings" panel and select Crop - "Custom...". Drag the right edge over the left boundary and release. The cursor that should appear on the left edge will be lost.

- [x] I have read [CONTRIBUTING.md](https://github.com/iina/iina/blob/develop/CONTRIBUTING.md)
- [x] This implements/fixes issue #4299 .

---

**Description:**

In `CropBoxView.swift`, it uses a `boxRect: NSRect` to store currently selected clip region, and drew cursor rects around it to capture dragging events. `boxRect.size` can be negative, indicating that it expands southwest from its origin point.

However, `NSRect.width` and `NSRect.height` are always positive, so the cursor rects (colored in red) are misplaced.

A screenshot of misplaced cursor rects

Using `NSRect.size.width` and `NSRect.size.height` should fix this problem.

### CODE REVIEW

File: iina/CropBoxView.swift [hunk 1]
```diff
@@ -220,13 +219,27 @@ class CropBoxView: NSView {
...
+        x -= w
+      }
+      if h < 0 {
+        h = -h
+        y -= h
+      }
+      return NSMakeRect(x, y, w, h)
+    }
+    
+    rectTop = makeRect(x, y-2, w, 4)
```
Comment (uiryuu) [inline iina/CropBoxView.swift]: You can call `standardized` after `NSMakeRect`, which does the exact same thing as your help function

**Review by uiryuu — COMMENTED** [review]
We always welcome new contributors! And I didn't notice that it's not needed to normalize after `mouseUp`, so your solution is actually better than mine! Please re-open your pull request if you want and follow the code review :)

File: iina/CropBoxView.swift (hunk 1 above)
Comment (yuxiqian) [reply iina/CropBoxView.swift]: Thanks for your advice! Reopened and cleaned up code.

File: iina/CropBoxView.swift [hunk 2]
```diff
@@ -220,13 +219,13 @@ class CropBoxView: NSView {
...
-    let w = boxRect.width
-    let h = boxRect.height
-
-    rectTop = NSMakeRect(x, y-2, w, 4)
-    rectBottom = NSMakeRect(x, y+h-2, w, 4)
-    rectLeft = NSMakeRect(x-2, y+2, 4, h-4)
-    rectRight = NSMakeRect(x+w-2, y+2, 4, h-4)
+    let w = boxRect.size.width
+    let h = boxRect.size.height
+
```
Comment (uiryuu) [inline iina/CropBoxView.swift]: Please remove trailing spaces

**Review by uiryuu — CHANGES_REQUESTED** [review]

File: iina/CropBoxView.swift (hunk 2 above)
Comment (yuxiqian) [reply iina/CropBoxView.swift]: Done

**Review by uiryuu — APPROVED** [review]

**Comment by uiryuu** [comment]
Thanks
